// Generated by model/tiny_ai/gen_rom.py from model/tiny_ai/weights.json; do not edit.
// source sha256 caf0c99cdb2d82c6b71cf5eb46199ad6cd0f3c66dca0d5f0d71a85fa8fb14781
`timescale 1ns/1ps
// The 2x2 kernel (bit 0 = top-left, 1 = top-right, 2 = bottom-left, 3 = bottom-right) and the neuron threshold.
module vision_block_rom (
    output wire [3:0] kernel,
    output wire [2:0] threshold
);
    assign kernel    = 4'b1111;
    assign threshold = 3'd4;
endmodule
