// Generated by model/tiny_ai/gen_rom.py from model/tiny_ai/weights.json; do not edit.
// source sha256 1f192d93b68b040882bccc6255d41137d6a9ed207fc1b3dc36b725a8cfd7446e
`timescale 1ns/1ps
// The 2x2 kernel (bit 0 = top-left, 1 = top-right, 2 = bottom-left, 3 = bottom-right) and the neuron threshold.
module vision_block_rom (
    output wire [3:0] kernel,
    output wire [2:0] threshold
);
    assign kernel    = 4'b1111;
    assign threshold = 3'd4;
endmodule
