// Generated by model/precision_hw/gen.py from model/precision_hw/golden.py; do not edit.
// source sha256 a16608a9e3fc8c7e91360bb384c920acd149c56aadb3e8ec7c184e84a71ac10e
`timescale 1ns/1ps
// prec_bin parameter ROM (model/precision_hw/spec.md): 1-bit weights (1 = +1, 0 = -1: the sign of the fp32 weight, w >= 0 -> 1) and the integer threshold T of the XNOR-popcount neuron: class = (matches >= T).
// Constants are continuous assignments (no always block): read by the one serial MAC, weight[addr] per input.
module prec_bin_rom (
    input  wire [3:0] addr,        // pixel index 0..8, raster order (>= 9 reads 0)
    output wire       weight,
    output wire [3:0] threshold
);
    localparam       W0 = 1'b1;   // fp32 +0.014786
    localparam       W1 = 1'b1;   // fp32 +0.291126
    localparam       W2 = 1'b1;   // fp32 +0.028851
    localparam       W3 = 1'b0;   // fp32 -0.316742
    localparam       W4 = 1'b0;   // fp32 -0.019083
    localparam       W5 = 1'b0;   // fp32 -0.267208
    localparam       W6 = 1'b1;   // fp32 +0.044593
    localparam       W7 = 1'b1;   // fp32 +0.294643
    localparam       W8 = 1'b1;   // fp32 +0.000830
    localparam [3:0] T  = 4'd3;   // fitted on the binarised training set
    assign weight = (addr == 4'd0) ? W0 :
                    (addr == 4'd1) ? W1 :
                    (addr == 4'd2) ? W2 :
                    (addr == 4'd3) ? W3 :
                    (addr == 4'd4) ? W4 :
                    (addr == 4'd5) ? W5 :
                    (addr == 4'd6) ? W6 :
                    (addr == 4'd7) ? W7 :
                    (addr == 4'd8) ? W8 : 1'b0;
    assign threshold = T;
endmodule
