#!/usr/bin/env python3
"""gen.py -- generate, from golden.py, for each variant in golden.VARIANTS:
  designs/kv_attn_<v>/rtl/kv_attn_<v>_rom.v   embeddings + projection matrices + biases, continuous assigns only
  designs/kv_attn_<v>/tb/vectors.hex          command-sequence vectors (record layout below, and in spec.md section 9)
Every generated file carries the sha256 of its inputs (golden.py, gen.py). Files are written only when their content
changes, so a second run writes nothing. Never edit the outputs; change golden.py and re-run:
  python3 model/kv_attention/gen.py

Vector file: $readmemh of 8-bit words in 40-word records; `//` comments allowed. Record 0 is the header:
  [0]=A5 [1]=record count high [2]=record count low (records after the header) [3]=N [4]=KV bits [5]=ring [6]=format version 1.
Records 1..count are played IN ORDER (the engine state carries over from record to record):
  type 01 COMMAND   [1] n_in (1..28) [2] n_out (2 or 8) [3] expected latency (cycles) [4..11] expected output beats
                    [12..12+n_in-1] input beats (s_last on the last). m_last is expected on beat n_out-1 only.
  type 02 RST_IDLE  pulse rst for 2 cycles between commands; every field after [0] is 0; the cache is empty afterwards.
  type 03 RST_MID   [1] n_in: drive n_in beats [12..] with s_last = 0 (an unfinished frame), then pulse rst; cache empty afterwards.
  type 04 RST_PEND  [1] n_in: send the whole frame [12..] (s_last on the last), wait for m_valid, do NOT take the response,
                    pulse rst; cache empty afterwards. Expected output fields are 0 and not checked.
"""
import hashlib
import os
import sys
sys.dont_write_bytecode = True
HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)
import golden as g   # noqa: E402

REC = 40
T_CMD, T_RST_IDLE, T_RST_MID, T_RST_PEND = 1, 2, 3, 4
MAX_IN, MAX_OUT = 28, 8
MAX_RECORDS = 3000


def sha256_of(*paths):
    h = hashlib.sha256()
    for p in paths:
        h.update(os.path.relpath(p, REPO).encode() + b"\0" + open(p, "rb").read())
    return h.hexdigest()


def write_if_changed(path, text):
    try:
        if open(path).read() == text:
            return False
    except OSError:
        pass
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(text)
    return True


# ------------------------------------------------------------------------------------------------------- ROM
def lit8(v):
    return "8'h%02X" % (v & 0xFF)


def rom_verilog(name, h):
    mats = {}
    for nm, w in (("WQ", g.WQ), ("WK", g.WK), ("WV", g.WV)):
        mats[nm] = "{" + ", ".join(lit8(w[r][c]) for r in reversed(range(4)) for c in reversed(range(4))) + "}"
    vecs = {}
    for nm, b in (("BQ", g.BQ), ("BK", g.BK), ("BV", g.BV)):
        vecs[nm] = "{" + ", ".join(lit8(b[i]) for i in reversed(range(4))) + "}"
    emb_rows = []
    for t in reversed(range(g.VOCAB)):
        e = g.EMB[t]
        emb_rows.append("{" + ", ".join(lit8(e[i]) for i in reversed(range(4))) + "}   // token %2d = %s: e0=%2d e1=%2d e2=%2d e3=%d"
                        % (t, g.tname(t), e[0], e[1], e[2], e[3]))
    emb = "{\n        " + "\n        ".join(r if i == len(emb_rows) - 1 else r.replace("}   //", "},  //", 1)
                                          for i, r in enumerate(emb_rows)) + "\n    }"
    return """// Generated by model/kv_attention/gen.py from model/kv_attention/golden.py; do not edit.
// source sha256 %(h)s
`timescale 1ns/1ps
// Parameter ROM of %(n)s: the token embedding table and the Wq / Wk / Wv matrices and biases (spec.md section 2).
// Continuous assigns only. int8 two's complement everywhere.
//   emb     {e3, e2, e1, e0} of token `token` (4 x int8, e0 in bits [7:0]); the engine adds the position to e3.
//   wq/wk/wv  16 x int8, entry (row r, column c) at bits [8*(4*r+c) +: 8]; out_r = sum_c W[r][c]*x[c] + b[r].
//   bq/bk/bv   4 x int8, b[r] at bits [8*r +: 8].
// Position embedding (not stored): x = emb + (0, 0, 0, pos), pos = 0..31 (saturating).
module %(n)s_rom (
    input  wire  [3:0]  token,
    output wire [31:0]  emb,
    output wire [127:0] wq,
    output wire [127:0] wk,
    output wire [127:0] wv,
    output wire [31:0]  bq,
    output wire [31:0]  bk,
    output wire [31:0]  bv
);
    localparam [16*32-1:0] EMB = %(emb)s;
    assign emb = EMB[token*32 +: 32];
    assign wq  = %(wq)s;
    assign wk  = %(wk)s;
    assign wv  = %(wv)s;
    assign bq  = %(bq)s;
    assign bk  = %(bk)s;
    assign bv  = %(bv)s;
endmodule
""" % dict(h=h, n=name, emb=emb, wq=mats["WQ"], wk=mats["WK"], wv=mats["WV"], bq=vecs["BQ"], bk=vecs["BK"], bv=vecs["BV"])


# ------------------------------------------------------------------------------------------------------- vectors
class Script:
    def __init__(self, name):
        self.name, self.eng, self.recs = name, g.Engine(name), []

    def _rec(self, typ, n_in, n_out, lat, outs, ins, label):
        assert n_in <= MAX_IN and n_out <= MAX_OUT
        w = [typ, n_in, n_out, lat] + list(outs) + [0] * (8 - len(outs)) + list(ins) + [0] * (MAX_IN - len(ins))
        assert len(w) == REC and all(0 <= x <= 255 for x in w)
        self.recs.append((w, label))

    def cmd(self, beats, label=""):
        out, lat, _ = self.eng.command(list(beats))
        self._rec(T_CMD, len(beats), len(out), lat, out, beats, label)
        return out

    def rst_idle(self, label="hw reset"):
        self.eng.reset(); self._rec(T_RST_IDLE, 0, 0, 0, [], [], label)

    def rst_mid(self, beats, label="reset mid-frame"):
        self.eng.reset(); self._rec(T_RST_MID, len(beats), 0, 0, [], beats, label)

    def rst_pend(self, beats, label="reset with a response pending"):
        self.eng.reset(); self._rec(T_RST_PEND, len(beats), 0, 0, [], beats, label)

    def prefill(self, toks, label=""):
        return self.cmd([g.OPC_PREFILL] + list(toks), label)

    def decode(self, tok, label=""):
        return self.cmd([g.OPC_DECODE, tok], label)

    def reset_cmd(self, label=""):
        return self.cmd([g.OPC_RESET], label)


def build(name):
    p = g.VARIANTS[name]
    N, ring, bits = p["N"], p["ring"], p["bits"]
    s = Script(name)
    rng = g.LCG(0x4B56 + N * 16 + bits + ring)
    rt = lambda: rng.below(g.VOCAB)
    T = lambda k, v: 4 * k + v

    # A. protocol errors on an empty cache
    s.cmd([0x00], "bad opcode 00"); s.cmd([0x04], "bad opcode 04"); s.cmd([0x80, 1, 2], "bad opcode 80 with payload")
    s.cmd([0xFF], "bad opcode FF")
    s.cmd([g.OPC_RESET, 0], "RESET with an extra beat: BAD_FRAME")
    s.reset_cmd("RESET on empty")
    s.prefill([], "PREFILL with zero tokens")
    s.cmd([g.OPC_DECODE], "DECODE without a token: BAD_FRAME")
    s.cmd([g.OPC_DECODE, 1, 2], "DECODE with two tokens: BAD_FRAME")
    s.decode(16, "DECODE bad token 16"); s.decode(255, "DECODE bad token 255")
    s.cmd([g.OPC_DECODE, 200, 1], "DECODE bad frame beats bad token (frame wins)")
    s.decode(T(1, 2), "DECODE on an empty cache: index FF, appends")
    s.decode(T(1, 3), "DECODE with one entry")
    s.prefill([T(2, 1), 16, T(3, 3)], "PREFILL stops at bad token 16 (token before it is cached)")
    s.prefill([T(3, 3)], "PREFILL one token")
    s.reset_cmd("RESET with entries")
    s.decode(T(0, 0), "DECODE after RESET (empty)")
    s.reset_cmd()

    # B. every (cached token, query token) pair: every embedding row as k/v and as q, hit and miss
    for c in range(g.VOCAB):
        for q in range(g.VOCAB):
            s.reset_cmd("pair c=%s q=%s" % (g.tname(c), g.tname(q)))
            s.prefill([c]); s.decode(q)

    # C. every fill level n = 0..N (the latency formula n+3), random contents
    for n in range(N + 1 if ring else N):
        for rep in range(3):
            s.reset_cmd("fill %d" % n)
            if n:
                s.prefill([rt() for _ in range(n)])
            s.decode(rt(), "DECODE with n=%d cached" % n)

    # D. chains of one key: recency; ties where the format cannot resolve them
    for a in range(4):
        s.reset_cmd("same-key chain key %s" % "ABCD"[a])
        m = N if not ring else N + 4
        s.prefill([T(a, i % 4) for i in range(m)], "%d tokens of one key" % m)
        s.decode(T(a, 0), "query the same key"); 
        s.decode(T((a + 1) % 4, 0), "query another key (no key match)")
        if not ring:
            s.reset_cmd()
            s.prefill([T(a, i % 4) for i in range(N - 1)])
            s.decode(T(a, 1), "last free slot: cache becomes full")
            s.decode(T(a, 2), "DECODE on a full cache")

    # E. capacity and overflow
    if not ring:
        s.reset_cmd("fill to N")
        s.prefill([rt() for _ in range(N)], "PREFILL exactly N tokens")
        s.prefill([rt()], "PREFILL on a full cache: CACHE_FULL")
        s.prefill([], "PREFILL zero tokens on a full cache: ok")
        s.decode(rt(), "DECODE on a full cache: CACHE_FULL")
        s.prefill([16], "bad token beats full: BAD_TOKEN")
        s.reset_cmd("frame longer than N")
        s.prefill([rt() for _ in range(N + 3)], "PREFILL N+3 tokens: first N cached, then CACHE_FULL")
        s.decode(rt(), "DECODE: still full")
        s.reset_cmd("two prefill frames")
        s.prefill([rt() for _ in range(N // 2)]); s.prefill([rt() for _ in range(N // 2 + 2)], "second frame overflows")
        s.reset_cmd("bad token mid-frame")
        s.prefill([rt(), rt(), 99, rt(), rt()], "bad token at position 3: two cached, rest ignored")
        s.decode(rt(), "DECODE afterwards works")
        s.reset_cmd()
    else:
        s.reset_cmd("ring wrap by prefill")
        s.prefill([rt() for _ in range(N)], "PREFILL exactly N")
        s.prefill([rt() for _ in range(5)], "PREFILL 5 more: overwrites slots 0..4")
        for _ in range(N + 3):
            s.decode(rt(), "DECODE past the wrap (latency N+3, count stays N)")
        s.reset_cmd("long frame")
        s.prefill([rt() for _ in range(27)], "PREFILL 27 tokens in one frame")
        s.decode(rt()); s.decode(rt())
        s.reset_cmd("position saturation")
        for _ in range(4):
            s.prefill([T(1, i % 4) for i in range(10)], "10 tokens of one key; 40 total saturates pos at 31")
        for a in range(4):
            s.decode(T(a, 0), "DECODE after position saturation (ties -> lowest slot)")
        s.prefill([16, 1], "bad token in ring prefill")
        s.reset_cmd()

    # F. resets in the middle of things
    s.reset_cmd(); s.prefill([rt() for _ in range(min(N, 5))])
    s.rst_idle("hw reset with entries cached")
    s.decode(rt(), "after hw reset: empty cache, latency 3")
    s.prefill([rt(), rt(), rt()])
    s.rst_mid([g.OPC_PREFILL, rt(), rt()], "hw reset in the middle of a PREFILL frame")
    s.decode(rt(), "after reset mid-frame: empty cache")
    s.prefill([rt(), rt(), rt()])
    s.rst_pend([g.OPC_DECODE, rt()], "hw reset with a DECODE response waiting")
    s.decode(rt(), "after reset with pending response: empty cache")
    s.rst_mid([g.OPC_DECODE], "hw reset after the DECODE opcode beat")
    s.prefill([rt(), rt()])
    s.rst_pend([g.OPC_PREFILL, rt()], "hw reset with a PREFILL response waiting")
    s.reset_cmd("RESET_CACHE after hw resets"); s.decode(rt())

    # G. random episodes (fixed seed): prompt, queries, occasional protocol errors
    n_ep = 0
    while len(s.recs) < 2700 - 200 and n_ep < 60:
        n_ep += 1
        s.reset_cmd("random episode %d" % n_ep)
        total = N + (2 * N if ring else 0)
        pl = 1 + rng.below(N if not ring else 2 * N)
        s.prefill([rt() for _ in range(pl)])
        for _ in range(min(total, N + 2) if not ring else 12):
            r = rng.below(10)
            if r < 7:
                s.decode(rt())
            elif r == 7:
                s.prefill([rt() for _ in range(1 + rng.below(3))])
            elif r == 8:
                s.cmd([rng.below(256) if rng.below(2) else g.OPC_DECODE] + [rt() for _ in range(rng.below(3))])
            else:
                s.decode(rng.below(256))
    s.rst_idle("final hw reset")
    s.decode(rt(), "final: empty cache")
    assert len(s.recs) <= MAX_RECORDS, len(s.recs)
    return s


def vectors_text(name, h):
    s = build(name)
    p = g.VARIANTS[name]
    n = len(s.recs)
    lines = ["// Generated by model/kv_attention/gen.py from model/kv_attention/golden.py; do not edit.",
             "// source sha256 %s" % h,
             "// %s: 40-word records, header first; layout in model/kv_attention/gen.py and spec.md section 9." % name]
    hdr = [0xA5, n >> 8, n & 0xFF, p["N"], p["bits"], p["ring"], 1] + [0] * (REC - 7)
    lines.append(" ".join("%02x" % x for x in hdr) + "  // header: A5, records hi/lo, N, kv bits, ring, version")
    for i, (w, label) in enumerate(s.recs, 1):
        typ = w[0]
        kind = {T_CMD: "CMD", T_RST_IDLE: "RST_IDLE", T_RST_MID: "RST_MID", T_RST_PEND: "RST_PEND"}[typ]
        lines.append(" ".join("%02x" % x for x in w) + "  // %d %s %s" % (i, kind, label))
    return "\n".join(lines) + "\n"


def main():
    h = sha256_of(os.path.join(HERE, "golden.py"), os.path.abspath(__file__))
    changed = 0
    for name in g.VARIANTS:
        d = os.path.join(REPO, "designs", name)
        changed += write_if_changed(os.path.join(d, "rtl", name + "_rom.v"), rom_verilog(name, h))
        changed += write_if_changed(os.path.join(d, "tb", "vectors.hex"), vectors_text(name, h))
    print("kv_attention: %d file(s) written, %d variants" % (changed, len(g.VARIANTS)))


if __name__ == "__main__":
    main()
