#!/usr/bin/env python3
"""gen_rom.py -- generate, from weights.json and golden.py:
  designs/image_text_match/rtl/image_text_match_rom.v   the parameter ROM (two kernels + thresholds, text embedding table, similarity threshold)
  designs/image_text_match/tb/vectors.hex               test vectors for tb/image_text_match_tb.v
Every output carries the sha256 of its inputs. Files are rewritten only when their content changes.

Vector file (same layout as model/tiny_ai/gen_rom.py): $readmemh of 8-bit words in 16-word records. Record 0 is a
header: A5, count high, count low. Each case record: [0] number of beats (1..12), [1..12] s_data of each beat
(s_last on the last), [13] expected beat 0, [14] expected beat 1, [15] expected latency.
Cases: all 2,048 (image, caption) pairs, then protocol cases: every short frame length (1..9), two long frames
(11, 12 beats), and an out-of-range item (2 and 0xFF) at each of the 10 positions."""
import os
import golden

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = golden.REPO
MAX_BEATS = 12


def header(h):
    return ("// Generated by model/image_text_match/gen_rom.py from model/image_text_match/weights.json; do not edit.\n"
            "// source sha256 %s\n`timescale 1ns/1ps\n" % h)


def slit(v, bits):
    return ("%d'sd%d" % (bits, v)) if v >= 0 else ("-%d'sd%d" % (bits, -v))


def rom_verilog(w, h):
    ka, kb = w["image_encoder"]
    kbits = lambda k: "".join(str(b) for b in reversed(k["kernel"]))
    names = golden.spec()["captions"]
    emb = []
    for t, e in enumerate(w["text_embedding"]):
        assert all(-4 <= v <= 3 for v in e)
        emb.append("{" + ", ".join(slit(v, 3) for v in reversed(e)) + "}")
    return header(h) + """// Learned parameters of image_text_match (continuous assigns only).
//   kernel_a / kernel_b : 3-tap binary kernels of the two image neurons (bit i = weight of pixel i of a line)
//   thr_a / thr_b       : neuron thresholds (fire when matches >= thr)
//   emb                 : text embedding of `token`: 6 signed 3-bit weights, packed {B_diags, B_rows, B_cols, A_diags, A_rows, A_cols}
//   sim_thr             : class = (similarity >= sim_thr)
module image_text_match_rom (
    input  wire        [1:0]  token,
    output wire        [2:0]  kernel_a,
    output wire        [1:0]  thr_a,
    output wire        [2:0]  kernel_b,
    output wire        [1:0]  thr_b,
    output wire signed [6:0]  sim_thr,
    output wire        [17:0] emb
);
    assign kernel_a = 3'b%s;
    assign thr_a    = 2'd%d;
    assign kernel_b = 3'b%s;
    assign thr_b    = 2'd%d;
    assign sim_thr  = %s;
    // %s
    assign emb = (token == 2'd0) ? %s :   // %s
                 (token == 2'd1) ? %s :   // %s
                 (token == 2'd2) ? %s :   // %s
                                   %s;    // %s
endmodule
""" % (kbits(ka), ka["threshold"], kbits(kb), kb["threshold"], slit(w["threshold"], 7),
       "embedding rows: one per caption token",
       emb[0], names[0], emb[1], names[1], emb[2], names[2], emb[3], names[3])


def cases():
    full = [1] * 9 + [3]
    out = [x for x, _ in golden.truth_table()]
    out += [full[:k] for k in range(1, 10)]
    out += [full + [1], full + [0, 1]]
    for i in range(10):
        out.append(full[:i] + [4 if i == 9 else 2] + full[i + 1:])
        out.append(full[:i] + [0xFF] + full[i + 1:])
    assert all(1 <= len(c) <= MAX_BEATS for c in out)
    return out


def vectors(w, h):
    cs = cases()
    lines = ["// Generated by model/image_text_match/gen_rom.py from weights.json and golden.py; do not edit.",
             "// source sha256 %s" % h,
             "// image_text_match: %d cases (record layout in model/image_text_match/gen_rom.py)" % len(cs),
             " ".join("%02x" % v for v in [0xA5, len(cs) >> 8, len(cs) & 0xFF] + [0] * 13)]
    for c in cs:
        b0, b1, lat = golden.run(c, w)
        rec = [len(c)] + c + [0] * (MAX_BEATS - len(c)) + [b0, b1, lat]
        lines.append(" ".join("%02x" % v for v in rec))
    return "\n".join(lines) + "\n", len(cs)


def write_if_changed(path, text):
    try:
        if open(path).read() == text:
            return
    except OSError:
        pass
    open(path, "w").write(text)


def main():
    w = golden.params()
    h = golden.sha256_of(golden.WEIGHTS_PATH, os.path.join(HERE, "golden.py"), os.path.abspath(__file__), golden.SPEC_PATH)
    rom = os.path.join(REPO, "designs", "image_text_match", "rtl", "image_text_match_rom.v")
    vec = os.path.join(REPO, "designs", "image_text_match", "tb", "vectors.hex")
    os.makedirs(os.path.dirname(rom), exist_ok=True)
    os.makedirs(os.path.dirname(vec), exist_ok=True)
    write_if_changed(rom, rom_verilog(w, h))
    text, n = vectors(w, h)
    write_if_changed(vec, text)
    print("gen_rom: image_text_match %s, %s (%d cases)" % (os.path.relpath(rom, REPO), os.path.relpath(vec, REPO), n))


if __name__ == "__main__":
    main()
