"""pytest tests/tools/test_hermes_context.py: .hermes.md (the single context file Hermes Agent reads in this repo) is generated by
scripts/docs/make_hermes_context.py from tools/prompts/master_prompt.txt, the HARD RULES of CLAUDE.md and a hand-written tool
routing block; it must be in sync, within budget, name every design, and only name tools that tools/hermes_tools.json exposes.
Run: build/agent/venv/bin/python -m pytest -q tests/tools/test_hermes_context.py
Pass: every test passes. Fix a stale file with: python3 scripts/docs/make_hermes_context.py
Docs: build/agent/tool_eval_PLAN.md (item D), docs/HERMES_AGENT_INTEGRATION.md"""
import json
import os
import subprocess
import sys

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
GEN = os.path.join(REPO, "scripts", "docs", "make_hermes_context.py")
sys.path.insert(0, os.path.join(REPO, "scripts", "lib"))
import repo  # noqa: E402


import pytest  # noqa: E402

# the tool-calling eval moves .hermes.md aside for its baseline variants (build/agent/hermes.md.hold exists meanwhile)
pytestmark = pytest.mark.skipif(os.path.exists(os.path.join(REPO, "build", "agent", "hermes.md.hold")) and not os.path.exists(os.path.join(REPO, ".hermes.md")),
                                reason="eval variant run in progress: .hermes.md is temporarily aside")


def test_in_sync_and_tools_exist():
    """Pins down: .hermes.md equals the generator output and its routing block names only exposed tools."""
    r = subprocess.run([sys.executable, GEN, "--check"], capture_output=True, text=True, cwd=REPO)
    assert r.returncode == 0, r.stderr + r.stdout


def test_content():
    """Pins down: size budget, every design named, HARD RULES and the confirm protocol present, no absolute home path."""
    t = open(os.path.join(REPO, ".hermes.md"), encoding="utf-8").read()
    assert len(t) // 4 <= 3000
    for d in repo.all_designs():
        assert d in t, d
    for w in ("HARD RULES", "yes, run", "confirm_run", "gui_command", "CLOCK_PERIOD"):
        assert w in t, w
    assert "/Users/" not in t
    cur = json.load(open(os.path.join(REPO, "tools", "hermes_tools.json")))
    assert set(cur.get("core", [])) <= set(cur["include"])
