#!/usr/bin/env python3
# Docs: docs/RESULTS.md, docs/CODE_MAP.md
"""code_map.py -- generate docs/CODE_MAP.md: per area, file -> one-line purpose -> parent doc, plus the reverse index (doc -> files).
Run: make code-map   (python3 scripts/docs/code_map.py). Input: the `Docs:` header line of every code file, or
tests/traceability_map.txt for files that must not be edited (model/**). Output: docs/CODE_MAP.md. Standard library only.
"""
import os, sys

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, os.path.join(REPO, "tests"))
import check_traceability as ct   # noqa: E402

AREAS = [("scripts", "scripts/"), ("tools", "tools/"), ("examples", "examples/"), ("tests", "tests/"), ("model", "model/"),
         ("firmware / soc_sim", ("firmware/", "soc_sim/")), ("caravel_sim", "caravel_sim/"), ("precheck", "precheck/")]


def esc(s):
    return s.replace("|", "\\|")


def main():
    files = ct.code_files()
    rows = {}
    for f in files:
        rows[f] = (ct.header_purpose(f), ct.parse_docs(f) or [])
    out = ["# Code map", "",
           "Generated by `make code-map` (scripts/docs/code_map.py) from the `Docs:` header line of each code file, or from",
           "tests/traceability_map.txt for files that must stay byte-identical (model/**). Do not edit by hand; checked by",
           "`python3 tests/check_traceability.py`. Files under designs/ and shared/ are documented by each design's NOTES.md.", ""]
    used = set()
    for title, pref in AREAS:
        sel = [f for f in files if f.startswith(pref)]
        used.update(sel)
        if not sel:
            continue
        out += ["## " + title, "", "| file | purpose | parent doc |", "|---|---|---|"]
        for f in sel:
            p, d = rows[f]
            out.append("| `%s` | %s | %s |" % (f, esc(p), ", ".join("[%s](../%s)" % (x, x) for x in d) or "MISSING"))
        out.append("")
    rest = [f for f in files if f not in used]
    if rest:
        out += ["## other", "", "| file | purpose | parent doc |", "|---|---|---|"]
        for f in rest:
            p, d = rows[f]
            out.append("| `%s` | %s | %s |" % (f, esc(p), ", ".join(d) or "MISSING"))
        out.append("")
    rev = {}
    for f, (p, d) in rows.items():
        for x in d:
            rev.setdefault(x, []).append(f)
    out += ["## Reverse index: document -> files", ""]
    for x in sorted(rev):
        out.append("- [%s](../%s): %s" % (x, x, ", ".join("`%s`" % f for f in rev[x])))
    out.append("")
    open(os.path.join(REPO, "docs", "CODE_MAP.md"), "w").write("\n".join(out))
    print("wrote docs/CODE_MAP.md (%d files)" % len(files))


if __name__ == "__main__":
    main()
