#!/usr/bin/env bash
# make_thumbs.sh -- small thumbnails of every design's layout render for the results-page gallery.
#   bash scripts/docs/make_thumbs.sh          # writes docs/img/thumbs/<design>.jpg (320 px on the long side, JPEG quality 70: dense layouts compress badly as PNG)
# Source: designs/<d>/output/layout.png (written by `make collect`). The gallery in docs/RESULTS.md is generated by
# scripts/docs/results_page.py (make table) and uses these thumbnails when present, so GitHub loads ~25 small images
# instead of ~29 MB of full renders. Thumbnails live under docs/ on purpose: a new file in designs/<d>/ would make that
# design's run stale (scripts/flow/find_reusable_run.py watches the design directory).
# Docs: docs/RESULTS.md. Tools: sips (macOS, built in) or ImageMagick `convert` (Linux).
set -euo pipefail
cd "$(dirname "$0")/../.."
out=docs/img/thumbs
mkdir -p "$out"
n=0
for png in designs/*/output/layout.png; do
  d=$(basename "$(dirname "$(dirname "$png")")")
  if command -v sips >/dev/null 2>&1; then
    sips -Z 320 -s format jpeg -s formatOptions 70 "$png" --out "$out/$d.jpg" >/dev/null
  elif command -v convert >/dev/null 2>&1; then
    convert "$png" -resize 320x320 -quality 70 "$out/$d.jpg"
  else
    echo "need sips (macOS) or ImageMagick convert (Linux)"; exit 1
  fi
  n=$((n + 1))
done
echo "make_thumbs: $n thumbnails in $out ($(du -sh "$out" | cut -f1))"
