#!/usr/bin/env bash
# run_tests.sh -- fast repository checks, no Docker (a few seconds):
#   structure     required files present, no symlinks, no absolute home paths, no leftovers from the reference repository
#   upstream      RTL and LICENSE byte-identical to chipfoundry/caravel_user_project @ TEMPLATE_COMMIT (tests/upstream.sha256)
#   config        every design's config.json parses, required keys and guard settings present, every dir:: path exists
#   rtl           iverilog -Wall elaborates RTL + testbench of every design with no warnings (-Wno-timescale: the upstream
#                 RTL has no `timescale and must stay byte-identical; it contains no delays, so the default unit does not matter)
#   model         golden.py --check has zero mismatches; scripts/check_generated.sh: regeneration reproduces every generated file
#   wrapper       every designs/user_project_wrapper*/ (module user_project_wrapper, one macro mprj from its MACROS): same structure/config/lint
#                 checks (config: dir:: paths into build/macros are generated by `make views` and need not exist), exactly one
#                 instance `tiny_ai_core mprj`, module header identical to build/template's (when present), RTL testbench with
#                 the macro RTL and the core's vectors (skipped with a NOTE until its tb exists)
#   sim           each tiny AI engine's testbench passes on the RTL with its generated vectors (PASS line, exit 0)
#   adapter       tests/adapter/run.sh: wb_stream_adapter with all stream engines
#   soc           make -C firmware sim (PicoRV32 SoC sim; NOTE if riscv64-elf-gcc is missing); Caravel runs are not included
#   notes         every design with output/metrics.json has NOTES.md with the required headings
#   negative-all  one corrupted expected value per remaining family (kv variants, soc macros, wrappers, prec_*), through the adapter too
#   tools         pytest of tests/tools (agent, KLayout/OpenROAD tools, RAG, MCP) with build/agent/venv; NOTE when the venv is missing
#   docs          tests/check_docs.py: markdown links, make targets in docs, design inventory, README Status numbers vs metrics.json
#                 (self-tested by tests/lib/check_docs_selftest.sh); the test matrix is tests/TEST_MATRIX.md
#   negative      (also: one corrupted expected value each for audio_pitch, audio_onset, image_text_match, prec_int8)
#                 the testbenches and the model FAIL on deliberately broken input (they can catch a bug): the counter with
#                 +2 increments; per tiny engine a corrupted expected value in vectors.hex and a broken RTL copy; a mutated
#                 threshold in a copy of model/tiny_ai. All mutations are made in a temp dir and asserted to have applied.
# Run: bash tests/run_tests.sh   (make test; about 65 s, no Docker). Exit 0 and a final "test: ALL PASSED" line mean PASS;
#      every check prints one PASS/FAIL/NOTE line (NOTE = optional tool missing, skipped).
# Docs: tests/TEST_MATRIX.md, tests/tools/TEST_MATRIX_TOOLS.md, CLAUDE.md
set -uo pipefail
cd "$(dirname "$0")/.."
D=designs/user_proj_example
TINY="vision_all_lit vision_block text_sentiment"
CORE=tiny_ai_core                      # the three engines behind the Wishbone register block
NEWENG="audio_pitch audio_onset image_text_match prec_bin prec_tern prec_int4 prec_int8 prec_fp8 prec_fp16 prec_bf16"
STREAM="$TINY $NEWENG"                 # streaming engines: stream-style testbench with +VEC (the core and wrapper use their own)
SOCM="soc_image_text_match soc_kv_attn_n8"         # adapter-based experiment macros (one build per experiment, docs/SOC_PLAN.md)
KV="kv_attn_n4 kv_attn_n8 kv_attn_n16 kv_attn_n8_int4 kv_attn_n8_ring"   # KV-cache attention: shared/rtl/kv_attn_core.v, tb shared/tb/kv_attn_tb.vh, +VEC=vectors.hex
ALL="user_proj_example $TINY $CORE $NEWENG $SOCM $KV"
# Caravel wrappers: every designs/user_project_wrapper*/ (module user_project_wrapper, exactly one macro mprj from its MACROS)
WRAPS=""; for _w in designs/user_project_wrapper*/; do _w=$(basename $_w); [ -f designs/$_w/config.json ] && WRAPS="$WRAPS $_w"; done
WRAP=user_project_wrapper              # the tiny_ai_core wrapper (kept for messages)
note() { echo "  NOTE  $*"; }
HAVE_WRAP=0; [ -n "$WRAPS" ] && { HAVE_WRAP=1; ALL="$ALL $WRAPS"; }
# vsim <name> <design> <vvp> <vec>: run a compiled testbench from $TMP; exit code in $rc, log in $TMP/<name>.log
vsim() { (cd "$TMP" && vvp -n "$3" +VEC="$4" > "$1.log" 2>&1); rc=$?; }
# RTL file list of a design plus its macros' RTL, duplicates removed (order kept)
rtl_of() { { python3 scripts/flow/design_info.py "$1" files; for m in $(python3 scripts/flow/find_reusable_run.py --macros "$1"); do python3 scripts/flow/design_info.py "$m" files; done; } | awk '!s[$0]++'; }
FAILS=0
pass() { echo "  PASS  $*"; }
fail() { echo "  FAIL  $*"; FAILS=$((FAILS+1)); }
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT

# == structure: Guards against: missing files, symlinks, absolute home paths and reference-repo leftovers in committed files. Docs: CLAUDE.md (Evidence and hygiene), tests/TEST_MATRIX.md
echo "== structure"
for f in Makefile versions.lock README.md provenance/SOURCES.md \
         $D/config.json $D/pin_order.cfg $D/base_user_proj_example.sdc \
         $D/rtl/user_proj_example.v $D/rtl/defines.v $D/rtl/LICENSE $D/rtl/UPSTREAM.txt $D/tb/user_proj_example_tb.v \
         scripts/doctor.sh scripts/flow/{run_capped.sh,find_reusable_run.py,gl_sim.sh,check_signoff.py,collect.sh,summary.py,design_info.py,signoff_allowances.json,tiny_table.py} \
         scripts/check_generated.sh scripts/lib/common.sh scripts/lib/repo.py shared/tb/stream_tb.vh \
         model/tiny_ai/{common.py,train.py,golden.py,gen_rom.py,spec.json,weights.json} \
         model/audio_pitch/{train.py,golden.py,gen_rom.py,spec.json,weights.json} \
         model/audio_onset/{common.py,train.py,golden.py,gen_rom.py,spec.json,weights.json} \
         model/image_text_match/{train.py,golden.py,gen_rom.py,spec.json,weights.json} \
         model/precision_hw/{gen.py,golden.py,report.py,spec.md} scripts/docs/tables.py; do
  [ -f "$f" ] || fail "missing $f"
done
for d in $TINY $NEWENG; do
  for f in designs/$d/config.json designs/$d/rtl/$d.v designs/$d/rtl/${d}_rom.v designs/$d/tb/${d}_tb.v designs/$d/tb/vectors.hex; do
    [ -f "$f" ] || fail "missing $f"
  done
done
if [ $HAVE_WRAP = 1 ]; then
  for _w in $WRAPS; do for f in designs/$_w/config.json designs/$_w/rtl/user_project_wrapper.v; do [ -f "$f" ] || fail "missing $f"; done; done
else note "designs/$WRAP/config.json not there yet: wrapper checks skipped"; fi
[ "$FAILS" = 0 ] && pass "required files present"
links=$(find . -type l -not -path './build/*' -not -path "./$D/runs/*" | head -3)
[ -z "$links" ] && pass "no symlinks" || fail "symlinks: $links"
src=(Makefile scripts tests designs/*/config.json designs/*/rtl/*.v designs/*/tb model shared)   # rtl/UPSTREAM.txt names the reference on purpose
hits=$(grep -rIl -e "$HOME" -e 'ci_user_proj_example' -e 'ci-upe' -e 'osl_cap_' "${src[@]}" 2>/dev/null | grep -v '^tests/run_tests.sh$' || true)
# agent/tool/simulation code: no absolute home paths (local outputs under build/, results/ and caches are skipped)
hits="$hits $(grep -rIl --exclude-dir=build --exclude-dir=results --exclude-dir=__pycache__ --exclude-dir=third_party -e "$HOME" \
  tools examples caravel_sim precheck firmware soc_sim 2>/dev/null || true)"
hits=$(echo $hits)
[ -z "$hits" ] && pass "no absolute home paths or reference-repo names in sources" || fail "found in: $hits"
# shared helpers (scripts/lib/common.sh, scripts/lib/repo.py): DOCKER_HOST default kept when set; the Colima osl socket only if it
# exists; else /var/run/docker.sock on Linux if it exists; else unset (Docker's default). Image = versions.lock LIBRELANE_IMAGE.
mkdir -p "$TMP/h0" "$TMP/h1/.colima/osl"; : > "$TMP/h1/.colima/osl/docker.sock"
dh() { env -i HOME="$1" PATH="$PATH" ${2:+DOCKER_HOST=$2} bash -c '. scripts/lib/common.sh; oac_docker_host; echo "${DOCKER_HOST:-unset} $OAC_LIBRELANE_IMAGE"'; }
dhp() { env -i HOME="$1" PATH="$PATH" ${2:+DOCKER_HOST=$2} python3 -c 'import sys; sys.path.insert(0, "scripts/lib"); import repo; print(repo.docker_env().get("DOCKER_HOST", "unset"), repo.librelane_image())'; }
img=$(sed -n 's/^LIBRELANE_IMAGE=//p' versions.lock); none=unset
[ "$(uname)" != Darwin ] && [ -e /var/run/docker.sock ] && none=unix:///var/run/docker.sock
ok_dh=1
for f in dh dhp; do
  [ "$($f "$TMP/h0")" = "$none $img" ] || ok_dh=0
  [ "$($f "$TMP/h1")" = "unix://$TMP/h1/.colima/osl/docker.sock $img" ] || ok_dh=0
  [ "$($f "$TMP/h1" tcp://x:1)" = "$( [ $f = dh ] && echo tcp://x:1 || echo unset) $img" ] || ok_dh=0
done
[ "$(python3 scripts/flow/design_info.py --list | sort)" = "$(ls -d designs/*/config.json | cut -d/ -f2 | sort)" ] || ok_dh=0
[ $ok_dh = 1 ] && pass "scripts/lib common.sh/repo.py: DOCKER_HOST default, image pin, design list" || fail "scripts/lib common.sh/repo.py helpers"

# == upstream: Guards against: edits to the upstream template RTL/LICENSE (must stay byte-identical). Docs: CLAUDE.md (Evidence and hygiene), tests/TEST_MATRIX.md
echo "== upstream"
if shasum -a 256 -c tests/upstream.sha256 >"$TMP/sha.txt" 2>&1; then pass "RTL and LICENSE match tests/upstream.sha256"
else fail "upstream files changed:"; grep -v ': OK$' "$TMP/sha.txt"; fi

# == config: Guards against: a config.json losing a required key or a guard setting (CLOCK_PERIOD, ERROR_ON_SYNTH_CHECKS ...) or pointing at a missing file. Docs: CLAUDE.md (HARD RULES), tests/TEST_MATRIX.md
echo "== config"
for d in $ALL; do
if python3 - "designs/$d/config.json" "$d" <<'PY'
import json, os, sys
p = sys.argv[1]; name = sys.argv[2]; c = json.load(open(p)); base = os.path.dirname(p); bad = []
wrap = name.startswith("user_project_wrapper")   # elaborate-only: ERROR_ON_SYNTH_CHECKS false and MAX_TRANSITION_CONSTRAINT come from the template
for k in ("DESIGN_NAME", "VERILOG_FILES", "CLOCK_PERIOD", "CLOCK_PORT", "DIE_AREA", "VDD_NETS", "GND_NETS") + (("IO_PIN_ORDER_CFG",) if name == "user_proj_example" else ()) + (("MACROS", "SYNTH_ELABORATE_ONLY") if wrap else ()):   # tiny engines use automatic pin placement
    if k not in c: bad.append("missing key " + k)
want = "user_project_wrapper" if wrap else name      # Caravel requires the wrapper module name in every wrapper build
if c.get("DESIGN_NAME") != want: bad.append("DESIGN_NAME is not " + want)
if wrap:
    if c.get("SYNTH_ELABORATE_ONLY") is not True: bad.append("SYNTH_ELABORATE_ONLY must be true")
    ms = sorted(c.get("MACROS", {}))
    if len(ms) != 1 or not os.path.isfile(os.path.join("designs", ms[0], "config.json")):
        bad.append("MACROS must hold exactly one macro that is a design in this repository (got %s)" % ms)
else:
    if c.get("ERROR_ON_SYNTH_CHECKS") is not True: bad.append("ERROR_ON_SYNTH_CHECKS must be true")
for k in ("RUN_LINT_CHECK", "DISABLE_LVS") + (() if wrap else ("MAX_TRANSITION_CONSTRAINT",)):
    if k in c: bad.append(k + " must not be set")
if "DELAY" in str(c.get("SYNTH_STRATEGY", "")): bad.append("SYNTH_STRATEGY DELAY is not allowed")
def paths(v):
    if isinstance(v, str) and v.startswith("dir::"): yield v
    elif isinstance(v, list):
        for x in v: yield from paths(x)
for k, v in c.items():
    for d in paths(v):
        tgt = os.path.normpath(os.path.join(base, d[5:]))
        if os.path.relpath(tgt, os.getcwd()).startswith("build" + os.sep + "macros" + os.sep): continue   # generated by make views
        if not os.path.exists(tgt): bad.append("%s: %s does not exist" % (k, d))
for b in bad: print("    " + b)
sys.exit(1 if bad else 0)
PY
then pass "$d/config.json valid"; else fail "$d/config.json"; fi
done

for f in designs/$CORE/config.json designs/$CORE/rtl/$CORE.v designs/$CORE/tb/${CORE}_tb.v designs/$CORE/tb/vectors.hex; do
  [ -f "$f" ] || fail "missing $f"
done

# == rtl: Guards against: RTL or testbench that does not elaborate cleanly under iverilog -Wall (every design). Docs: tests/TEST_MATRIX.md
echo "== rtl"
for d in $ALL; do
  RTL=$(rtl_of $d)
  TBF=designs/$d/tb/${d}_tb.v; TOPF=""
  if [ ! -f "$TBF" ]; then
    case $d in user_project_wrapper*) ;; *) fail "missing $TBF"; continue ;; esac
    note "$d: no testbench yet; linting the RTL alone"; TBF=""; TOPF="-s $d"
  fi
  if iverilog -g2012 -Wall -Wno-timescale -I shared/tb $TOPF -o "$TMP/tb_$d.vvp" $RTL $TBF >"$TMP/iv_$d.log" 2>&1; then
    if grep -qi 'warning' "$TMP/iv_$d.log"; then fail "$d iverilog warnings:"; head -5 "$TMP/iv_$d.log"; else pass "$d iverilog -Wall -Wno-timescale: clean"; fi
  else fail "$d iverilog failed:"; head -10 "$TMP/iv_$d.log"; fi
done

# == wrapper: Guards against: a Caravel wrapper with a changed module header, wrong macro instance count or a failing RTL testbench. Docs: .claude/skills/wrapper-build/SKILL.md, tests/TEST_MATRIX.md
echo "== wrapper"
if [ $HAVE_WRAP = 1 ]; then
 for WRAP in $WRAPS; do
  W=designs/$WRAP/rtl/user_project_wrapper.v
  MAC=$(python3 -c "import json,sys; print(next(iter(json.load(open(sys.argv[1]))['MACROS'])))" designs/$WRAP/config.json)
  if python3 - "$W" "$MAC" <<'PY'
import re, sys
t = re.sub(r"//[^\n]*|/\*.*?\*/", "", open(sys.argv[1]).read(), flags=re.S)
t = re.sub(r"^\s*`[^\n]*", "", t, flags=re.M)                    # preprocessor lines
m = re.search(r"\bmodule\s+user_project_wrapper\b(.*?)\bendmodule\b", t, re.S)
if not m: sys.exit("no module user_project_wrapper")
KW = {"module", "input", "output", "inout", "wire", "reg", "assign", "parameter", "localparam", "integer", "genvar", "always",
      "initial", "generate", "if", "else", "for", "function", "task", "defparam", "supply0", "supply1", "tri", "real", "begin", "end"}
inst = []
for st in m.group(1).split(";"):
    g = re.match(r"\s*(\w+)\s*(?:#\s*\(.*?\)\s*)?(\w+)\s*\(", st, re.S)
    if g and g.group(1) not in KW and not st.lstrip().startswith("("):
        inst.append((g.group(1), g.group(2)))
if inst != [(sys.argv[2], "mprj")]:
    sys.exit("expected exactly one instance '%s mprj', found %s" % (sys.argv[2], inst))
if re.search(r"\b(assign|always)\b", m.group(1)): sys.exit("wrapper has glue logic (assign/always)")
PY
  then pass "$WRAP RTL: exactly one instance, $MAC mprj, no glue logic"; else fail "$WRAP RTL instance check"; fi
  TPL=build/template/verilog/rtl/user_project_wrapper.v
  if [ -f $TPL ]; then
    if python3 - "$W" "$TPL" <<'PY'
import re, sys
def hdr(p):
    t = re.sub(r"//[^\n]*|/\*.*?\*/", "", open(p).read(), flags=re.S)
    m = re.search(r"\bmodule\s+user_project_wrapper\b.*?\)\s*;", t, re.S)
    return re.sub(r"\s+", " ", m.group(0)).replace("( ", "(").replace(" )", ")").strip() if m else None
a, b = hdr(sys.argv[1]), hdr(sys.argv[2])
if a is None or a != b: sys.exit("module header differs from the template's:\n  mine: %s\n  tmpl: %s" % (a, b))
PY
    then pass "$WRAP module header identical to build/template's"; else fail "$WRAP module header"; fi
  else note "build/template not present: header comparison skipped"; fi
  WTB=designs/$WRAP/tb/${WRAP}_tb.v
  if [ -f $WTB ]; then
    WV=designs/$WRAP/tb/vectors.hex; [ -f $WV ] || WV=designs/$MAC/tb/vectors.hex
    vsim "sim_$WRAP" "$WRAP" "tb_$WRAP.vvp" "$PWD/$WV"
    if [ $rc -eq 0 ] && grep -q '^PASS' "$TMP/sim_$WRAP.log"; then pass "$WRAP: $(grep -m1 '^PASS' "$TMP/sim_$WRAP.log" | cut -c1-90)"
    else fail "$WRAP testbench (exit $rc): $(tail -2 "$TMP/sim_$WRAP.log" | tr '\n' ' ' | cut -c1-120)"; fi
  else note "$WTB does not exist yet: wrapper RTL simulation skipped"; fi
 done
else note "no designs/user_project_wrapper*: wrapper checks skipped"; fi

# == model: Guards against: golden models disagreeing with their checks, and generated ROM/vectors/weights drifting from the model. Docs: CLAUDE.md (Generated files), tests/TEST_MATRIX.md
echo "== model"
if python3 model/tiny_ai/golden.py --check >"$TMP/golden.log" 2>&1; then
  if grep -qv ' 0 mismatches' "$TMP/golden.log"; then fail "golden.py --check reported mismatches:"; cat "$TMP/golden.log"
  else pass "golden.py --check: zero mismatches ($(grep -c mismatches "$TMP/golden.log") designs)"; fi
else fail "golden.py --check:"; cat "$TMP/golden.log"; fi
for m in image_text_match precision_hw kv_attention; do
  if python3 model/$m/golden.py --check >"$TMP/golden_$m.log" 2>&1; then
    if grep -q 'mismatches' "$TMP/golden_$m.log" && grep 'mismatches' "$TMP/golden_$m.log" | grep -qv ' 0 mismatches'; then fail "$m golden.py --check reported mismatches:"; cat "$TMP/golden_$m.log"
    else pass "$m golden.py --check: $(tail -1 "$TMP/golden_$m.log" | cut -c1-70)"; fi
  else fail "$m golden.py --check:"; tail -5 "$TMP/golden_$m.log"; fi
done
# audio_pitch and audio_onset have no golden.py --check; their testbenches (== sim) compare the RTL with golden.py's vectors
if scripts/check_generated.sh >"$TMP/gen.log" 2>&1; then pass "regeneration reproduces every generated file"
else fail "check_generated.sh:"; cat "$TMP/gen.log"; fi

# == sim: Guards against: an engine RTL that no longer matches its generated vectors (PASS line expected). Docs: tests/TEST_MATRIX.md
echo "== sim"
for d in $TINY $CORE $NEWENG $SOCM $KV; do
  VEC="$PWD/designs/$d/tb/vectors.hex"
  t0=$(date +%s)
  vsim "sim_$d" "$d" "tb_$d.vvp" "$VEC"
  t1=$(date +%s); [ $((t1-t0)) -ge 10 ] && note "$d simulation took $((t1-t0)) s"
  if [ $rc -eq 0 ] && grep -q '^PASS' "$TMP/sim_$d.log"; then pass "$d: $(grep -m1 '^PASS' "$TMP/sim_$d.log" | cut -c1-90)"
  else fail "$d testbench (exit $rc): $(tail -2 "$TMP/sim_$d.log" | tr '\n' ' ' | cut -c1-120)"; fi
done

# == negative: Guards against: testbenches or the model that cannot fail (each is fed a deliberately broken input and must FAIL). Docs: tests/TEST_MATRIX.md
echo "== negative"
# Vector corruption: tests/lib/mutate_vectors.py (one flipped expected value per design; layouts per vector family).
# tiny_ai_core: flip the expected class (byte 11) of the first case record; the Wishbone testbench must fail
python3 tests/lib/mutate_vectors.py $CORE designs/$CORE/tb/vectors.hex "$TMP/core_bad.hex"
if [ $? -ne 0 ] || cmp -s "$TMP/core_bad.hex" designs/$CORE/tb/vectors.hex; then fail "$CORE: vector corruption did not apply"
else
  vsim "neg_core" "$CORE" "tb_$CORE.vvp" "$TMP/core_bad.hex"
  if [ $rc -ne 0 ] && ! grep -q '^PASS' "$TMP/neg_core.log"; then pass "$CORE: testbench rejects a corrupted expected class ($(grep -m1 FAIL "$TMP/neg_core.log" | cut -c1-70))"
  else fail "$CORE: testbench passed a corrupted vector (exit $rc)"; fi
fi
# break the counter (increment by 2); the testbench must exit non-zero and print no PASS line
sed 's/count <= count + 1'"'"'b1;/count <= count + 2'"'"'d2;/' $D/rtl/user_proj_example.v > "$TMP/broken.v"
if cmp -s "$TMP/broken.v" $D/rtl/user_proj_example.v; then fail "mutation did not apply (RTL changed?)"
else
  iverilog -g2012 -o "$TMP/neg.vvp" $D/rtl/defines.v "$TMP/broken.v" $D/tb/user_proj_example_tb.v >/dev/null 2>&1
  (cd "$TMP" && vvp -n neg.vvp > neg.log 2>&1); rc=$?
  if [ $rc -ne 0 ] && ! grep -q '^PASS' "$TMP/neg.log"; then pass "testbench rejects a broken counter ($(grep -m1 FAIL "$TMP/neg.log" | cut -c1-70))"
  else fail "testbench passed a broken counter (exit $rc)"; fi
fi

# tiny engines: (a) one expected value in vectors.hex corrupted, (b) the RTL broken
for d in $TINY; do
  python3 tests/lib/mutate_vectors.py "$d" "designs/$d/tb/vectors.hex" "$TMP/$d.bad.hex"
  if [ $? -ne 0 ] || cmp -s "$TMP/$d.bad.hex" designs/$d/tb/vectors.hex; then fail "$d: vector mutation did not apply"
  else
    vsim "negv_$d" "$d" "tb_$d.vvp" "$TMP/$d.bad.hex"
    if [ $rc -ne 0 ] && ! grep -q '^PASS' "$TMP/negv_$d.log"; then pass "$d: testbench rejects a corrupted expected value ($(grep -m1 FAIL "$TMP/negv_$d.log" | cut -c1-60))"
    else fail "$d: testbench passed a corrupted vector (exit $rc)"; fi
  fi
  case $d in
    vision_all_lit) from='(score >= threshold)'; to='(score > threshold)' ;;
    vision_block)   from='pooled <= pooled | fire;'; to='pooled <= fire;' ;;
    text_sentiment) from="acc > 5'sd0"; to="acc >= 5'sd0" ;;
  esac
  python3 - "designs/$d/rtl/$d.v" "$TMP/$d.broken.v" "$from" "$to" <<'PY'
import sys
t = open(sys.argv[1]).read()
if sys.argv[3] not in t: sys.exit(1)
open(sys.argv[2], "w").write(t.replace(sys.argv[3], sys.argv[4]))
PY
  if [ $? -ne 0 ] || cmp -s "$TMP/$d.broken.v" designs/$d/rtl/$d.v; then fail "$d: RTL mutation did not apply"
  else
    iverilog -g2012 -Wno-timescale -I shared/tb -o "$TMP/negr_$d.vvp" designs/$d/rtl/${d}_rom.v "$TMP/$d.broken.v" designs/$d/tb/${d}_tb.v >"$TMP/negr_$d.cl" 2>&1
    vsim "negr_$d" "$d" "negr_$d.vvp" "$PWD/designs/$d/tb/vectors.hex"
    if [ $rc -ne 0 ] && ! grep -q '^PASS' "$TMP/negr_$d.log"; then pass "$d: testbench rejects broken RTL ($(grep -m1 FAIL "$TMP/negr_$d.log" | cut -c1-60))"
    else fail "$d: testbench passed broken RTL (exit $rc)"; fi
  fi
done

# new engines: one corrupted expected value in vectors.hex each (audio_pitch, audio_onset: 32-bit words; the others 16-byte records)
for d in audio_pitch audio_onset image_text_match prec_int8; do
  python3 tests/lib/mutate_vectors.py "$d" "designs/$d/tb/vectors.hex" "$TMP/$d.bad.hex"
  if [ $? -ne 0 ] || cmp -s "$TMP/$d.bad.hex" designs/$d/tb/vectors.hex; then fail "$d: vector mutation did not apply"
  else
    vsim "negv_$d" "$d" "tb_$d.vvp" "$TMP/$d.bad.hex"
    if [ $rc -ne 0 ] && ! grep -q '^PASS' "$TMP/negv_$d.log"; then pass "$d: testbench rejects a corrupted expected value ($(grep -m1 FAIL "$TMP/negv_$d.log" | cut -c1-60))"
    else fail "$d: testbench passed a corrupted vector (exit $rc)"; fi
  fi
done

# kv_attn_n8: flip one expected output beat (word 4 of the first CMD record with output beats) in a copy of its vectors
python3 tests/lib/mutate_vectors.py kv_attn_n8 designs/kv_attn_n8/tb/vectors.hex "$TMP/kv_bad.hex"
if [ $? -ne 0 ] || cmp -s "$TMP/kv_bad.hex" designs/kv_attn_n8/tb/vectors.hex; then fail "kv_attn_n8: vector mutation did not apply"
else
  vsim "negv_kv" "kv_attn_n8" "tb_kv_attn_n8.vvp" "$TMP/kv_bad.hex"
  if [ $rc -ne 0 ] && ! grep -q '^PASS' "$TMP/negv_kv.log"; then pass "kv_attn_n8: testbench rejects a corrupted expected output beat ($(grep -m1 FAIL "$TMP/negv_kv.log" | cut -c1-60))"
  else fail "kv_attn_n8: testbench passed a corrupted vector (exit $rc)"; fi
fi

# model: a copy of model/tiny_ai with the vision_all_lit threshold changed must fail golden.py --check
mkdir -p "$TMP/mm/model" && cp -R model/tiny_ai "$TMP/mm/model/"
python3 - "$TMP/mm/model/tiny_ai/weights.json" <<'PY'
import json, sys
w = json.load(open(sys.argv[1])); old = w["vision_all_lit"]["threshold"]
w["vision_all_lit"]["threshold"] = old - 1 if old > 0 else old + 1
json.dump(w, open(sys.argv[1], "w"), indent=2)
PY
if cmp -s "$TMP/mm/model/tiny_ai/weights.json" model/tiny_ai/weights.json; then fail "model: mutation did not apply"
elif (cd "$TMP/mm/model/tiny_ai" && python3 golden.py --check >"$TMP/negm.log" 2>&1); then fail "model: golden.py --check passed a mutated threshold"
else pass "golden.py --check rejects a mutated threshold ($(grep -m1 -v ' 0 mismatches' "$TMP/negm.log" | cut -c1-60))"; fi

# every design family: one expected value in a copy of its vectors.hex flipped (tests/lib/mutate_vectors.py); the self-checking
# testbench (already compiled in == rtl) must exit non-zero with no PASS line. The unmodified vectors pass in == sim / == wrapper.
# Covers what the cases above do not: kv_attn_n4/n16/n8_int4/n8_ring, soc_image_text_match, soc_kv_attn_n8, the three wrappers, 6 prec_*.
# == negative-all: Guards against: the same blind spot as == negative for the remaining families (kv, soc macros, wrappers, prec_*), also through the adapter. Docs: tests/TEST_MATRIX.md
echo "== negative-all"
for d in kv_attn_n4 kv_attn_n16 kv_attn_n8_int4 kv_attn_n8_ring prec_bin prec_tern prec_int4 prec_fp8 prec_fp16 prec_bf16 \
         soc_image_text_match soc_kv_attn_n8 $WRAPS; do
  src=designs/$d/tb/vectors.hex; [ -f $src ] || src=designs/$(python3 -c "import json,sys; print(next(iter(json.load(open(sys.argv[1]))['MACROS'])))" designs/$d/config.json)/tb/vectors.hex
  if [ ! -f "$TMP/tb_$d.vvp" ]; then fail "$d: no compiled testbench for the negative test"; continue; fi
  if ! python3 tests/lib/mutate_vectors.py "$d" "$src" "$TMP/$d.nbad.hex" || cmp -s "$TMP/$d.nbad.hex" "$src"; then fail "$d: vector mutation did not apply"; continue; fi
  vsim "nall_$d" "$d" "tb_$d.vvp" "$TMP/$d.nbad.hex"
  if [ $rc -ne 0 ] && ! grep -q '^PASS' "$TMP/nall_$d.log" && grep -q 'FAIL' "$TMP/nall_$d.log"; then pass "$d: testbench rejects a corrupted expected value ($(grep -m1 FAIL "$TMP/nall_$d.log" | cut -c1-60))"
  else fail "$d: testbench passed a corrupted vector (exit $rc)"; fi
done
# adapter: the same corruption behind the Wishbone adapter (VEC_DIR makes tests/adapter/run.sh read <engine>.hex from a scratch dir)
mkdir -p "$TMP/advec"
for d in vision_block kv_attn_n8 audio_pitch; do python3 tests/lib/mutate_vectors.py $d designs/$d/tb/vectors.hex "$TMP/advec/$d.hex" || fail "adapter $d: mutation did not apply"; done
if VEC_DIR="$TMP/advec" ONLY="vision_block kv_attn_n8 audio_pitch" bash tests/adapter/run.sh >"$TMP/adapter_neg.log" 2>&1; then fail "adapter passed corrupted vectors"
else pass "adapter test rejects corrupted vectors ($(grep -c '^FAIL' "$TMP/adapter_neg.log") of 3 engines FAIL)"; [ "$(grep -c '^FAIL' "$TMP/adapter_neg.log")" = 3 ] || fail "adapter: not every corrupted engine was caught"; fi
# the documentation checks themselves: each must pass a good scratch tree and fail the same tree with one fault
if bash tests/lib/check_docs_selftest.sh >"$TMP/docs_self.log" 2>&1; then pass "tests/check_docs.py self-test: $(grep -c '^ok' "$TMP/docs_self.log") cases (good tree accepted, each fault rejected)"
else fail "check_docs.py self-test:"; grep '^BAD' "$TMP/docs_self.log"; fi

# == docs: Guards against: broken markdown links, unknown make targets in docs, inventory drift, README Status numbers differing from metrics.json (tests/check_docs.py, self-tested by tests/lib/check_docs_selftest.sh). Docs: tests/TEST_MATRIX.md
echo "== docs"
# evidence and documentation consistency (tests/check_docs.py): relative links of every tracked *.md, make targets named in the docs,
# design inventory (files, tables.py ORDER, README, counts, model dirs), numbers in design README Status lines vs output/metrics.json
for c in inventory evidence targets links; do
  if python3 tests/check_docs.py $c >"$TMP/docs_$c.log" 2>&1; then pass "docs $c: $(tail -1 "$TMP/docs_$c.log")"
  else fail "docs $c:"; head -20 "$TMP/docs_$c.log"; fi
done
# traceability: every code file names its parent .md in a "Docs:" line, or is mapped in tests/traceability_map.txt
# (model/ is mapped, not edited: its sources are hashed into generated design inputs). Map: docs/CODE_MAP.md (make code-map)
if python3 tests/check_traceability.py >"$TMP/trace.log" 2>&1; then pass "$(tail -1 "$TMP/trace.log")"
else fail "traceability:"; grep -v '^traceability:' "$TMP/trace.log" | head -20; fi

# == notes: Guards against: a hardened design whose NOTES.md lacks the required headings. Docs: .claude/skills/write-design-notes/SKILL.md, tests/TEST_MATRIX.md
echo "== notes"
# every design with output/metrics.json needs NOTES.md with these headings (## or ###, case-insensitive prefix match)
for d in designs/*/; do
  d=${d%/}; n=$(basename $d)
  [ -f $d/output/metrics.json ] || continue
  if [ ! -f $d/NOTES.md ]; then fail "$n: output/metrics.json exists but NOTES.md is missing"; continue; fi
  if python3 - $d/NOTES.md <<'PY'
import re, sys
heads = [m.group(1).strip().lower() for m in re.finditer(r"^#{2,3}\s+(.+?)\s*$", open(sys.argv[1]).read(), re.M)]
want = [("architecture",), ("data flow",), ("verification",), ("layout",), ("synthesis",), ("floorplan",), ("placement",),
        ("clock tree", "cts"), ("routing",), ("timing",), ("drc",), ("lvs",), ("power", "ir"), ("antenna",), ("run time",),
        ("reproduce",), ("intuitions and insights",)]
miss = ["/".join(w) for w in want if not any(h.startswith(x) for h in heads for x in w)]
if miss: sys.exit("missing headings: " + ", ".join(miss))
PY
  then pass "$n/NOTES.md: all required headings"; else fail "$n/NOTES.md"; fi
done

# == adapter: Guards against: wb_stream_adapter.v failing to carry any stream engine's vectors over Wishbone (tests/adapter/run.sh). Docs: tests/TEST_MATRIX.md, docs/SOC_PLAN.md
echo "== adapter"
# generic Wishbone-to-stream adapter with every stream engine behind it (tests/adapter/run.sh)
t0=$(date +%s)
if bash tests/adapter/run.sh >"$TMP/adapter.log" 2>&1; then pass "wb_stream_adapter with all stream engines: $(grep -c "^PASS" "$TMP/adapter.log") engines ($(( $(date +%s)-t0 )) s)"
else fail "tests/adapter/run.sh:"; tail -5 "$TMP/adapter.log"; fi

# == soc: Guards against: the PicoRV32 SoC + firmware simulation regressing (skipped with a NOTE without riscv64-elf-gcc). Docs: docs/SOC_PLAN.md, tests/TEST_MATRIX.md
echo "== soc"
# PicoRV32 runs RISC-V firmware against user_project_wrapper RTL (make -C firmware sim)
if command -v riscv64-elf-gcc >/dev/null 2>&1; then
  t0=$(date +%s)
  if make -s -C firmware sim >"$TMP/soc.log" 2>&1 && grep -q '^PASS' "$TMP/soc.log"; then pass "firmware SoC sim: $(grep -m1 '^PASS' "$TMP/soc.log" | cut -c1-80) ($(( $(date +%s)-t0 )) s)"
  else fail "make -C firmware sim:"; tail -5 "$TMP/soc.log"; fi
else note "riscv64-elf-gcc not found: firmware SoC sim skipped (brew install riscv-gnu-toolchain)"; fi
if command -v riscv64-elf-gcc >/dev/null 2>&1; then
  t0=$(date +%s)
  if make -s -C firmware/kv sim >"$TMP/soc_kv.log" 2>&1 && grep -q '^PASS' "$TMP/soc_kv.log"; then pass "firmware KV SoC sim (make soc-kv): $(grep -m1 '^PASS' "$TMP/soc_kv.log" | cut -c1-80) ($(( $(date +%s)-t0 )) s)"
  else fail "make -C firmware/kv sim:"; tail -5 "$TMP/soc_kv.log"; fi
else note "riscv64-elf-gcc not found: firmware KV SoC sim skipped"; fi
note "full-Caravel runs (make caravel-rtl, make caravel-gl) are not part of make test: they need build/caravel downloads (about 5 GB)"

# == tools: Guards against: regressions in the agent/EDA tools, RAG and MCP (pytest tests/tools; skipped with a NOTE without the venv). Docs: tests/tools/TEST_MATRIX_TOOLS.md, docs/HERMES_AGENT.md
echo "== tools"
# agent/tools pytest (tests/tools, owned by the tools agent; no Ollama, no Docker; live tests are opt-in and skip by default)
if [ -x build/agent/venv/bin/python ]; then
  t0=$(date +%s)
  if build/agent/venv/bin/python -m pytest -q tests/tools >"$TMP/tools.log" 2>&1; then pass "tests/tools pytest: $(tail -1 "$TMP/tools.log") ($(( $(date +%s)-t0 )) s)"
  else fail "tests/tools pytest:"; tail -15 "$TMP/tools.log"; fi
else note "build/agent/venv missing: tests/tools pytest skipped (docs/HERMES_AGENT.md)"; fi

# == tables: Guards against: stale generated results tables (scripts/docs/tables.py --check). Docs: docs/RESULTS.md, tests/TEST_MATRIX.md
echo "== tables"
if python3 scripts/docs/tables.py --check >"$TMP/tables.log" 2>&1; then pass "docs/RESULTS.md results tables up to date"; else fail "tables.py --check: $(cat "$TMP/tables.log")"; fi

echo
[ "$FAILS" = 0 ] && { echo "test: ALL PASSED"; exit 0; } || { echo "test: $FAILS FAILED"; exit 1; }
