#!/usr/bin/env python3
# Docs: .claude/skills/tune-openroad-engines/SKILL.md, docs/HERMES_DESKTOP.md
"""gen_whatif_keys.py -- write examples/hermes_desktop/tool_server/whatif_keys.json, the list of every configuration variable of
LibreLane 3.0.2 (name, type, library default, unit, description, deprecated aliases, the steps that use it).

    python3 scripts/flow/gen_whatif_keys.py [--out FILE]

Read-only: one `docker run --rm` of the pinned LibreLane image (versions.lock) that imports the library and prints JSON on stdout
(nothing is mounted, nothing is written in the image). Defaults of the PDK and standard-cell-library variables (MAX_TRANSITION_CONSTRAINT,
CLOCK_UNCERTAINTY_CONSTRAINT, ...) have no library default; they are taken from the newest designs/*/runs/*/resolved.json when one exists.
Needs the Docker socket (DOCKER_HOST is set to the Colima socket when it exists, the Makefile rule). Standard library only.
"""
import glob, json, os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "lib"))
import repo  # noqa: E402

IN_IMAGE = r'''
import json
from librelane.flows import Flow
from librelane.config import flow as F
out = {}
def add(v, src):
    d = out.setdefault(v.name, {"sources": []})
    t = str(v.type).replace("typing.", "").replace("<class '", "").replace("'>", "")
    d.update(type=t, default=None if v.default is None else repr(v.default), units=getattr(v, "units", None),
             desc=" ".join((v.description or "").split()),
             aliases=[n if isinstance(n, str) else n[0] for n in (v.deprecated_names or [])])
    d["sources"].append(src)
for s in Flow.factory.get("Classic").Steps:
    for v in s.config_vars:
        add(v, s.id)
for grp in dir(F):
    g = getattr(F, grp)
    if isinstance(g, list) and g and hasattr(g[0], "name"):
        for v in g:
            add(v, "flow:" + grp)
for v in Flow.factory.get("Classic").config_vars:
    add(v, "flow:Classic")
print(json.dumps(out))
'''


def main():
    out = os.path.join(repo.REPO, "examples", "hermes_desktop", "tool_server", "whatif_keys.json")
    if "--out" in sys.argv:
        out = sys.argv[sys.argv.index("--out") + 1]
    env = dict(os.environ)
    env.update(repo.docker_env(os.environ))
    r = subprocess.run(["docker", "run", "--rm", "-i", repo.librelane_image(), "python3", "-"], input=IN_IMAGE, text=True,
                       capture_output=True, env=env)
    if r.returncode:
        sys.exit("docker run failed: " + r.stderr[-400:])
    keys = json.loads(r.stdout.strip().splitlines()[-1])
    # PDK/SCL defaults: the value a run resolved for a variable its design's config.json does not set
    resolved = {}
    for p in sorted(glob.glob(os.path.join(repo.REPO, "designs", "*", "runs", "*", "resolved.json")), key=os.path.getmtime, reverse=True):
        d = p.split(os.sep)[-4]
        try:
            own = set(repo.config(d))
            rj = json.load(open(p))
        except (OSError, ValueError, KeyError):
            continue
        for k, val in rj.items():
            if k not in own and k not in resolved and not str(val).startswith(("/", "{", "[")) and val is not None:
                resolved[k] = val
    for k, v in keys.items():
        v["sources"] = sorted(set(v["sources"]))
        v["resolved_default"] = resolved.get(k) if v["default"] is None else None
    doc = {"_what": "LibreLane 3.0.2 configuration variables, generated by scripts/flow/gen_whatif_keys.py (do not edit by hand)",
           "librelane": "3.0.2", "keys": dict(sorted(keys.items()))}
    with open(out, "w") as f:
        json.dump(doc, f, indent=1, sort_keys=False)
        f.write("\n")
    print("wrote %s: %d variables" % (os.path.relpath(out, repo.REPO), len(keys)))


if __name__ == "__main__":
    main()
