// Generated by model/tiny_ai/gen_rom.py from model/tiny_ai/weights.json; do not edit.
// source sha256 caf0c99cdb2d82c6b71cf5eb46199ad6cd0f3c66dca0d5f0d71a85fa8fb14781
`timescale 1ns/1ps
// One 1-bit weight per pixel (addr = pixel index, raster order; bit i of WEIGHTS) and the neuron threshold.
module vision_all_lit_rom (
    input  wire [1:0] addr,
    output wire       weight,
    output wire [2:0] threshold
);
    localparam [3:0] WEIGHTS = 4'b1111;
    assign weight    = WEIGHTS[addr];
    assign threshold = 3'd4;
endmodule
