#!/usr/bin/env python3
"""gen_rom.py -- generate, from weights.json and golden.py, for each design:
  designs/<d>/rtl/<d>_rom.v      the parameter ROM (weights / kernel / embedding table, threshold)
  designs/<d>/tb/vectors.hex     test vectors for designs/<d>/tb/<d>_tb.v (shared/tb/stream_tb.vh)
Every generated file carries a header with the sha256 of its inputs. Never edit the outputs; change the inputs and
re-run (make generate). `make check-generated` fails if re-running changes a file.

Vector file: $readmemh of 8-bit words in 16-word records. Record 0 is a header: A5, count high, count low.
Each case record: [0] number of beats (1..12), [1..12] s_data of each beat (s_last on the last), [13] expected
beat 0, [14] expected beat 1, [15] expected latency. Cases: every valid input (the truth table), then protocol
cases: every short frame length, two long frames, and an out-of-range item at every position."""
import os
from common import DESIGNS, REPO, WEIGHTS_PATH, sha256_of, spec, truth_table
import golden

HERE = os.path.dirname(os.path.abspath(__file__))
MAX_BEATS = 12


def header(src_hash):
    return ("// Generated by model/tiny_ai/gen_rom.py from model/tiny_ai/weights.json; do not edit.\n"
            "// source sha256 %s\n`timescale 1ns/1ps\n" % src_hash)


def rom_verilog(d, w, h):
    p = w[d]
    # continuous assignments only: an always @(*) block whose input never changes is never evaluated in simulation
    if d == "vision_all_lit":
        bits = "".join(str(v) for v in reversed(p["weights"]))
        return header(h) + """// One 1-bit weight per pixel (addr = pixel index, raster order; bit i of WEIGHTS) and the neuron threshold.
module vision_all_lit_rom (
    input  wire [1:0] addr,
    output wire       weight,
    output wire [2:0] threshold
);
    localparam [3:0] WEIGHTS = 4'b%s;
    assign weight    = WEIGHTS[addr];
    assign threshold = 3'd%d;
endmodule
""" % (bits, p["threshold"])
    if d == "vision_block":
        k = "".join(str(v) for v in reversed(p["kernel"]))
        return header(h) + """// The 2x2 kernel (bit 0 = top-left, 1 = top-right, 2 = bottom-left, 3 = bottom-right) and the neuron threshold.
module vision_block_rom (
    output wire [3:0] kernel,
    output wire [2:0] threshold
);
    assign kernel    = 4'b%s;
    assign threshold = 3'd%d;
endmodule
""" % (k, p["threshold"])
    voc = spec()["designs"][d]["vocabulary"]
    lit = lambda v: ("3'sd%d" % v) if v >= 0 else ("-3'sd%d" % -v)
    params = "\n".join("    localparam signed [2:0] E%d = %s;   // %s" % (i, lit(v), voc[i]) for i, v in enumerate(p["embedding"]))
    return header(h) + """// Signed 3-bit embedding of each vocabulary token. The decision threshold (sum > %d) is in text_sentiment.v.
module text_sentiment_rom (
    input  wire        [1:0] token,
    output wire signed [2:0] embedding
);
%s
    assign embedding = (token == 2'd0) ? E0 :
                       (token == 2'd1) ? E1 :
                       (token == 2'd2) ? E2 : E3;
endmodule
""" % (p["threshold"], params)


def cases(d):
    s = spec()["designs"][d]
    n, vmax = s["inputs"], s["input_max"]
    out = [x for x, _ in truth_table(d)]
    full = [vmax] * n
    out += [full[:k] for k in range(1, n)]                          # short frames
    out += [full + [vmax], full + [0, vmax]]                        # long frames
    for i in range(n):                                              # out-of-range item at each position
        out.append(full[:i] + [vmax + 1] + full[i + 1:])
        out.append(full[:i] + [0xFF] + full[i + 1:])
    assert all(1 <= len(c) <= MAX_BEATS for c in out)
    return out


def vectors(d, w, h):
    cs = cases(d)
    lines = ["// Generated by model/tiny_ai/gen_rom.py from model/tiny_ai/weights.json and golden.py; do not edit.",
             "// source sha256 %s" % h,
             "// %s: %d cases (record layout in model/tiny_ai/gen_rom.py)" % (d, len(cs)),
             " ".join("%02x" % v for v in [0xA5, len(cs) >> 8, len(cs) & 0xFF] + [0] * 13)]
    for c in cs:
        b0, b1, lat = golden.run(d, c, w)
        rec = [len(c)] + c + [0] * (MAX_BEATS - len(c)) + [b0, b1, lat]
        lines.append(" ".join("%02x" % v for v in rec))
    return "\n".join(lines) + "\n", len(cs)


def main():
    w = golden.params()
    h = sha256_of(WEIGHTS_PATH, os.path.join(HERE, "golden.py"), os.path.abspath(__file__), os.path.join(HERE, "common.py"),
                  os.path.join(HERE, "spec.json"))
    for d in DESIGNS:
        rom = os.path.join(REPO, "designs", d, "rtl", "%s_rom.v" % d)
        vec = os.path.join(REPO, "designs", d, "tb", "vectors.hex")
        os.makedirs(os.path.dirname(rom), exist_ok=True)
        os.makedirs(os.path.dirname(vec), exist_ok=True)
        open(rom, "w").write(rom_verilog(d, w, h))
        text, n = vectors(d, w, h)
        open(vec, "w").write(text)
        print("gen_rom: %-15s %s, %s (%d cases)" % (d, os.path.relpath(rom, REPO), os.path.relpath(vec, REPO), n))


if __name__ == "__main__":
    main()
