#!/usr/bin/env python3
"""What-if tools for the Hermes desktop/browser agent: param_info, propose_change, whatif_run, whatif_result, whatif_sweep,
whatif_list, whatif_clean.

Mounted by tool_server.py (_mount_extensions) as `router`; every endpoint is `POST /<tool_name>` (operationId == name).
Purpose: let the agent change synthesis, timing-constraint and OpenROAD-engine settings of a design WITHOUT touching the
design. Nothing here edits designs/<d>/ or applies a patch. A what-if run works on a copy under build/whatif/<d>__<tag>/ (config.json
with the changes applied and every dir:: path rewritten so it still resolves), runs LibreLane there (scripts/flow/whatif_flow.sh,
same container setup as the Makefile) and compares the result with the committed designs/<d>/output/metrics.json.
HARD RULES (CLAUDE.md) are enforced in code by check_key(): CLOCK_PERIOD and MAX_TRANSITION_CONSTRAINT may only be tightened, no DISABLE_LVS /
RUN_LVS off, no SYNTH_STRATEGY DELAY, ERROR_ON_SYNTH_CHECKS stays true, no weaker DRC/LVS/timing/signoff settings, fixed wrapper geometry and pins are
read-only, and keys that are not LibreLane 3.0.2 variables are refused (a typo would otherwise be a silent no-op).
Gate and lock: whatif_run / whatif_sweep use the tool server's own two-step "yes, run <id>" confirmation and its job manager
(one physical flow at a time, shared with run_make), and refuse while a LibreLane container is already running.
Does NOT import tool_server.py (it imports this file); it finds the running server module in sys.modules at call time.
Data: whatif_keys.json (generated by scripts/flow/gen_whatif_keys.py from the pinned LibreLane image), whatif_notes.json (curated).
Docs: docs/HERMES_DESKTOP.md (section "What-if experiments: change constraints safely"), examples/hermes_desktop/tool_server/README.md,
.claude/skills/whatif-experiment/SKILL.md
Tests: tests/tools/test_whatif.py
"""
import ast
import copy
import datetime
import difflib
import glob
import importlib.util
import json
import os
import re
import secrets
import shutil
import subprocess
import sys
import time
from typing import Any, Dict, List, Optional

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
for _p in (os.path.join(REPO, "scripts", "lib"),):
    if _p not in sys.path:
        sys.path.insert(0, _p)

import repo  # noqa: E402
from fastapi import APIRouter  # noqa: E402
from pydantic import BaseModel, Field  # noqa: E402

router = APIRouter()

BASE = os.path.join(REPO, "build", "whatif")
PATCH_DIR = os.path.join(BASE, "patches")
SWEEP_DIR = os.path.join(BASE, "sweeps")
KEYS_JSON = os.path.join(HERE, "whatif_keys.json")
NOTES_JSON = os.path.join(HERE, "whatif_notes.json")
SKILLS = ".claude/skills/tune-synthesis, .claude/skills/tune-timing-sdc, .claude/skills/tune-openroad-engines, .claude/skills/whatif-experiment"
TAG_RE = re.compile(r"^[a-z0-9][a-z0-9_-]{0,30}$")
FLOW_TIMEOUT_S = 600
MAX_SWEEP = 6
CLOCK_FLOOR_NS = 0.0

# Test hooks: tests replace these (no Docker, no server job).
DOCKER_BUSY_HOOK = None      # () -> Optional[str]: name of a running physical-flow container, or None
SERVER_HOOK = None           # () -> module-like object with JOBS / DOCKER_SOCK / confirm helpers


# ---------------------------------------------------------------- data
_CACHE: Dict[str, Any] = {}


def _json(path: str, default=None):
    return repo.load_json(path, default)


def catalog() -> Dict[str, dict]:
    if "keys" not in _CACHE:
        _CACHE["keys"] = (_json(KEYS_JSON, {}) or {}).get("keys", {})
        _CACHE["alias"] = {a: k for k, v in _CACHE["keys"].items() for a in v.get("aliases", [])}
    return _CACHE["keys"]


def aliases() -> Dict[str, str]:
    catalog()
    return _CACHE["alias"]


def notes() -> Dict[str, dict]:
    if "notes" not in _CACHE:
        _CACHE["notes"] = _json(NOTES_JSON, {}) or {}
    return _CACHE["notes"]


def canonical(key: str) -> str:
    return aliases().get(key, key)


# ---------------------------------------------------------------- rules (CLAUDE.md HARD RULES, as code)
# tighten-only constraints: direction "down" = a lower value is tighter, "up" = a higher value is tighter
TIGHTEN_ONLY = {
    "CLOCK_PERIOD": "down", "MAX_TRANSITION_CONSTRAINT": "down", "MAX_FANOUT_CONSTRAINT": "down",
    "MAX_CAPACITANCE_CONSTRAINT": "down", "CLOCK_UNCERTAINTY_CONSTRAINT": "up", "CLOCK_TRANSITION_CONSTRAINT": "up",
    "TIME_DERATING_CONSTRAINT": "up", "IO_DELAY_CONSTRAINT": "up", "OUTPUT_CAP_LOAD": "up",
}
RULE_TEXT = {
    "R1-CLOCK": "CLAUDE.md HARD RULES: never loosen CLOCK_PERIOD (25 ns) to make a gate pass; a lower (tighter) period is allowed for an experiment.",
    "R1-SLEW": "CLAUDE.md HARD RULES: never loosen MAX_TRANSITION_CONSTRAINT to make a gate pass; a lower (tighter) value is allowed.",
    "R1-TIGHTEN": "CLAUDE.md HARD RULES: never weaken timing settings; this constraint may only move in the tightening direction.",
    "R2-LVS": "CLAUDE.md HARD RULES: never DISABLE_LVS and never weaken LVS settings.",
    "R3-DELAY": "CLAUDE.md HARD RULES: never SYNTH_STRATEGY DELAY (only AREA 0..3).",
    "R4-SYNTH-CHECKS": "CLAUDE.md HARD RULES: keep ERROR_ON_SYNTH_CHECKS true (only the elaborate-only Caravel wrappers set it false).",
    "R5-WEAKEN": "CLAUDE.md HARD RULES: never weaken DRC, LVS, timing or precheck settings (a check, a violation corner list or a signoff tool setting).",
    "R6-GEOMETRY": "CLAUDE.md HARD RULES: do not modify fixed wrapper geometry or pin locations (designs/user_project_wrapper*/fixed_dont_change).",
    "R7-ELABORATE": "CLAUDE.md HARD RULES: SYNTH_ELABORATE_ONLY is only for the elaborate-only Caravel wrappers; a macro or engine must be mapped.",
    "R8-DESIGN-FILE": "Not a what-if knob: files, nets, macros and identity keys belong to the design owner (CLAUDE.md: never edit committed designs/<d>/ files from an agent).",
    "R9-UNKNOWN": "Not a LibreLane 3.0.2 variable (checked against whatif_keys.json); an unknown key would be a silent no-op or a flow error.",
    "R10-TYPE": "The value does not match the variable's type in LibreLane 3.0.2.",
    "R11-MARGIN": "CLAUDE.md HARD RULES: never weaken timing; a negative slack margin or allowing setup violations loosens the repair target.",
}
# signoff-relevant flags that may not be switched off when currently on
RUN_OFF_BLOCKED = {"RUN_LVS", "RUN_MAGIC_DRC", "RUN_KLAYOUT_DRC", "RUN_KLAYOUT_XOR", "RUN_MCSTA", "RUN_DRT", "RUN_CTS",
                   "RUN_SPEF_EXTRACTION", "RUN_ANTENNA_REPAIR", "RUN_LINTER", "RUN_IRDROP_REPORT", "RUN_POST_CTS_RESIZER_TIMING",
                   "RUN_POST_GRT_DESIGN_REPAIR", "RUN_POST_GPL_DESIGN_REPAIR", "RUN_MAGIC_STREAMOUT", "RUN_KLAYOUT_STREAMOUT",
                   "RUN_MAGIC_WRITE_LEF", "RUN_FILL_INSERTION", "RUN_TAP_ENDCAP_INSERTION"}
LVS_NAMES = re.compile(r"(^|_)LVS($|_)|^DISABLE_LVS$|NETGEN")
# variables that exist but are not engine or constraint knobs: design identity, files, nets, macros, tool setups
NOT_TUNABLE_PREFIX = ("PAD_", "CELL_", "TECH_", "EXTRA_", "MAGIC", "KLAYOUT", "NETGEN", "LVS_", "EQY", "RCX_", "LINTER", "SLANG",
                      "VERILOG_", "SCL_", "VSRC_", "STA_", "SIGNAL_WIRE", "CLOCK_WIRE", "LAYERS_RC", "VIAS_R", "SET_RC", "DEDUPLICATE")
NOT_TUNABLE = {"PDK", "PDK_ROOT", "DESIGN_DIR", "DESIGN_NAME", "STD_CELL_LIBRARY", "CLOCK_PORT", "CLOCK_NET", "VDD_NETS", "GND_NETS",
               "MACROS", "LIB", "FALLBACK_SDC", "PNR_SDC_FILE", "SIGNOFF_SDC_FILE", "FP_DEF_TEMPLATE", "MACRO_PLACEMENT_CFG",
               "IO_PIN_ORDER_CFG", "MANUAL_GLOBAL_PLACEMENTS", "FP_TRACKS_INFO", "PDN_CFG", "DIODE_CELL", "WELLTAP_CELL", "ENDCAP_CELL",
               "PLACE_SITE", "PNR_EXCLUDED_CELL_FILE", "SYNTH_EXCLUDED_CELL_FILE", "RSZ_DONT_TOUCH_LIST", "RSZ_DONT_TOUCH_RX",
               "YOSYS_LOG_LEVEL", "USE_SLANG", "STA_THREADS", "KLAYOUT_DRC_THREADS", "DRT_ASSIGN_NDR", "NON_DEFAULT_RULES",
               "ROUTING_OBSTRUCTIONS", "PDN_OBSTRUCTIONS", "FP_OBSTRUCTIONS", "PL_SOFT_OBSTRUCTIONS", "SYNTH_EXTRA_MAPPING_FILE",
               "SYNTH_DRIVING_CELL", "SYNTH_CLK_DRIVING_CELL", "SYNTH_BUFFER_CELL", "SYNTH_TIEHI_CELL", "SYNTH_TIELO_CELL",
               "CTS_CLK_BUFFERS", "CTS_ROOT_BUFFER", "SYNTH_CLOCKGATE_NEGEDGE_ICG", "SYNTH_CLOCKGATE_POSEDGE_ICG"}
CORNER_KEYS = re.compile(r"(_CORNERS$|^DEFAULT_CORNER$|^SYNTH_CORNER$)")
GEOMETRY = re.compile(r"^(DIE_AREA|CORE_AREA|FP_|IO_PIN|IO_EXCLUDE|PDN_|MACRO_|MANUAL_GLOBAL|RT_|ERRORS_ON_UNMATCHED_IO|(TOP|BOTTOM|LEFT|RIGHT)_MARGIN_MULT)")


def engine_of(key: str) -> str:
    n = notes().get(key)
    if n:
        return n["engine"]
    k = key
    for pre, eng in (("SYNTH_", "synth"), ("FP_", "floorplan"), ("DIE_AREA", "floorplan"), ("CORE_AREA", "floorplan"),
                     ("IO_", "ioplace"), ("PDN_", "pdn"), ("GPL_", "gpl"), ("DPL_", "dpl"), ("PL_RESIZER", "rsz-cts"),
                     ("PL_", "gpl"), ("DESIGN_REPAIR", "rsz-gpl"), ("GRT_RESIZER", "rsz-grt"), ("GRT_DESIGN_REPAIR", "rsz-grt"),
                     ("GRT_ANT", "ant"), ("GRT_", "grt"), ("RT_", "grt"), ("CTS_", "cts"), ("DRT_ANT", "ant"), ("DRT_", "drt"),
                     ("DIODE", "ant"), ("HEURISTIC", "ant"), ("RSZ_", "rsz-gpl"), ("ERROR_ON", "signoff"), ("RUN_", "flow"),
                     ("CLOCK_", "constraints"), ("MAX_", "constraints"), ("IO_DELAY", "constraints"), ("TIME_DERATING", "constraints"),
                     ("OUTPUT_CAP", "constraints")):
        if k.startswith(pre):
            return eng
    return "other"


def is_wrapper(design: str) -> bool:
    try:
        cfg = repo.config(design)
    except (OSError, ValueError):
        return False
    return design.startswith("user_project_wrapper") or "FP_DEF_TEMPLATE" in cfg or bool(cfg.get("MACROS"))


def _cfg_get(cfg: dict, key: str):
    """(present, value, spelling used in the config) for a canonical key, honouring deprecated spellings."""
    for spelling in [key] + catalog().get(key, {}).get("aliases", []):
        if spelling in cfg:
            return True, cfg[spelling], spelling
    return False, None, key


def effective(design: str, key: str) -> Dict[str, Any]:
    """Current value of a variable for a design: config.json value, else the library default, else the PDK/SCL value that a
    flow resolved (resolved_default). source says which."""
    key = canonical(key)
    cfg = repo.config(design)
    present, v, spelling = _cfg_get(cfg, key)
    if present:
        return {"value": v, "source": "config.json" + ("" if spelling == key else " (as " + spelling + ")"), "spelling": spelling}
    c = catalog().get(key, {})
    if c.get("resolved_default") is not None:
        return {"value": c["resolved_default"], "source": "default (resolved by a flow run; PDK/library value)", "spelling": key}
    d = c.get("default")
    if d is not None:
        try:
            v = ast.literal_eval(d)
        except (ValueError, SyntaxError):
            v = d
        return {"value": v, "source": "default (LibreLane 3.0.2)", "spelling": key}
    return {"value": None, "source": "unset (derived at run time)" if c else "unknown", "spelling": key}


def _is_num(v) -> bool:
    return isinstance(v, (int, float)) and not isinstance(v, bool)


def _literal_options(tp: str) -> Optional[List[str]]:
    m = re.search(r"Literal\[(.*)\]", tp)
    return re.findall(r"'([^']*)'", m.group(1)) if m else None


def coerce(tp: str, v: Any):
    """Accept '20' / 'true' strings from a model; returns (value, error)."""
    inner = re.sub(r"^Optional\[(.*)\]$", r"\1", tp)
    if v is None:
        return (None, None) if tp.startswith("Optional") else (None, "null is not allowed for %s" % tp)
    if inner == "bool":
        if isinstance(v, bool):
            return v, None
        if isinstance(v, str) and v.strip().lower() in ("true", "false"):
            return v.strip().lower() == "true", None
        return v, "expected true or false"
    if inner == "int":
        if isinstance(v, bool):
            return v, "expected an integer"
        if isinstance(v, (int, float)) and float(v) == int(v):
            return int(v), None
        if isinstance(v, str) and re.fullmatch(r"-?\d+", v.strip()):
            return int(v), None
        return v, "expected an integer"
    if inner in ("decimal.Decimal", "float"):
        if _is_num(v):
            return v, None
        if isinstance(v, str) and re.fullmatch(r"-?\d+(\.\d+)?", v.strip()):
            return float(v) if "." in v else int(v), None
        return v, "expected a number"
    if inner.startswith("Literal"):
        opts = _literal_options(inner) or []
        if isinstance(v, str) and v in opts:
            return v, None
        return v, "expected one of: " + ", ".join(opts)
    if inner == "str":
        return (v, None) if isinstance(v, str) else (v, "expected a string")
    if inner.startswith("Tuple") or inner.startswith("List"):
        if isinstance(v, list):
            return v, None
        return v, "expected a list"
    return v, None


def check_key(design: str, key: str, value: Any) -> Dict[str, Any]:
    """One key against the HARD RULES and the variable catalog. Returns {key, canonical, status, rule, reason, current, value, notes[]}."""
    r: Dict[str, Any] = {"key": key, "status": "allowed", "value": value, "notes": []}

    def block(rule: str, why: str):
        r.update(status="blocked", rule=rule, rule_text=RULE_TEXT[rule], reason=why)
        return r

    ck = canonical(key)
    r["canonical"] = ck
    if ck != key:
        r["notes"].append("%s is a deprecated alias of %s in LibreLane 3.0.2" % (key, ck))
    if key == "DISABLE_LVS" or LVS_NAMES.search(ck):
        return block("R2-LVS", "%s touches LVS; LVS may not be disabled, skipped or weakened." % key)
    if ck not in catalog():
        return block("R9-UNKNOWN", "%s is not a LibreLane 3.0.2 variable." % key)
    cur = effective(design, ck) if os.path.isfile(repo.config_path(design)) else {"value": None, "source": "unknown", "spelling": ck}
    r["current"] = cur["value"]
    r["current_source"] = cur["source"]
    tp = catalog()[ck]["type"]
    val, err = coerce(tp, value)
    if err:
        return block("R10-TYPE", "%s = %r: %s (type %s)." % (ck, value, err, tp))
    r["value"] = val
    # identity / file / tool-setup keys
    if ck in NOT_TUNABLE or any(ck.startswith(p) for p in NOT_TUNABLE_PREFIX) or "Path" in tp:
        if CORNER_KEYS.search(ck):
            return block("R5-WEAKEN", "%s selects timing corners; changing the corner set can hide a violation." % ck)
        if ck.startswith(("MAGIC", "KLAYOUT", "RCX_", "STA_", "LINTER")) or ck.startswith("LVS"):
            return block("R5-WEAKEN", "%s is a signoff tool setting (DRC, extraction, STA, lint); it may not be changed from an agent." % ck)
        return block("R8-DESIGN-FILE", "%s is a design-owned identity, file or net setting." % ck)
    if CORNER_KEYS.search(ck):
        return block("R5-WEAKEN", "%s selects timing corners; changing the corner set can hide a violation." % ck)
    # wrapper geometry
    if is_wrapper(design) and GEOMETRY.match(ck):
        return block("R6-GEOMETRY", "%s is part of the fixed Caravel wrapper geometry/pins of %s." % (ck, design))
    if ck == "SYNTH_STRATEGY" and str(val).upper().startswith("DELAY"):
        return block("R3-DELAY", "SYNTH_STRATEGY %r is a DELAY strategy." % val)
    if ck == "ERROR_ON_SYNTH_CHECKS" and val is False:
        return block("R4-SYNTH-CHECKS", "ERROR_ON_SYNTH_CHECKS must stay true.")
    if ck == "SYNTH_ELABORATE_ONLY" and val is True:
        return block("R7-ELABORATE", "SYNTH_ELABORATE_ONLY true would skip logic mapping for %s." % design)
    if ck.startswith("ERROR_ON_") and val is False and ck != "ERROR_ON_LINTER_WARNINGS" and cur["value"] is not False:
        return block("R5-WEAKEN", "%s false turns a signoff check from an error into a warning." % ck)
    if ck in RUN_OFF_BLOCKED and val is False and cur["value"] is not False:
        return block("R5-WEAKEN", "%s false skips a signoff, repair or check step that is on for %s." % (ck, design))
    if ck == "MAGIC_DRC_USE_GDS" and val is False:
        return block("R5-WEAKEN", "MAGIC_DRC_USE_GDS false changes the DRC input.")
    if ck.endswith("_ALLOW_SETUP_VIOS") and val is True:
        return block("R11-MARGIN", "%s true lets hold repair create setup violations." % ck)
    if ck.endswith("_SLACK_MARGIN") and _is_num(val) and val < 0:
        return block("R11-MARGIN", "%s = %s is a negative slack margin: repair would stop with negative slack left." % (ck, val))
    if ck in TIGHTEN_ONLY and _is_num(val):
        cv = cur["value"]
        if ck == "CLOCK_PERIOD":
            cv = cv if _is_num(cv) else 25
            if val <= CLOCK_FLOOR_NS:
                return block("R10-TYPE", "CLOCK_PERIOD must be positive.")
            if val > cv:
                return block("R1-CLOCK", "CLOCK_PERIOD %s ns is longer than the current %s ns (loosening); only a shorter period is allowed." % (val, cv))
            r["notes"].append("tightens the clock from %s ns to %s ns (%.0f MHz); setup slack will shrink" % (cv, val, 1000.0 / val))
        elif ck == "MAX_TRANSITION_CONSTRAINT":
            cv = cv if _is_num(cv) else 0.75
            if val > cv:
                return block("R1-SLEW", "MAX_TRANSITION_CONSTRAINT %s ns is above the current %s ns (loosening); only a lower value is allowed." % (val, cv))
            r["notes"].append("tightens the slew limit from %s ns to %s ns; expect more repair work and more violations to read" % (cv, val))
        elif _is_num(cv):
            down = TIGHTEN_ONLY[ck] == "down"
            if (down and val > cv) or ((not down) and val < cv):
                return block("R1-TIGHTEN", "%s = %s moves away from the tight direction (current %s; allowed: %s)." % (
                    ck, val, cv, "lower" if down else "higher"))
    # warnings (allowed, but said)
    if ck in ("DESIGN_REPAIR_MAX_SLEW_PCT", "GRT_DESIGN_REPAIR_MAX_SLEW_PCT") and _is_num(val) and val > 40:
        r["notes"].append("WARNING: slew margins above 40 percent ran the 8 GB container out of memory in this repo (70 percent on tiny_ai_core; 40 percent on the 80 and 120 um designs); the run is capped by FLOW_TIMEOUT")
    if ck == "DIE_AREA" and isinstance(val, list) and len(val) == 4:
        r["notes"].append("the die sets utilisation; above about 80 percent placement or repair failed in this repo, below 30 percent area is wasted")
    if ck == "PL_TARGET_DENSITY_PCT" and _is_num(val) and (val <= 0 or val > 100):
        return block("R10-TYPE", "PL_TARGET_DENSITY_PCT is a percent between 1 and 100.")
    if ck.startswith("SYNTH_ABC_DFF") and val is True:
        r["notes"].append("flip-flops through ABC can merge registers; check_signoff.py then fails on 'logic lost' unless an allowance with a RTL-verifiable reason exists")
    if is_wrapper(design):
        r["notes"].append("%s is a wrapper/macro-bearing design: propose_change works, whatif_run does not (needs macro views)" % design)
    return r


def rule_of(key: str) -> str:
    """The HARD RULE that applies to a key, in words (for param_info)."""
    ck = canonical(key)
    if ck == "CLOCK_PERIOD":
        return RULE_TEXT["R1-CLOCK"]
    if ck == "MAX_TRANSITION_CONSTRAINT":
        return RULE_TEXT["R1-SLEW"]
    if ck in TIGHTEN_ONLY:
        return RULE_TEXT["R1-TIGHTEN"] + " Direction: %s." % ("lower is tighter" if TIGHTEN_ONLY[ck] == "down" else "higher is tighter")
    if ck == "SYNTH_STRATEGY":
        return RULE_TEXT["R3-DELAY"]
    if ck == "ERROR_ON_SYNTH_CHECKS":
        return RULE_TEXT["R4-SYNTH-CHECKS"]
    if ck == "SYNTH_ELABORATE_ONLY":
        return RULE_TEXT["R7-ELABORATE"]
    if LVS_NAMES.search(ck):
        return RULE_TEXT["R2-LVS"]
    if ck in RUN_OFF_BLOCKED or ck.startswith("ERROR_ON_") or CORNER_KEYS.search(ck):
        return RULE_TEXT["R5-WEAKEN"] + " (setting it to false / changing the corners is blocked)"
    if ck.endswith("_SLACK_MARGIN") or ck.endswith("_ALLOW_SETUP_VIOS"):
        return RULE_TEXT["R11-MARGIN"]
    if ck in NOT_TUNABLE or any(ck.startswith(p) for p in NOT_TUNABLE_PREFIX):
        return RULE_TEXT["R8-DESIGN-FILE"]
    if GEOMETRY.match(ck):
        return "Free on a macro or engine copy; blocked on the Caravel wrappers (" + RULE_TEXT["R6-GEOMETRY"] + ")"
    return "No special rule beyond the global ones (never loosen CLOCK_PERIOD / MAX_TRANSITION_CONSTRAINT, never DISABLE_LVS, no DELAY, keep ERROR_ON_SYNTH_CHECKS true)."


# ---------------------------------------------------------------- design helpers
def _check_design(d: Any) -> Optional[str]:
    if not isinstance(d, str) or d not in repo.design_dirs():
        return "unknown design %r; valid: %s" % (d, " ".join(repo.design_dirs()))
    return None


def _comment_for(design: str, key: str) -> Optional[Dict[str, str]]:
    """The design's own //KEY comment about this variable (the reasoning behind the committed value)."""
    cfg = repo.config(design)
    ck = canonical(key)
    cands = ["//" + ck] + ["//" + a for a in catalog().get(ck, {}).get("aliases", [])]
    if "SLEW" in ck:
        cands.append("//SLEW")
    if ck in ("DIE_AREA", "CORE_AREA") or ck.startswith("FP_"):
        cands.append("//DIE_AREA")
    for c in cands:
        if c in cfg:
            return {"key": c, "text": cfg[c] if isinstance(cfg[c], str) else json.dumps(cfg[c])}
    return None


def _fmt(v) -> str:
    return json.dumps(v) if not isinstance(v, str) else v


class Empty(BaseModel):
    pass


class ParamReq(BaseModel):
    design: str = Field(..., description="design directory name, e.g. vision_block (see list_designs)", examples=["vision_block"])
    key: Optional[str] = Field(None, description="LibreLane variable, e.g. PL_TARGET_DENSITY_PCT or CLOCK_PERIOD; omit to list the tunable keys by engine")
    engine: Optional[str] = Field(None, description="with no key: only this engine group (synth, constraints, floorplan, ioplace, pdn, gpl, dpl, rsz-gpl, rsz-cts, rsz-grt, cts, grt, ant, drt)")


@router.post("/param_info", operation_id="param_info", summary="Explain a synthesis / timing / OpenROAD setting and show its current value", response_model=None)
def param_info(req: ParamReq) -> dict:
    """With `key`: current value (and where it comes from), library default, engine, meaning, safe range, the symptom it fixes, how to verify,
    the HARD RULE that applies, the design's own //KEY comment, and the docs link. Without `key`: the tunable keys grouped by engine with their
    current values (set in config.json or default). Read-only."""
    err = _check_design(req.design)
    if err:
        return {"error": err}
    cat = catalog()
    if not cat:
        return {"error": "whatif_keys.json missing; run python3 scripts/flow/gen_whatif_keys.py"}
    if req.key:
        ck = canonical(req.key)
        if ck not in cat:
            near = [k for k in cat if req.key.upper() in k][:8]
            return {"error": "%s is not a LibreLane 3.0.2 variable" % req.key, "rule": RULE_TEXT["R9-UNKNOWN"], "did_you_mean": near}
        c, n, cur = cat[ck], notes().get(ck, {}), effective(req.design, ck)
        out = {"design": req.design, "key": ck, "alias_of": req.key if ck != req.key else None, "aliases": c.get("aliases", []),
               "engine": engine_of(ck), "type": c["type"], "unit": c.get("units"),
               "current": {"value": cur["value"], "source": cur["source"]},
               "default": c.get("default") if c.get("default") is not None else c.get("resolved_default"),
               "meaning": n.get("meaning") or c["desc"], "librelane_description": c["desc"],
               "safe_range": n.get("safe"), "symptom_it_fixes": n.get("symptom"), "verify_with": n.get("verify"),
               "repo_choice": n.get("repo"), "design_comment": _comment_for(req.design, ck),
               "rule": rule_of(ck), "doc": n.get("doc") or "docs/OPENROAD_ENGINES.md",
               "skills": SKILLS, "used_by_steps": c.get("sources", [])}
        # would a value be allowed? show the current value's check as a self-test of the rule
        return {k: v for k, v in out.items() if v is not None}
    groups: Dict[str, List[dict]] = {}
    for k in sorted(notes()):
        if k not in cat or (req.engine and engine_of(k) != req.engine):
            continue
        cur = effective(req.design, k)
        groups.setdefault(engine_of(k), []).append({"key": k, "value": cur["value"], "set_in_config": cur["source"].startswith("config.json")})
    return {"design": req.design, "engines": groups, "count": sum(len(v) for v in groups.values()),
            "note": "call param_info with a key for meaning, safe range and rule; 'set_in_config' false means the default applies",
            "skills": SKILLS}


# ---------------------------------------------------------------- patch text
def _config_text(design: str) -> str:
    t = open(repo.config_path(design), encoding="utf-8").read()
    return t if t.endswith("\n") else t + "\n"


def apply_changes(cfg: dict, changes: Dict[str, Any]) -> dict:
    """A copy of cfg with the (already validated and coerced) changes; an existing deprecated spelling is changed in place so the
    config never carries both names."""
    out = copy.deepcopy(cfg)
    for k, v in changes.items():
        ck = canonical(k)
        present, _, spelling = _cfg_get(out, ck)
        out[spelling if present else ck] = v
    return out


def make_patch(design: str, changes: Dict[str, Any]) -> str:
    old_text = _config_text(design)
    cfg = json.loads(old_text)
    new_text = json.dumps(apply_changes(cfg, changes), indent=4) + "\n"
    old_norm = json.dumps(cfg, indent=4) + "\n"
    rel = "designs/%s/config.json" % design
    diff = difflib.unified_diff(old_norm.splitlines(True), new_text.splitlines(True), "a/" + rel, "b/" + rel)
    return "".join(diff)


class ChangeReq(BaseModel):
    design: str = Field(..., description="design directory name, e.g. vision_block", examples=["vision_block"])
    changes: Dict[str, Any] = Field(..., description="{LibreLane_KEY: value}, e.g. {\"CLOCK_PERIOD\": 20, \"PL_TARGET_DENSITY_PCT\": 70}",
                                    examples=[{"CLOCK_PERIOD": 20}])


def evaluate(design: str, changes: Dict[str, Any]) -> Dict[str, Any]:
    per = [check_key(design, k, v) for k, v in changes.items()]
    allowed = {canonical(p["key"]): p["value"] for p in per if p["status"] == "allowed"}
    return {"per_key": per, "allowed": allowed, "blocked": [p for p in per if p["status"] == "blocked"]}


@router.post("/propose_change", operation_id="propose_change", summary="Check proposed setting changes against the HARD RULES and make a patch text", response_model=None)
def propose_change(req: ChangeReq) -> dict:
    """Validate {KEY: value} changes for a design: each key is `allowed` or `blocked` with the rule and reason (CLOCK_PERIOD and
    MAX_TRANSITION_CONSTRAINT may only be tightened; no DISABLE_LVS; no SYNTH_STRATEGY DELAY; ERROR_ON_SYNTH_CHECKS stays true; no weaker
    DRC/LVS/timing/precheck settings; wrapper geometry is fixed; unknown keys refused). Returns a unified diff of config.json as PATCH
    TEXT (saved under build/whatif/patches/). NEVER applies it: the owner applies a patch by hand if wanted."""
    err = _check_design(req.design)
    if err:
        return {"error": err}
    if not req.changes:
        return {"error": "changes is empty"}
    ev = evaluate(req.design, req.changes)
    patch, saved = "", None
    if ev["allowed"]:
        patch = make_patch(req.design, ev["allowed"])
        os.makedirs(PATCH_DIR, exist_ok=True)
        name = "%s_%s_%s.patch" % (req.design, time.strftime("%Y%m%d_%H%M%S"), secrets.token_hex(2))
        saved = os.path.join(PATCH_DIR, name)
        with open(saved, "w", encoding="utf-8") as f:
            f.write(patch)
    return {"design": req.design, "verdict": "all allowed" if not ev["blocked"] else ("all blocked" if not ev["allowed"] else "partly blocked"),
            "keys": [{k: v for k, v in p.items() if k in ("key", "canonical", "status", "value", "current", "rule", "rule_text", "reason", "notes")}
                     for p in ev["per_key"]],
            "patch_text": patch, "patch_file": os.path.relpath(saved, REPO) if saved else None, "applied": False,
            "note": "Nothing was applied and designs/%s/ is untouched. The patch covers the allowed keys only. To see the effect, call whatif_run "
                    "(runs on a copy under build/whatif/). Editing config.json makes the committed run stale (find_reusable_run.py), so only the "
                    "owner applies a patch." % req.design}


# ---------------------------------------------------------------- the copy
def _dirs_rewrite(cfg_val, src_cfg_dir: str, dst_dir: str, src_design_dir: str, keep: List[str]):
    """Rewrite dir:: paths for the copy. A target inside the copied part of the design directory stays as it is (the copy holds it);
    every other target gets a path relative to the copy (dir:: only takes relative paths, and `..` means something else after the move)."""
    if isinstance(cfg_val, str) and cfg_val.startswith("dir::"):
        tgt = os.path.normpath(os.path.join(src_cfg_dir, cfg_val[5:]))
        rel_in = os.path.relpath(tgt, src_design_dir)
        if not rel_in.startswith("..") and os.path.exists(os.path.join(dst_dir, rel_in)):
            return cfg_val
        return "dir::" + os.path.relpath(tgt, dst_dir)
    if isinstance(cfg_val, list):
        return [_dirs_rewrite(x, src_cfg_dir, dst_dir, src_design_dir, keep) for x in cfg_val]
    if isinstance(cfg_val, dict):
        return {k: _dirs_rewrite(x, src_cfg_dir, dst_dir, src_design_dir, keep) for k, x in cfg_val.items()}
    return cfg_val


def _walk_dirs(v):
    if isinstance(v, str) and v.startswith("dir::"):
        yield v[5:]
    elif isinstance(v, list):
        for x in v:
            yield from _walk_dirs(x)
    elif isinstance(v, dict):
        for x in v.values():
            yield from _walk_dirs(x)


def whatif_dir(design: str, tag: str) -> str:
    return os.path.join(BASE, "%s__%s" % (design, tag))


def prepare_copy(design: str, tag: str, changes: Dict[str, Any], base: Optional[str] = None) -> Dict[str, Any]:
    """Copy designs/<d>/ (without runs/, output/, tb/, *.md) to build/whatif/<d>__<tag>/, rewrite every dir:: path of config.json so it
    still resolves from there, apply the changes. Never writes below designs/. Returns {dir, missing, config}."""
    base = base or BASE
    if not TAG_RE.match(tag):
        raise ValueError("bad tag %r" % tag)
    src = os.path.join(REPO, "designs", design)
    dst = os.path.join(base, "%s__%s" % (design, tag))
    real = os.path.realpath(dst)
    if not real.startswith(os.path.realpath(base) + os.sep):
        raise ValueError("copy path escapes build/whatif")
    shutil.copytree(src, dst, ignore=shutil.ignore_patterns("runs", "output", "tb", "*.md", "__pycache__", ".DS_Store"))
    cfg = json.load(open(os.path.join(src, "config.json")))
    cfg = {k: _dirs_rewrite(v, src, dst, src, []) for k, v in cfg.items()}
    cfg = apply_changes(cfg, changes)
    with open(os.path.join(dst, "config.json"), "w", encoding="utf-8") as f:
        json.dump(cfg, f, indent=4)
        f.write("\n")
    missing = [p for p in _walk_dirs(cfg) if not os.path.exists(os.path.normpath(os.path.join(dst, p)))]
    return {"dir": dst, "missing": missing, "config": cfg}


# ---------------------------------------------------------------- server plumbing (gate, lock, jobs)
def _server():
    if SERVER_HOOK:
        return SERVER_HOOK()
    for name in ("tool_server", "__main__"):
        m = sys.modules.get(name)
        if m is not None and hasattr(m, "JOBS") and hasattr(m, "_issue_confirm"):
            return m
    return None


def _docker_env() -> Dict[str, str]:
    return repo.docker_env(dict(os.environ))


def docker_busy() -> Optional[str]:
    """Name of a running LibreLane/flow container (another session may be running a flow), else None. Docker unreachable: None."""
    if DOCKER_BUSY_HOOK:
        return DOCKER_BUSY_HOOK()
    try:
        env = dict(os.environ)
        env.update(_docker_env())
        r = subprocess.run(["docker", "ps", "--format", "{{.Names}}|{{.Command}}"], capture_output=True, text=True, timeout=15, env=env)
    except (OSError, subprocess.SubprocessError):
        return None
    for line in r.stdout.splitlines():
        name, _, command = line.partition("|")
        # a flow runs `python3 -m librelane ...`; GUI containers (magic, openroad viewers) of the same image are not flows
        if name.startswith(("oac_cap_", "oac_whatif_")) or "-m librelane" in command or "librelane " in command:
            return name
    return None


def _committed(design: str) -> Dict[str, Any]:
    m = _json("designs/%s/output/metrics.json" % design, {}) or {}
    res = _json("designs/%s/output/resources.json" % design, {}) or {}
    return {"metrics": m, "wall_s": res.get("wall_s_total"), "mem_gb": res.get("container_peak_mem_gb")}


def _analysis():
    if "analysis" not in _CACHE:
        spec = importlib.util.spec_from_file_location("chip_whatif_analysis", os.path.join(HERE, "analysis_tools.py"))
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        _CACHE["analysis"] = mod
    return _CACHE["analysis"]


def _supported(design: str) -> Optional[str]:
    cfg = repo.config(design)
    if cfg.get("MACROS") or design.startswith("user_project_wrapper"):
        return ("%s is a Caravel wrapper (MACROS / fixed geometry); a what-if run needs the exported macro views and the fixed wrapper files. "
                "Try the macro itself (for example tiny_ai_core) instead." % design)
    if not os.path.isfile(os.path.join(REPO, "designs", design, "output", "metrics.json")):
        return "designs/%s/output/metrics.json is missing: no committed result to compare with" % design
    return None


def _expected_minutes(design: str) -> str:
    w = _committed(design)["wall_s"]
    return "about %.0f s of flow (committed resources.json wall_s_total) plus a signoff check; capped at %d s" % (w, FLOW_TIMEOUT_S) if w else \
        "unknown (no resources.json); capped at %d s" % FLOW_TIMEOUT_S


class RunReq(BaseModel):
    design: Optional[str] = Field(None, description="design directory name, e.g. vision_block (required on the first call)", examples=["vision_block"])
    changes: Optional[Dict[str, Any]] = Field(None, description="{LibreLane_KEY: value}; checked against the HARD RULES (see propose_change)",
                                               examples=[{"PL_TARGET_DENSITY_PCT": 70}])
    tag: Optional[str] = Field(None, description="short name of this experiment: lower-case letters, digits, - and _ (max 31); the copy is build/whatif/<design>__<tag>/",
                               examples=["dens70"])
    confirm_id: Optional[str] = Field(None, description="SECOND call only: the confirm_id from the first reply, after the USER wrote 'yes, run <confirm_id>'. Never invent or reuse one.")
    rebuild: Optional[bool] = Field(None, description="true = rebuild the design UNCHANGED on a fresh copy (no changes needed): a full flow "
                                    "that leaves the frozen design and its committed run untouched")


def _gate(kind: str, payload: dict, will_run: str, what: str, confirm_id: Optional[str]):
    """(confirmed_payload, response). With no confirm_id: issues one (unless CHIP_TOOLS_NO_CONFIRM=1)."""
    srv = _server()
    if srv is None:
        return None, {"error": "tool server not available in this process (whatif_run needs its job manager); start tool_server.py"}
    if confirm_id:
        payload, err = srv._take_confirm("whatif", confirm_id.strip())
        if err:
            return None, {"error": err}
        return (payload, confirm_id.strip()), None
    if srv._no_confirm():
        return (payload, None), None
    return None, srv._issue_confirm("whatif", payload, will_run, what)


def _start_job(cmd: List[str], label: str, confirmed: Optional[str]):
    srv = _server()
    env = {"DOCKER_HOST": "unix://" + srv.DOCKER_SOCK, "FLOW_TIMEOUT": str(FLOW_TIMEOUT_S)}
    job, err = srv.JOBS.start("make", cmd, label, physical=True, env=env)
    if err:
        return None, err
    if confirmed:
        srv._consume_confirm(confirmed)
    return job, None


def _write_meta(d: str, meta: dict):
    with open(os.path.join(d, "whatif_meta.json"), "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=1)


@router.post("/whatif_run", operation_id="whatif_run", summary="Run the flow on a COPY of a design with changed settings (needs user confirmation)", response_model=None)
def whatif_run(req: RunReq) -> dict:
    """Run LibreLane on a copy of designs/<design>/ with `changes` applied (build/whatif/<design>__<tag>/), never on the design itself.
    TWO STEPS: the first call starts NOTHING and returns {needs_confirmation, confirm_id, will_run, plan}: show `say` and the plan to the user and STOP;
    call again with the confirm_id only after the user replies 'yes, run <confirm_id>'. Then it returns {job_id}; poll job_status and call
    whatif_result. Same container setup as make gds, one physical flow at a time (shared lock with run_make), capped at 600 s."""
    confirmed = None
    if req.confirm_id:
        got, resp = _gate("whatif", {}, "", "", req.confirm_id)
        if resp:
            return resp
        payload, confirmed = got
        design, changes, tag = payload["design"], payload["changes"], payload["tag"]
        rebuild = bool(payload.get("rebuild"))
    else:
        design, changes, tag = req.design, req.changes, req.tag
        rebuild = bool(req.rebuild)
        if rebuild:
            changes = changes or {}
            tag = tag or "rebuild-" + datetime.datetime.now().strftime("%m%d-%H%M%S")
    err = _check_design(design)
    if err:
        return {"error": err}
    if not changes and not rebuild:
        return {"error": "changes is required, e.g. {\"CLOCK_PERIOD\": 20}"}
    if not tag or not TAG_RE.match(tag):
        return {"error": "tag is required: 1..31 characters of lower-case letters, digits, - and _ (got %r)" % (tag,)}
    err = _supported(design)
    if err:
        return {"error": err}
    ev = evaluate(design, changes)
    if ev["blocked"]:
        return {"error": "blocked by the HARD RULES; nothing was started", "blocked": [
            {"key": b["key"], "rule": b["rule"], "reason": b["reason"]} for b in ev["blocked"]], "allowed_keys": sorted(ev["allowed"])}
    if os.path.exists(whatif_dir(design, tag)):
        return {"error": "build/whatif/%s__%s already exists; pick another tag or whatif_clean it first" % (design, tag)}
    busy = docker_busy()
    if busy:
        return {"error": "a flow container is already running (%s); only one physical flow at a time (CLAUDE.md). Wait for it." % busy}
    rel = os.path.relpath(whatif_dir(design, tag), REPO)
    cmd = ["bash", "scripts/flow/whatif_flow.sh", "--dir", rel, "--design", design, "--tag", tag]
    plan = {"design": design, "tag": tag, "changes": ev["allowed"], "copy": rel, "command": " ".join(cmd),
            "designs_untouched": "designs/%s/ is not modified; its committed run stays current" % design,
            "expected": _expected_minutes(design), "steps": [
                "copy designs/%s/ (without runs/, output/, tb/, *.md) to %s" % (design, rel),
                "rewrite every dir:: path of the copy's config.json so it still resolves, apply the changes",
                "run LibreLane in Docker on the copy (PROFILE=tight: 2 CPUs, 8 GB), cap %d s" % FLOW_TIMEOUT_S,
                "check_signoff.py on the new metrics.json (RTL is unchanged, so no new simulation is needed)",
                "whatif_result compares with designs/%s/output/metrics.json" % design]}
    payload = {"design": design, "changes": ev["allowed"], "tag": tag, **({"rebuild": True} if rebuild else {})}
    if not confirmed and not (_server() and _server()._no_confirm()):
        _, resp = _gate("whatif", payload, " ".join(cmd), "what-if flow on a copy of %s with %s (physical flow, about a minute to ten)" % (
            design, json.dumps(ev["allowed"])), None)
        if resp:
            resp["plan"] = plan
            return resp
    prep = prepare_copy(design, tag, ev["allowed"])
    if prep["missing"]:
        shutil.rmtree(prep["dir"], ignore_errors=True)
        return {"error": "a dir:: path of the copy does not resolve: %s" % prep["missing"]}
    job, err = _start_job(cmd, "whatif %s %s" % (design, tag), confirmed)
    if err:
        shutil.rmtree(prep["dir"], ignore_errors=True)
        return {"error": err}
    _write_meta(prep["dir"], {"design": design, "tag": tag, "changes": ev["allowed"], "job_id": job.id,
                              "created": datetime.datetime.now().isoformat(timespec="seconds")})
    return {"job_id": job.id, "state": job.state, "copy": rel, "changes": ev["allowed"], "log": os.path.relpath(job.log, REPO),
            "next": "poll job_status; when done call whatif_result {tag: %s}" % tag}


# ---------------------------------------------------------------- results
CORNERS = ["nom_tt_025C_1v80", "nom_ss_100C_1v60", "nom_ff_n40C_1v95", "min_tt_025C_1v80", "min_ss_100C_1v60", "min_ff_n40C_1v95",
           "max_tt_025C_1v80", "max_ss_100C_1v60", "max_ff_n40C_1v95"]


def _find_dir(tag: Optional[str], job_id: Optional[str], design: Optional[str]) -> Optional[str]:
    if not os.path.isdir(BASE):
        return None
    for d in sorted(glob.glob(os.path.join(BASE, "*__*"))):
        meta = _json(os.path.join(d, "whatif_meta.json"), {}) or {}
        if tag and meta.get("tag") == tag and (not design or meta.get("design") == design):
            return d
        if job_id and meta.get("job_id") == job_id:
            return d
    return None


def _run_metrics(d: str, tag: str) -> Optional[str]:
    p = os.path.join(d, "runs", tag, "final", "metrics.json")
    return p if os.path.isfile(p) else None


def _num(x):
    return isinstance(x, (int, float)) and not isinstance(x, bool)


def _delta(new, old, nd=3, pct=False):
    if not (_num(new) and _num(old)):
        return "n/a"
    dd = new - old
    if pct and old:
        return "%+.*f (%+.1f%%)" % (nd, dd, 100.0 * dd / abs(old))
    return "%+.*f" % (nd, dd)


def _g(m: dict, key: str):
    v = m.get(key)
    return round(v, 3) if _num(v) else v


def _committed_current(design: str) -> Optional[bool]:
    """True when find_reusable_run.py says the committed run of the design is still current (exit 0)."""
    try:
        r = subprocess.run([sys.executable, os.path.join(REPO, "scripts", "flow", "find_reusable_run.py"), design], capture_output=True, text=True,
                           timeout=120, cwd=REPO)
        return r.returncode == 0
    except (OSError, subprocess.SubprocessError):
        return None


def compare(design: str, new: dict, old: dict, new_res: dict, old_wall, old_mem) -> Dict[str, Any]:
    """Code-built comparison table and verdict (new = the what-if metrics, old = committed). Pure function of two metrics dicts."""
    ana = _analysis()
    kn, ko = ana.key_numbers(new), ana.key_numbers(old)

    rows = []

    def row(name, a, b, delta=""):
        rows.append({"metric": name, "whatif": a, "committed": b, "delta": delta})

    row("std cells", kn["stdcells"], ko["stdcells"], _delta(kn["stdcells"], ko["stdcells"], 0, True))
    row("flip-flops", kn["flip_flops"], ko["flip_flops"], _delta(kn["flip_flops"], ko["flip_flops"], 0))
    row("die (um)", kn["die_um"], ko["die_um"])
    row("utilisation %", kn["utilisation_pct"], ko["utilisation_pct"], _delta(kn["utilisation_pct"], ko["utilisation_pct"], 2))
    sw, so = (kn["setup_worst"] or {}), (ko["setup_worst"] or {})
    hw, ho = (kn["hold_worst"] or {}), (ko["hold_worst"] or {})
    row("setup worst slack ns (%s)" % sw.get("corner", "?"), sw.get("slack_ns"), so.get("slack_ns"), _delta(sw.get("slack_ns"), so.get("slack_ns"), 3))
    row("hold worst slack ns (%s)" % hw.get("corner", "?"), hw.get("slack_ns"), ho.get("slack_ns"), _delta(hw.get("slack_ns"), ho.get("slack_ns"), 3))
    for label, a, b in (("DRC magic", kn["drc"]["magic"], ko["drc"]["magic"]), ("DRC klayout", kn["drc"]["klayout"], ko["drc"]["klayout"]),
                        ("DRC route", kn["drc"]["route"], ko["drc"]["route"]), ("LVS errors", kn["lvs_errors"], ko["lvs_errors"]),
                        ("XOR differences", kn["xor_differences"], ko["xor_differences"]),
                        ("antenna violating nets", kn["antenna"]["violating_nets"], ko["antenna"]["violating_nets"]),
                        ("max slew violations", kn["max_slew_violations"], ko["max_slew_violations"]),
                        ("max cap violations", kn["max_cap_violations"], ko["max_cap_violations"]),
                        ("max fanout violations", kn["max_fanout_violations"], ko["max_fanout_violations"])):
        row(label, a, b, _delta(a, b, 0))
    row("power total mW", kn["power_total_mW"], ko["power_total_mW"], _delta(kn["power_total_mW"], ko["power_total_mW"], 4))
    row("flow wall time s", new_res.get("wall_s_total"), old_wall, _delta(new_res.get("wall_s_total"), old_wall, 0))
    row("container peak memory GB", new_res.get("container_peak_mem_gb"), old_mem, _delta(new_res.get("container_peak_mem_gb"), old_mem, 3))
    corners = []
    for c in CORNERS:
        corners.append({"corner": c, "setup_whatif": _g(new, "timing__setup__ws__corner:" + c), "setup_committed": _g(old, "timing__setup__ws__corner:" + c),
                        "hold_whatif": _g(new, "timing__hold__ws__corner:" + c), "hold_committed": _g(old, "timing__hold__ws__corner:" + c)})
    viol = ana.violations(new)
    parts = []
    if viol:
        parts.append("FAILS signoff: " + "; ".join(viol[:4]))
    else:
        parts.append("CLEAN: no DRC, LVS, XOR, antenna, slew/cap or negative-slack violation in the what-if metrics")
    if _num(kn["stdcells"]) and _num(ko["stdcells"]):
        parts.append("cells %s" % _delta(kn["stdcells"], ko["stdcells"], 0, True))
    if _num(sw.get("slack_ns")) and _num(so.get("slack_ns")):
        parts.append("setup slack %s ns" % _delta(sw.get("slack_ns"), so.get("slack_ns"), 2))
    if _num(hw.get("slack_ns")) and _num(ho.get("slack_ns")):
        parts.append("hold slack %s ns" % _delta(hw.get("slack_ns"), ho.get("slack_ns"), 3))
    return {"table": rows, "corners": corners, "violations": viol, "verdict": "; ".join(parts), "clean": not viol}


def md_table(head: List[str], rows: List[List[Any]]) -> str:
    out = ["| " + " | ".join(head) + " |", "|" + "|".join("---" for _ in head) + "|"]
    out += ["| " + " | ".join("" if c is None else str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def result_of(d: str) -> Dict[str, Any]:
    meta = _json(os.path.join(d, "whatif_meta.json"), {}) or {}
    design, tag = meta.get("design"), meta.get("tag")
    out: Dict[str, Any] = {"design": design, "tag": tag, "changes": meta.get("changes"), "dir": os.path.relpath(d, REPO), "job_id": meta.get("job_id")}
    res = _json(os.path.join(d, "whatif_resources.json"), None)
    mpath = _run_metrics(d, tag) if tag else None
    srv = _server()
    job = srv.JOBS.jobs.get(meta.get("job_id")) if srv and meta.get("job_id") else None
    if res is None and job is not None and job.state == "running":
        out.update(state="running", say="the what-if flow is still running; poll job_status %s and call whatif_result again" % job.id)
        return out
    if res is None:
        out.update(state="no result", say="no whatif_resources.json: the run did not finish (job lost or cancelled); whatif_clean it or run again")
        return out
    out["flow_exit_code"] = res.get("exit_code")
    if res.get("exit_code") != 0 or not mpath:
        log = _tail(os.path.join(d, "runs", tag, "flow.log"), 12) if tag else []
        out.update(state="failed", say="the flow failed (exit %s) after %s s; last log lines below. The committed run is untouched." % (
            res.get("exit_code"), res.get("wall_s_total")), log_tail=log)
        return out
    new = _json(mpath, {}) or {}
    c = _committed(design)
    cmp_ = compare(design, new, c["metrics"], res, c["wall_s"], c["mem_gb"])
    sign = os.path.join(d, "signoff.txt")
    out.update(state="done", **cmp_)
    out["signoff_check"] = _tail(sign, 8) if os.path.isfile(sign) else None
    out["markdown"] = md_table(["metric", "what-if", "committed", "delta"], [[r["metric"], r["whatif"], r["committed"], r["delta"]] for r in cmp_["table"]]) + \
        "\n\n" + md_table(["corner", "setup what-if", "setup committed", "hold what-if", "hold committed"],
                          [[c_["corner"], c_["setup_whatif"], c_["setup_committed"], c_["hold_whatif"], c_["hold_committed"]] for c_ in cmp_["corners"]])
    out["committed_run_still_current"] = _committed_current(design)
    out["designs_touched"] = False
    return out


def _tail(path: str, n: int) -> List[str]:
    try:
        with open(path, errors="replace") as f:
            return [l.rstrip("\n") for l in f.readlines()[-n:]]
    except OSError:
        return []


class ResultReq(BaseModel):
    tag: Optional[str] = Field(None, description="the tag given to whatif_run / listed by whatif_list")
    job_id: Optional[str] = Field(None, description="or the job_id returned by whatif_run")
    design: Optional[str] = Field(None, description="optional, to disambiguate a tag used for several designs")
    sweep_id: Optional[str] = Field(None, description="or the sweep_id returned by whatif_sweep: one table row per value")


@router.post("/whatif_result", operation_id="whatif_result", summary="Compare a what-if run with the committed result", response_model=None)
def whatif_result(req: ResultReq) -> dict:
    """Compare a finished what-if run with designs/<d>/output/metrics.json: cells, flip-flops, die, utilisation, setup/hold worst slack and per
    corner, DRC/LVS/XOR/antenna, slew/cap/fanout violations, power, wall time, peak memory, a verdict built by code and a markdown table.
    Also says whether the committed run is still current (it must be: the what-if never touches designs/). Read-only."""
    if req.sweep_id:
        return sweep_result(req.sweep_id)
    if not (req.tag or req.job_id):
        return {"error": "give tag, job_id or sweep_id (whatif_list shows the tags)"}
    d = _find_dir(req.tag, req.job_id, req.design)
    if not d:
        return {"error": "no what-if copy for tag=%r job_id=%r under build/whatif/ (whatif_list)" % (req.tag, req.job_id)}
    return result_of(d)


# ---------------------------------------------------------------- sweep
class SweepReq(BaseModel):
    design: Optional[str] = Field(None, description="design directory name, e.g. vision_block", examples=["vision_block"])
    key: Optional[str] = Field(None, description="the one variable to sweep, e.g. PL_TARGET_DENSITY_PCT", examples=["PL_TARGET_DENSITY_PCT"])
    values: Optional[List[Any]] = Field(None, description="2 to 6 values; each is checked against the HARD RULES, blocked ones are dropped and listed",
                                        examples=[[50, 60, 70]])
    confirm_id: Optional[str] = Field(None, description="SECOND call only: the confirm_id from the first reply, after the USER wrote 'yes, run <confirm_id>'")


@router.post("/whatif_sweep", operation_id="whatif_sweep", summary="Run what-if flows for several values of one setting, one after the other (needs user confirmation)", response_model=None)
def whatif_sweep(req: SweepReq) -> dict:
    """Sweep one setting over 2..6 values: one what-if copy per value, run sequentially inside ONE job (one physical flow at a time).
    TWO STEPS like whatif_run: the first call returns the plan and a confirm_id; start only after the user says 'yes, run <confirm_id>'.
    Then poll job_status and call whatif_result {sweep_id}."""
    confirmed = None
    if req.confirm_id:
        got, resp = _gate("whatif", {}, "", "", req.confirm_id)
        if resp:
            return resp
        payload, confirmed = got
        design, key, values = payload["design"], payload["key"], payload["values"]
    else:
        design, key, values = req.design, req.key, req.values
    err = _check_design(design)
    if err:
        return {"error": err}
    if not key or not isinstance(values, list) or not (2 <= len(values) <= MAX_SWEEP):
        return {"error": "give key and 2..%d values" % MAX_SWEEP}
    err = _supported(design)
    if err:
        return {"error": err}
    runs, blocked = [], []
    for v in values:
        ev = evaluate(design, {key: v})
        if ev["blocked"]:
            blocked.append({"value": v, "rule": ev["blocked"][0]["rule"], "reason": ev["blocked"][0]["reason"]})
        else:
            runs.append(v)
    if not runs:
        return {"error": "every value is blocked by the HARD RULES; nothing was started", "blocked": blocked}
    busy = docker_busy()
    if busy:
        return {"error": "a flow container is already running (%s); only one physical flow at a time" % busy}
    cmd_preview = "python3 examples/hermes_desktop/tool_server/whatif_tools.py sweep <manifest> (%d runs of scripts/flow/whatif_flow.sh in sequence)" % len(runs)
    payload = {"design": design, "key": key, "values": values}
    plan = {"design": design, "key": canonical(key), "values": runs, "blocked_values": blocked, "runs": len(runs),
            "expected": "%d runs, each %s" % (len(runs), _expected_minutes(design)), "designs_untouched": True}
    if not confirmed and not (_server() and _server()._no_confirm()):
        _, resp = _gate("whatif", payload, cmd_preview, "what-if sweep of %s over %s on %s (%d sequential flows)" % (key, runs, design, len(runs)), None)
        if resp:
            resp["plan"] = plan
            return resp
    sid = "sw" + time.strftime("%m%d%H%M%S")
    manifest = {"sweep_id": sid, "design": design, "key": canonical(key), "runs": []}
    for i, v in enumerate(runs):
        tag = "%s-%d" % (sid, i + 1)
        prep = prepare_copy(design, tag, {canonical(key): coerce(catalog()[canonical(key)]["type"], v)[0]})
        if prep["missing"]:
            return {"error": "a dir:: path of the copy does not resolve: %s" % prep["missing"]}
        _write_meta(prep["dir"], {"design": design, "tag": tag, "changes": {canonical(key): v}, "sweep_id": sid,
                                  "created": datetime.datetime.now().isoformat(timespec="seconds")})
        manifest["runs"].append({"tag": tag, "value": v, "dir": os.path.relpath(prep["dir"], REPO)})
    os.makedirs(SWEEP_DIR, exist_ok=True)
    mpath = os.path.join(SWEEP_DIR, sid + ".json")
    json.dump(manifest, open(mpath, "w"), indent=1)
    cmd = [sys.executable, os.path.join("examples", "hermes_desktop", "tool_server", "whatif_tools.py"), "sweep", os.path.relpath(mpath, REPO)]
    job, err = _start_job(cmd, "whatif sweep %s %s" % (design, key), confirmed)
    if err:
        for r in manifest["runs"]:
            shutil.rmtree(os.path.join(REPO, r["dir"]), ignore_errors=True)
        return {"error": err}
    for r in manifest["runs"]:
        meta_p = os.path.join(REPO, r["dir"], "whatif_meta.json")
        m = _json(meta_p, {})
        m["job_id"] = job.id
        json.dump(m, open(meta_p, "w"), indent=1)
    return {"job_id": job.id, "sweep_id": sid, "state": job.state, "runs": manifest["runs"], "blocked_values": blocked,
            "log": os.path.relpath(job.log, REPO), "next": "poll job_status; then whatif_result {sweep_id: %s}" % sid}


def sweep_result(sid: str) -> Dict[str, Any]:
    if not re.fullmatch(r"sw\d{10}", sid or ""):
        return {"error": "bad sweep_id %r" % sid}
    man = _json(os.path.join(SWEEP_DIR, sid + ".json"), None)
    if not man:
        return {"error": "unknown sweep_id %s" % sid}
    ana = _analysis()
    c = _committed(man["design"])
    ko = ana.key_numbers(c["metrics"])
    rows, details = [], []
    for r in man["runs"]:
        d = os.path.join(REPO, r["dir"])
        res = _json(os.path.join(d, "whatif_resources.json"), None)
        mp = _run_metrics(d, r["tag"])
        if res is None:
            rows.append([r["value"], "not finished", "", "", "", "", "", ""])
            continue
        if res.get("exit_code") != 0 or not mp:
            rows.append([r["value"], "FAILED (exit %s)" % res.get("exit_code"), "", "", "", "", "", res.get("wall_s_total")])
            continue
        kn = ana.key_numbers(_json(mp, {}))
        viol = ana.violations(_json(mp, {}))
        sw, hw = kn["setup_worst"] or {}, kn["hold_worst"] or {}
        rows.append([r["value"], "clean" if not viol else "FAILS: %s" % viol[0], kn["stdcells"], kn["utilisation_pct"], sw.get("slack_ns"), hw.get("slack_ns"),
                     kn["max_slew_violations"], res.get("wall_s_total")])
        details.append(r["tag"])
    so, ho = ko["setup_worst"] or {}, ko["hold_worst"] or {}
    rows.append(["committed", "clean", ko["stdcells"], ko["utilisation_pct"], so.get("slack_ns"), ho.get("slack_ns"), ko["max_slew_violations"], c["wall_s"]])
    head = [man["key"], "result", "std cells", "util %", "setup ws ns", "hold ws ns", "slew viol", "wall s"]
    return {"sweep_id": sid, "design": man["design"], "key": man["key"], "markdown": md_table(head, rows), "rows": rows, "head": head,
            "tags": details, "designs_touched": False}


# ---------------------------------------------------------------- list / clean
@router.post("/whatif_list", operation_id="whatif_list", summary="List what-if copies under build/whatif/", response_model=None)
def whatif_list(req: Empty = Empty()) -> dict:
    """The what-if copies (design, tag, changes, state, size) and saved patches under build/whatif/. Read-only."""
    items = []
    for d in sorted(glob.glob(os.path.join(BASE, "*__*"))):
        if not os.path.isdir(d):
            continue
        meta = _json(os.path.join(d, "whatif_meta.json"), {}) or {}
        res = _json(os.path.join(d, "whatif_resources.json"), None)
        state = "not run" if res is None else ("done" if res.get("exit_code") == 0 else "failed")
        srv = _server()
        job = srv.JOBS.jobs.get(meta.get("job_id")) if srv and meta.get("job_id") else None
        if res is None and job is not None and job.state == "running":
            state = "running"
        items.append({"dir": os.path.relpath(d, REPO), "design": meta.get("design"), "tag": meta.get("tag"), "changes": meta.get("changes"),
                      "state": state, "created": meta.get("created"), "sweep_id": meta.get("sweep_id")})
    patches = sorted(os.path.relpath(p, REPO) for p in glob.glob(os.path.join(PATCH_DIR, "*.patch")))
    return {"runs": items, "patches": patches, "base": os.path.relpath(BASE, REPO)}


class CleanReq(BaseModel):
    tag: Optional[str] = Field(None, description="remove build/whatif/*__<tag>/")
    all: Optional[bool] = Field(None, description="true: remove every finished what-if copy and saved patch (running ones are kept)")


@router.post("/whatif_clean", operation_id="whatif_clean", summary="Delete what-if copies (only under build/whatif/)", response_model=None)
def whatif_clean(req: CleanReq) -> dict:
    """Delete one what-if copy by tag, or all finished ones. Only paths inside build/whatif/ are ever removed; a copy whose job is still
    running is kept. designs/ is never touched."""
    if not req.tag and not req.all:
        return {"error": "give a tag or all=true"}
    removed, kept = [], []
    srv = _server()
    for d in sorted(glob.glob(os.path.join(BASE, "*__*"))):
        meta = _json(os.path.join(d, "whatif_meta.json"), {}) or {}
        if req.tag and meta.get("tag") != req.tag:
            continue
        job = srv.JOBS.jobs.get(meta.get("job_id")) if srv and meta.get("job_id") else None
        if job is not None and job.state == "running":
            kept.append(os.path.relpath(d, REPO))
            continue
        real = os.path.realpath(d)
        if not real.startswith(os.path.realpath(BASE) + os.sep):
            continue
        shutil.rmtree(d, ignore_errors=True)
        removed.append(os.path.relpath(d, REPO))
    if req.all and os.path.isdir(PATCH_DIR):
        for p in glob.glob(os.path.join(PATCH_DIR, "*.patch")):
            os.remove(p)
            removed.append(os.path.relpath(p, REPO))
    return {"removed": removed, "kept_running": kept}


# ---------------------------------------------------------------- sweep driver (the body of a sweep job)
def _sweep_main(manifest_path: str) -> int:
    man = json.load(open(manifest_path))
    rc_all = 0
    for r in man["runs"]:
        print("=== sweep %s: %s = %s (%s) ===" % (man["sweep_id"], man["key"], r["value"], r["tag"]), flush=True)
        rc = subprocess.call(["bash", "scripts/flow/whatif_flow.sh", "--dir", r["dir"], "--design", man["design"], "--tag", r["tag"]], cwd=REPO)
        rc_all = rc_all or rc
    return rc_all


def _cli_prepare(design: str, tag: str, pairs: List[str]) -> int:
    """Terminal use (Claude Code): make the copy build/whatif/<design>__<tag>/ with the rules applied; run it with scripts/flow/whatif_flow.sh."""
    err = _check_design(design) or _supported(design)
    if err or not TAG_RE.match(tag):
        print(err or "bad tag %r" % tag)
        return 2
    changes: Dict[str, Any] = {}
    for p in pairs:
        k, _, v = p.partition("=")
        try:
            changes[k] = json.loads(v)
        except ValueError:
            changes[k] = v
    ev = evaluate(design, changes) if changes else {"allowed": {}, "blocked": []}
    for b in ev["blocked"]:
        print("BLOCKED %s: [%s] %s" % (b["key"], b["rule"], b["reason"]))
    if ev["blocked"]:
        return 3
    if os.path.exists(whatif_dir(design, tag)):
        print("build/whatif/%s__%s exists" % (design, tag))
        return 2
    prep = prepare_copy(design, tag, ev["allowed"])
    _write_meta(prep["dir"], {"design": design, "tag": tag, "changes": ev["allowed"], "created": datetime.datetime.now().isoformat(timespec="seconds")})
    print("copy: %s (missing dir:: targets: %s)" % (os.path.relpath(prep["dir"], REPO), prep["missing"] or "none"))
    print("run:  bash scripts/flow/whatif_flow.sh --dir %s --design %s --tag %s" % (os.path.relpath(prep["dir"], REPO), design, tag))
    return 0


if __name__ == "__main__":
    if len(sys.argv) == 3 and sys.argv[1] == "sweep":
        sys.exit(_sweep_main(os.path.join(REPO, sys.argv[2])))
    if len(sys.argv) >= 4 and sys.argv[1] == "prepare":
        sys.exit(_cli_prepare(sys.argv[2], sys.argv[3], sys.argv[4:]))
    sys.exit("usage: whatif_tools.py sweep <manifest.json>   (used by whatif_sweep jobs)\n"
             "       whatif_tools.py prepare <design> <tag> [KEY=VALUE ...]   (terminal: make a rule-checked copy under build/whatif/)")
