// SPDX-License-Identifier: Apache-2.0
// stream_tb.vh -- body of the self-checking testbench shared by the tiny AI engines. Included inside a module by
// designs/<d>/tb/<d>_tb.v after `define DUT <d>. Runs unchanged on the RTL and on the gate-level netlists.
//
// Vectors: +VEC=<file> (designs/<d>/tb/vectors.hex, generated by model/tiny_ai/gen_rom.py; layout there).
// For every case: send the frame (random gaps in s_valid), take the two result beats (random m_ready stalls), and
// compare beat 0, beat 1, m_last on beat 1 only, and the latency with the golden values. Also checked:
//   - while m_valid is high and m_ready low, m_valid, m_data and m_last hold;
//   - s_ready is low from the last input beat until the result has been taken;
//   - reset in the middle of a frame and while a result is waiting returns to an empty, ready state.
// Comparisons use !== so X never passes. First failure: $fatal(1, "FAIL ..."). Success: "PASS <dut>_tb: ...".
`define STR(x) `"x`"

    reg        clk = 1'b0;
    reg        rst = 1'b1;
    reg        s_valid = 1'b0;
    reg  [7:0] s_data = 8'd0;
    reg        s_last = 1'b0;
    wire       s_ready;
    wire       m_valid;
    wire [7:0] m_data;
    wire       m_last;
    reg        m_ready = 1'b0;

    `DUT dut (.clk(clk), .rst(rst), .s_valid(s_valid), .s_data(s_data), .s_last(s_last), .s_ready(s_ready),
              .m_valid(m_valid), .m_data(m_data), .m_last(m_last), .m_ready(m_ready));

    always #5 clk = ~clk;

    localparam integer MAXREC = 1024;
    reg  [7:0] vec [0:16*MAXREC-1];
    integer    fd, h0, h1, h2;
    reg  [8*256-1:0] line;
    integer    nvec, n_checks, seed, k;
    reg  [1023:0] vfile;

    // cycle counter and first-m_valid capture (sampled at the falling edge, half a cycle after the flops switch)
    integer cyc = 0;
    always @(posedge clk) cyc <= cyc + 1;
    integer t_last, t_mv;
    reg     mv_seen;
    always @(negedge clk) if (m_valid === 1'b1 && !mv_seen) begin mv_seen = 1'b1; t_mv = cyc; end

    // output stability under back-pressure
    reg       held_valid = 1'b0;
    reg [7:0] held_data;
    reg       held_last;
    // sampled 1 ns after the falling edge, once the stimulus for the next rising edge is in place
    always @(negedge clk) #1 begin
        if (held_valid && !rst) begin
            if (m_valid !== 1'b1 || m_data !== held_data || m_last !== held_last)
                $fatal(1, "FAIL output changed while stalled: m_valid=%b m_data=%h m_last=%b, held %h/%b (t=%0t)",
                       m_valid, m_data, m_last, held_data, held_last, $time);
        end
        held_valid = (m_valid === 1'b1) && !m_ready && !rst;
        held_data  = m_data;
        held_last  = m_last;
    end

    initial begin
        #(64'd200000000);
        $fatal(1, "FAIL timeout: testbench did not finish");
    end

    task check8(input [7:0] got, input [7:0] want, input [127:0] what, input integer idx);
        begin
            n_checks = n_checks + 1;
            if (got !== want)
                $fatal(1, "FAIL case %0d %0s: got %h expected %h (t=%0t)", idx, what, got, want, $time);
        end
    endtask

    task do_reset;
        begin
            @(negedge clk); rst = 1'b1; s_valid = 1'b0; s_last = 1'b0; m_ready = 1'b0;
            @(negedge clk); @(negedge clk); rst = 1'b0;
            if (s_ready !== 1'b1 || m_valid !== 1'b0)
                $fatal(1, "FAIL after reset: s_ready=%b m_valid=%b", s_ready, m_valid);
            n_checks = n_checks + 1;
        end
    endtask

    // send the frame of record r; inputs change on the falling edge, the beat is taken at the next rising edge
    task send(input integer r);
        integer b, n;
        begin
            n = vec[16*r]; b = 0; mv_seen = 1'b0;
            while (b < n) begin
                @(negedge clk);
                if (($random(seed) & 3) == 0) begin
                    s_valid = 1'b0; s_last = 1'b0;
                end else begin
                    s_valid = 1'b1; s_data = vec[16*r + 1 + b]; s_last = (b == n - 1);
                    if (s_ready === 1'b1) begin
                        if (b == n - 1) t_last = cyc + 1;
                        b = b + 1;
                    end
                end
            end
            @(negedge clk); s_valid = 1'b0; s_last = 1'b0; s_data = 8'd0;
        end
    endtask

    task receive_and_check(input integer r);
        integer got_n;
        reg [7:0] b0, b1;
        reg       l0, l1;
        begin
            got_n = 0;
            while (got_n < 2) begin
                if (got_n == 0 && m_valid !== 1'b1 && s_ready !== 1'b0)
                    $fatal(1, "FAIL case %0d: s_ready high before the result was taken", r);
                m_ready = (($random(seed) & 3) != 0);
                if (m_valid === 1'b1 && m_ready) begin
                    if (got_n == 0) begin b0 = m_data; l0 = m_last; end
                    else begin b1 = m_data; l1 = m_last; end
                    got_n = got_n + 1;
                end
                @(negedge clk);
            end
            m_ready = 1'b0;
            check8(b0, vec[16*r + 13], "beat 0 {error,class}", r);
            check8(b1, vec[16*r + 14], "beat 1 score", r);
            check8({7'd0, l0}, 8'd0, "m_last on beat 0", r);
            check8({7'd0, l1}, 8'd1, "m_last on beat 1", r);
            check8(t_mv - t_last + 1, vec[16*r + 15], "latency (cycles)", r);
        end
    endtask

    initial begin
        n_checks = 0; seed = 32'h7A1;
        if (!$value$plusargs("VEC=%s", vfile)) $fatal(1, "FAIL no +VEC=<vectors.hex>");
        // header record = first line that is not a comment: A5, case count high, low
        fd = $fopen(vfile, "r");
        if (fd == 0) $fatal(1, "FAIL cannot open %0s", vfile);
        h0 = 0;
        while (h0 == 0 && !$feof(fd)) begin
            if ($fgets(line, fd) && $sscanf(line, "%h %h %h", h0, h1, h2) != 3) h0 = 0;
        end
        $fclose(fd);
        if (h0 !== 32'hA5) $fatal(1, "FAIL %0s: not a vector file (header %h)", vfile, h0);
        nvec = h1 * 256 + h2;
        if (nvec < 1 || nvec >= MAXREC) $fatal(1, "FAIL bad case count %0d", nvec);
        $readmemh(vfile, vec, 0, 16 * (nvec + 1) - 1);
        do_reset;
        for (k = 1; k <= nvec; k = k + 1) begin
            send(k);
            receive_and_check(k);
        end
        // reset in the middle of a frame, then a full case
        @(negedge clk); s_valid = 1'b1; s_data = vec[16*1 + 1]; s_last = 1'b0;
        @(negedge clk); s_valid = 1'b0;
        do_reset;
        send(nvec); receive_and_check(nvec);
        // reset while a result is waiting, then a full case
        send(1);
        while (m_valid !== 1'b1) @(negedge clk);
        do_reset;
        send(2); receive_and_check(2);
        $display("PASS %0s_tb: %0d cases, %0d checks (results, latency, back-pressure, protocol errors, reset)",
                 `STR(`DUT), nvec, n_checks);
        $finish;
    end
