// Generated by model/tiny_ai/gen_rom.py from model/tiny_ai/weights.json; do not edit.
// source sha256 1f192d93b68b040882bccc6255d41137d6a9ed207fc1b3dc36b725a8cfd7446e
`timescale 1ns/1ps
// Signed 3-bit embedding of each vocabulary token. The decision threshold (sum > 0) is in text_sentiment.v.
module text_sentiment_rom (
    input  wire        [1:0] token,
    output wire signed [2:0] embedding
);
    localparam signed [2:0] E0 = 3'sd0;   // PAD
    localparam signed [2:0] E1 = 3'sd1;   // GOOD
    localparam signed [2:0] E2 = 3'sd0;   // FINE
    localparam signed [2:0] E3 = -3'sd1;   // BAD
    assign embedding = (token == 2'd0) ? E0 :
                       (token == 2'd1) ? E1 :
                       (token == 2'd2) ? E2 : E3;
endmodule
