// Generated by model/precision_hw/gen.py from model/precision_hw/golden.py; do not edit.
// source sha256 bd114534c7c5336b459aecd7842971a1fa2183e1751e6a3c639c7effa9cbd748
`timescale 1ns/1ps
// prec_tern parameter ROM (model/precision_hw/spec.md): ternary weights {-1,0,+1} (2-bit two's complement; 2'b10 never stored), integer bias in the same units, 9-bit two's complement. Real value = code * scale, scale = 0.292429812.
// Constants are continuous assignments (no always block): read by the one serial MAC, weight[addr] per input.
module prec_tern_rom (
    input  wire        [3:0]  addr,     // pixel index 0..8, raster order (>= 9 reads 0)
    output wire signed [1:0]  weight,
    output wire signed [8:0]  bias
);
    localparam signed [1:0]  W0 = 2'sh0;   // +0  (fp32 +0.014786)
    localparam signed [1:0]  W1 = 2'sh1;   // +1  (fp32 +0.291126)
    localparam signed [1:0]  W2 = 2'sh0;   // +0  (fp32 +0.028851)
    localparam signed [1:0]  W3 = 2'sh3;   // -1  (fp32 -0.316742)
    localparam signed [1:0]  W4 = 2'sh0;   // +0  (fp32 -0.019083)
    localparam signed [1:0]  W5 = 2'sh3;   // -1  (fp32 -0.267208)
    localparam signed [1:0]  W6 = 2'sh0;   // +0  (fp32 +0.044593)
    localparam signed [1:0]  W7 = 2'sh1;   // +1  (fp32 +0.294643)
    localparam signed [1:0]  W8 = 2'sh0;   // +0  (fp32 +0.000830)
    localparam signed [8:0]  B  = 9'sh1FF;   // -1  (fp32 bias -0.181312)
    assign weight = (addr == 4'd0) ? W0 :
                    (addr == 4'd1) ? W1 :
                    (addr == 4'd2) ? W2 :
                    (addr == 4'd3) ? W3 :
                    (addr == 4'd4) ? W4 :
                    (addr == 4'd5) ? W5 :
                    (addr == 4'd6) ? W6 :
                    (addr == 4'd7) ? W7 :
                    (addr == 4'd8) ? W8 : 2'sh0;
    assign bias = B;
endmodule
