// Generated by model/kv_attention/gen.py from model/kv_attention/golden.py; do not edit.
// source sha256 5aa21bef6d54d808962828a2b90e3652a8b210c9b13176c007b48d412e3681b4
`timescale 1ns/1ps
// Parameter ROM of kv_attn_n8_int4: the token embedding table and the Wq / Wk / Wv matrices and biases (spec.md section 2).
// Continuous assigns only. int8 two's complement everywhere.
//   emb     {e3, e2, e1, e0} of token `token` (4 x int8, e0 in bits [7:0]); the engine adds the position to e3.
//   wq/wk/wv  16 x int8, entry (row r, column c) at bits [8*(4*r+c) +: 8]; out_r = sum_c W[r][c]*x[c] + b[r].
//   bq/bk/bv   4 x int8, b[r] at bits [8*r +: 8].
// Position embedding (not stored): x = emb + (0, 0, 0, pos), pos = 0..31 (saturating).
module kv_attn_n8_int4_rom (
    input  wire  [3:0]  token,
    output wire [31:0]  emb,
    output wire [127:0] wq,
    output wire [127:0] wk,
    output wire [127:0] wv,
    output wire [31:0]  bq,
    output wire [31:0]  bk,
    output wire [31:0]  bv
);
    localparam [16*32-1:0] EMB = {
        {8'h00, 8'h03, 8'h01, 8'h01},  // token 15 = D3: e0= 1 e1= 1 e2= 3 e3=0
        {8'h00, 8'h01, 8'h01, 8'h01},  // token 14 = D2: e0= 1 e1= 1 e2= 1 e3=0
        {8'h00, 8'hFF, 8'h01, 8'h01},  // token 13 = D1: e0= 1 e1= 1 e2=-1 e3=0
        {8'h00, 8'hFD, 8'h01, 8'h01},  // token 12 = D0: e0= 1 e1= 1 e2=-3 e3=0
        {8'h00, 8'h03, 8'hFF, 8'h01},  // token 11 = C3: e0= 1 e1=-1 e2= 3 e3=0
        {8'h00, 8'h01, 8'hFF, 8'h01},  // token 10 = C2: e0= 1 e1=-1 e2= 1 e3=0
        {8'h00, 8'hFF, 8'hFF, 8'h01},  // token  9 = C1: e0= 1 e1=-1 e2=-1 e3=0
        {8'h00, 8'hFD, 8'hFF, 8'h01},  // token  8 = C0: e0= 1 e1=-1 e2=-3 e3=0
        {8'h00, 8'h03, 8'h01, 8'hFF},  // token  7 = B3: e0=-1 e1= 1 e2= 3 e3=0
        {8'h00, 8'h01, 8'h01, 8'hFF},  // token  6 = B2: e0=-1 e1= 1 e2= 1 e3=0
        {8'h00, 8'hFF, 8'h01, 8'hFF},  // token  5 = B1: e0=-1 e1= 1 e2=-1 e3=0
        {8'h00, 8'hFD, 8'h01, 8'hFF},  // token  4 = B0: e0=-1 e1= 1 e2=-3 e3=0
        {8'h00, 8'h03, 8'hFF, 8'hFF},  // token  3 = A3: e0=-1 e1=-1 e2= 3 e3=0
        {8'h00, 8'h01, 8'hFF, 8'hFF},  // token  2 = A2: e0=-1 e1=-1 e2= 1 e3=0
        {8'h00, 8'hFF, 8'hFF, 8'hFF},  // token  1 = A1: e0=-1 e1=-1 e2=-1 e3=0
        {8'h00, 8'hFD, 8'hFF, 8'hFF}   // token  0 = A0: e0=-1 e1=-1 e2=-3 e3=0
    };
    assign emb = EMB[token*32 +: 32];
    assign wq  = {8'h00, 8'h00, 8'h00, 8'h00, 8'h00, 8'h00, 8'h00, 8'h00, 8'h00, 8'h00, 8'h04, 8'h00, 8'h00, 8'h00, 8'h00, 8'h04};
    assign wk  = {8'h01, 8'h00, 8'h00, 8'h00, 8'h00, 8'h00, 8'h00, 8'h00, 8'h00, 8'h00, 8'h04, 8'h00, 8'h00, 8'h00, 8'h00, 8'h04};
    assign wv  = {8'h01, 8'h00, 8'h00, 8'h00, 8'h00, 8'h00, 8'h01, 8'h00, 8'h00, 8'h00, 8'h00, 8'h01, 8'h00, 8'h01, 8'h00, 8'h00};
    assign bq  = {8'h01, 8'h00, 8'h00, 8'h00};
    assign bk  = {8'h00, 8'h00, 8'h00, 8'h00};
    assign bv  = {8'h00, 8'h00, 8'h00, 8'h00};
endmodule
