// Generated by model/audio_onset/gen_rom.py from model/audio_onset/weights.json; do not edit.
// source sha256 155a17910d29012035d6b3a18b394ce48ac6608cc101fb57a0543125e857a8ad
`timescale 1ns/1ps
// Learned weights (signed 3 bit) and threshold (signed 6 bit) of the one neuron. Exact sum range with these
// weights and 4-bit energies: -30..30 (fits the 6-bit signed sum in audio_onset.v).
module audio_onset_rom (
    output wire signed [2:0] w0,
    output wire signed [2:0] w1,
    output wire signed [2:0] w2,
    output wire signed [2:0] w3,
    output wire signed [5:0] threshold
);
    assign w0 = -3'sd1;   // applies to the oldest energy
    assign w1 = -3'sd1;   // applies to the second-oldest energy
    assign w2 = 3'sd1;   // applies to the second-newest energy
    assign w3 = 3'sd1;   // applies to the newest energy
    assign threshold = 6'sd4;   // class = (sum >= threshold)
endmodule
