// SPDX-License-Identifier: Apache-2.0
// Self-checking testbench for tiny_ai_core (designs/tiny_ai_core/rtl/tiny_ai_core.v; register map in its header and SPEC.md).
// Everything is driven and observed through the DUT ports only (Wishbone master task, GPIO / LA / irq monitors), so it runs
// unchanged on the RTL and on the gate-level netlists (scripts/flow/gl_sim.sh).
//
// Vectors: +VEC=<file> (designs/tiny_ai_core/tb/vectors.hex, generated by model/tiny_ai/gen_rom.py core_vectors):
// header record A5 <count hi> <count lo>, then 16-byte records [0] mode [1] n inputs [2..10] inputs [11] class [12] score
// [13] expected CYCLES.
//
// Checks:
//   1. every case: CLEAR, mode, push inputs, START, poll STATUS (BUSY on the first poll), RESULT, CYCLES (== record, <= 16),
//      STATUS, DEBUG, one single-clock irq[0] pulse per run, GPIO and LA mirrors; every third case is run a second time
//      without CLEAR (inputs persist) and must give the same result.
//   2. registers: ID, CAPS, CTRL, DEBUG, byte-select masking of reads, unmapped offsets, addresses outside the window.
//   3. protocol negatives (sticky ERROR, otherwise no effect), byte-select writes, START+CLEAR, DONE / ERROR persistence.
//   4. back-to-back runs without CLEAR.
//   5. reset during a run (every mode, many points in the run) returns to the reset state; full cases pass afterwards.
// Wishbone: ack is exactly one clock wide, never rises without a request. Comparisons use !== so X never passes.
// First failure: $fatal(1, "FAIL ..."). Success: "PASS tiny_ai_core_tb: ...".
`timescale 1ns/1ps

module tiny_ai_core_tb;
    reg          wb_clk_i = 1'b0;
    reg          wb_rst_i = 1'b1;
    reg          wbs_stb_i = 1'b0, wbs_cyc_i = 1'b0, wbs_we_i = 1'b0;
    reg  [3:0]   wbs_sel_i = 4'd0;
    reg  [31:0]  wbs_dat_i = 32'd0, wbs_adr_i = 32'd0;
    wire         wbs_ack_o;
    wire [31:0]  wbs_dat_o;
    reg  [127:0] la_data_in = 128'h0123_4567_89AB_CDEF_FEDC_BA98_7654_3210;
    reg  [127:0] la_oenb    = 128'hFFFF_0000_FFFF_0000_0000_FFFF_0000_FFFF;
    wire [127:0] la_data_out;
    reg  [37:0]  io_in = 38'h2A_5A5A_5A5A;
    wire [37:0]  io_out, io_oeb;
    wire [2:0]   irq;

    tiny_ai_core dut (
        .wb_clk_i(wb_clk_i), .wb_rst_i(wb_rst_i),
        .wbs_stb_i(wbs_stb_i), .wbs_cyc_i(wbs_cyc_i), .wbs_we_i(wbs_we_i), .wbs_sel_i(wbs_sel_i),
        .wbs_dat_i(wbs_dat_i), .wbs_adr_i(wbs_adr_i), .wbs_ack_o(wbs_ack_o), .wbs_dat_o(wbs_dat_o),
        .la_data_in(la_data_in), .la_data_out(la_data_out), .la_oenb(la_oenb),
        .io_in(io_in), .io_out(io_out), .io_oeb(io_oeb), .irq(irq));

    always #5 wb_clk_i = ~wb_clk_i;

    localparam [31:0] BASE     = 32'h3000_0000;
    localparam [31:0] A_ID     = 32'h3000_0000;
    localparam [31:0] A_CTRL   = 32'h3000_0004;
    localparam [31:0] A_STATUS = 32'h3000_0008;
    localparam [31:0] A_INPUT  = 32'h3000_000C;
    localparam [31:0] A_RESULT = 32'h3000_0010;
    localparam [31:0] A_CYCLES = 32'h3000_0014;
    localparam [31:0] A_CAPS   = 32'h3000_0018;
    localparam [31:0] A_DEBUG  = 32'h3000_001C;

    localparam integer MAXREC = 1024;
    reg  [7:0] vec [0:16*MAXREC-1];
    integer    fd, h0, h1, h2;
    reg  [8*256-1:0] line;
    integer    nvec;
    reg  [1023:0] vfile;

    integer n_checks = 0;
    integer n_tx = 0;
    integer cur = 0;               // current case / scenario number, for messages
    integer runs = 0;              // runs expected to have completed (irq pulses)
    integer max_polls = 0;
    reg [1:0] eact = 2'd0;         // expected active mode (STATUS[5:4])
    reg [31:0] rdat;               // data returned by the last wb()
    reg [127:0] snap_la;           // la_data_out / io_out sampled together with rdat
    reg [37:0]  snap_io;

    // ---------------------------------------------------------------- monitors (sampled 2 ns after the falling edge)
    integer reqs = 0, acks = 0;
    integer irq_rises = 0, irq_hi = 0;
    reg     mon_en = 1'b0, prev_ack = 1'b0, prev_irq = 1'b0;
    always @(negedge wb_clk_i) begin
        #2;
        if (mon_en) begin
            if (wbs_ack_o !== 1'b0 && wbs_ack_o !== 1'b1) $fatal(1, "FAIL wbs_ack_o is X (t=%0t)", $time);
            if (wbs_ack_o === 1'b1) begin
                if (prev_ack) $fatal(1, "FAIL wbs_ack_o wider than one clock (t=%0t)", $time);
                acks = acks + 1;
                if (acks > reqs) $fatal(1, "FAIL wbs_ack_o without a request (t=%0t)", $time);
            end
            prev_ack = (wbs_ack_o === 1'b1);
            if (irq !== 3'b000 && irq !== 3'b001) $fatal(1, "FAIL irq=%b (X or irq[2:1] != 0) (t=%0t)", irq, $time);
            if (irq[0] === 1'b1) begin
                irq_hi = irq_hi + 1;
                if (!prev_irq) irq_rises = irq_rises + 1;
            end
            prev_irq = (irq[0] === 1'b1);
        end
    end

    initial begin
        #(64'd100000000);
        $fatal(1, "FAIL timeout: testbench did not finish");
    end

    // ---------------------------------------------------------------- checking helpers
    task chk(input [127:0] got, input [127:0] want, input [8*48-1:0] what);
        begin
            n_checks = n_checks + 1;
            if (got !== want)
                $fatal(1, "FAIL case %0d %0s: got %h expected %h (t=%0t)", cur, what, got, want, $time);
        end
    endtask

    task idle(input integer n);
        begin repeat (n) @(negedge wb_clk_i); end
    endtask

    // Wishbone classic cycle. Called on a falling edge; drives there, waits for ack, samples dat_o while ack is high,
    // drops cyc/stb, waits one more falling edge and checks ack went low. Returns on a falling edge. Read data in rdat.
    task wb(input we, input [3:0] sel, input [31:0] adr, input [31:0] dat);
        integer t;
        begin
            reqs = reqs + 1; n_tx = n_tx + 1;
            wbs_cyc_i = 1'b1; wbs_stb_i = 1'b1; wbs_we_i = we; wbs_sel_i = sel; wbs_adr_i = adr; wbs_dat_i = dat;
            t = 0;
            @(negedge wb_clk_i);
            while (wbs_ack_o !== 1'b1) begin
                if (wbs_ack_o !== 1'b0) $fatal(1, "FAIL case %0d: wbs_ack_o is X during a request", cur);
                t = t + 1;
                if (t > 8) $fatal(1, "FAIL case %0d: no wbs_ack_o within 8 cycles (adr %h)", cur, adr);
                @(negedge wb_clk_i);
            end
            rdat = wbs_dat_o; snap_la = la_data_out; snap_io = io_out;
            wbs_cyc_i = 1'b0; wbs_stb_i = 1'b0; wbs_we_i = 1'b0; wbs_sel_i = 4'd0; wbs_adr_i = 32'd0; wbs_dat_i = 32'd0;
            @(negedge wb_clk_i);
            n_checks = n_checks + 1;
            if (wbs_ack_o !== 1'b0) $fatal(1, "FAIL case %0d: wbs_ack_o not exactly one clock wide (adr %h)", cur, adr);
        end
    endtask

    task rdr(input [31:0] adr);          wb(1'b0, 4'hF, adr, 32'd0);   endtask
    task wr (input [3:0] sel, input [31:0] adr, input [31:0] dat); wb(1'b1, sel, adr, dat); endtask
    task push(input [31:0] v);           wr(4'hF, A_INPUT, v);         endtask
    task do_clear;                       wr(4'b0010, A_CTRL, 32'h0000_0200); endtask
    task set_mode(input [1:0] m);        wr(4'b0001, A_CTRL, {30'd0, m}); endtask
    task go;                             wr(4'b0010, A_CTRL, 32'h0000_0100); endtask

    function [31:0] stat_word(input [3:0] cnt, input [1:0] act, input err, input done, input busy);
        stat_word = {20'd0, cnt, 2'd0, act, 1'b0, err, done, busy};
    endfunction

    // GPIO / LA / irq[2:1] mirrors against the register values just read (called on an idle falling edge)
    task chk_mirrors(input [31:0] st, input [31:0] res, input [31:0] cy);
        begin
            chk(io_out, {16'd0, res[15:8], st[5:4], st[2], st[0], st[1], res[0], 8'd0}, "io_out mirror");
            chk(io_oeb, {16'hFFFF, 14'd0, 8'hFF}, "io_oeb");
            chk(la_data_out, {64'd0, cy[31:0], st[15:0], res[15:0]}, "la_data_out mirror");
            chk(irq[2:1], 2'b00, "irq[2:1]");
        end
    endtask

    task chk_stat(input [3:0] cnt, input [1:0] act, input err, input done, input busy, input [8*48-1:0] what);
        begin
            rdr(A_STATUS);
            chk(rdat, stat_word(cnt, act, err, done, busy), what);
            chk(snap_la[31:16], rdat[15:0], "STATUS vs la_data_out");
            chk(snap_io[13:9], {rdat[5:4], rdat[2], rdat[0], rdat[1]}, "STATUS vs io_out");
        end
    endtask

    task chk_irq;
        begin
            chk(irq_rises, runs, "irq[0] pulse count");
            chk(irq_hi, runs, "irq[0] pulse width (clocks high)");
        end
    endtask

    // poll STATUS until BUSY drops; DONE must be set then
    task wait_done(input first_busy);
        integer p;
        reg fin;
        begin
            fin = 1'b0; p = 0;
            while (!fin) begin
                rdr(A_STATUS);
                p = p + 1;
                if (p == 1 && first_busy) begin
                    chk(rdat[0], 1'b1, "BUSY high on first poll after START");
                    chk(rdat[1], 1'b0, "DONE low on first poll after START");
                end
                chk(snap_la[31:16], rdat[15:0], "poll STATUS vs la_data_out");
                chk(snap_io[10], rdat[0], "poll BUSY vs io_out[10]");
                chk(snap_io[9],  rdat[1], "poll DONE vs io_out[9]");
                if (rdat[0] === 1'b0) fin = 1'b1;
                else if (rdat[0] !== 1'b1 || p > 40) $fatal(1, "FAIL case %0d: run did not finish (status %h)", cur, rdat);
            end
            if (p > max_polls) max_polls = p;
            chk(rdat[1], 1'b1, "DONE set once BUSY drops");
            runs = runs + 1;
        end
    endtask

    // after wait_done: STATUS, RESULT, CYCLES, DEBUG, mirrors and the irq count against record r
    task verify_run(input integer r, input [3:0] cnt, input [1:0] md, input err, input [17:0] pk);
        reg [31:0] st, res, cy;
        reg [7:0] sc, cl, ec;
        begin
            sc = vec[16*r+12]; cl = vec[16*r+11]; ec = vec[16*r+13];
            rdr(A_STATUS); st = rdat;  chk(st, stat_word(cnt, md, err, 1'b1, 1'b0), "STATUS after run");
            rdr(A_RESULT); res = rdat; chk(res, {16'd0, sc, 7'd0, cl[0]}, "RESULT class/score");
            rdr(A_CYCLES); cy = rdat;  chk(cy, {24'd0, ec}, "CYCLES vs vectors");
            chk(cy <= 32'd16, 1'b1, "CYCLES <= 16");
            rdr(A_DEBUG);              chk(rdat, {14'd0, pk}, "DEBUG buffer");
            chk_mirrors(st, res, cy);
            chk_irq;
            eact = md;
        end
    endtask

    function integer find_case(input [1:0] md, input [3:0] n, input [17:0] pk);
        integer r, i;
        reg ok;
        begin
            find_case = -1;
            for (r = 1; r <= nvec; r = r + 1)
                if (vec[16*r] == {6'd0, md} && vec[16*r+1] == {4'd0, n} && find_case < 0) begin
                    ok = 1'b1;
                    for (i = 0; i < n; i = i + 1) if (vec[16*r+2+i] !== {6'd0, pk[2*i +: 2]}) ok = 1'b0;
                    if (ok) find_case = r;
                end
        end
    endfunction

    function integer first_of_mode(input [1:0] md);
        integer r;
        begin
            first_of_mode = -1;
            for (r = 1; r <= nvec; r = r + 1) if (vec[16*r] == {6'd0, md} && first_of_mode < 0) first_of_mode = r;
        end
    endfunction

    // CLEAR, set the mode, check the cleared state
    task fresh(input [1:0] m);
        begin
            do_clear; set_mode(m);
            chk_stat(4'd0, eact, 1'b0, 1'b0, 1'b0, "STATUS after CLEAR");
        end
    endtask

    // verify that a verified run exists for (mode, inputs) and return its index
    function integer need_case(input [1:0] md, input [3:0] n, input [17:0] pk);
        begin
            need_case = find_case(md, n, pk);
            if (need_case < 0) $fatal(1, "FAIL TB: no vector for mode %0d inputs %h", md, pk);
        end
    endfunction

    // ---------------------------------------------------------------- 1. one vector case
    reg [17:0] cpk;
    task run_case(input integer k, input rerun);
        integer i, n;
        reg [1:0] md;
        begin
            cur = k;
            md = vec[16*k]; n = vec[16*k+1];
            cpk = 18'd0;
            for (i = 0; i < n; i = i + 1) cpk[2*i +: 2] = vec[16*k+2+i];
            do_clear;
            set_mode(md);
            rdr(A_CTRL); chk(rdat, {30'd0, md}, "CTRL readback");
            for (i = 0; i < n; i = i + 1) begin
                if (k % 2) wr(4'b0001, A_INPUT, {24'hA5A5A5, 6'd0, vec[16*k+2+i][1:0]});
                else       wr(4'hF,    A_INPUT, {30'd0, vec[16*k+2+i][1:0]});
            end
            chk_stat(n[3:0], eact, 1'b0, 1'b0, 1'b0, "STATUS before START");
            rdr(A_DEBUG); chk(rdat, {14'd0, cpk}, "DEBUG before START");
            if (k % 2) wr(4'b0010, A_CTRL, 32'h0000_0100);
            else       wr(4'hF,    A_CTRL, {30'd0, md} | 32'h0000_0100);
            wait_done(1'b1);
            verify_run(k, n[3:0], md, 1'b0, cpk);
            rdr(A_CTRL); chk(rdat, {30'd0, md}, "CTRL readback after run");
            if (rerun) begin
                // back-to-back: same buffer, no CLEAR, START again -> the same result
                go;
                wait_done(1'b1);
                verify_run(k, n[3:0], md, 1'b0, cpk);
            end
        end
    endtask

    // ---------------------------------------------------------------- 5. reset
    task rst_pulse;
        begin
            wb_rst_i = 1'b1; idle(2); wb_rst_i = 1'b0; idle(1);
        end
    endtask

    task chk_reset_state(input [8*48-1:0] what);
        reg [31:0] st, res, cy;
        begin
            rdr(A_STATUS); st = rdat;  chk(st, 32'd0, what);
            rdr(A_RESULT); res = rdat; chk(res, 32'd0, "RESULT after reset");
            rdr(A_CYCLES); cy = rdat;  chk(cy, 32'd0, "CYCLES after reset");
            rdr(A_DEBUG);              chk(rdat, 32'd0, "DEBUG after reset");
            rdr(A_CTRL);               chk(rdat, 32'd0, "CTRL after reset");
            chk_mirrors(st, res, cy);
            chk(io_out, 38'd0, "io_out after reset");
            chk(la_data_out, 128'd0, "la_data_out after reset");
        end
    endtask

    // ---------------------------------------------------------------- the test
    integer i, j, m, d, r, k0, nrec;
    reg [17:0] pk;
    reg [31:0] v32;
    reg [1:0]  mm;

    initial begin
        // header: first line that is not a comment: A5, count high, count low
        if (!$value$plusargs("VEC=%s", vfile)) $fatal(1, "FAIL no +VEC=<vectors.hex>");
        fd = $fopen(vfile, "r");
        if (fd == 0) $fatal(1, "FAIL cannot open %0s", vfile);
        h0 = 0;
        while (h0 == 0 && !$feof(fd)) begin
            if ($fgets(line, fd) && $sscanf(line, "%h %h %h", h0, h1, h2) != 3) h0 = 0;
        end
        $fclose(fd);
        if (h0 !== 32'hA5) $fatal(1, "FAIL %0s: not a vector file (header %h)", vfile, h0);
        nvec = h1 * 256 + h2;
        if (nvec < 1 || nvec >= MAXREC) $fatal(1, "FAIL bad case count %0d", nvec);
        $readmemh(vfile, vec, 0, 16 * (nvec + 1) - 1);

        // reset
        wb_rst_i = 1'b1;
        repeat (3) @(negedge wb_clk_i);
        wb_rst_i = 1'b0;
        @(negedge wb_clk_i);
        mon_en = 1'b1;
        cur = 0;
        chk_reset_state("STATUS after power-on reset");

        // ---------------- 2. registers
        cur = -2;
        rdr(A_ID);   chk(rdat, 32'h5441_4901, "ID");
        rdr(A_CAPS); chk(rdat, {8'd0, 8'd1, 4'd0, 4'd9, 5'd0, 3'b111}, "CAPS");
        chk({8'd0, 8'd1, 4'd0, 4'd9, 5'd0, 3'b111}, 32'h0001_0907, "CAPS literal");
        wb(1'b0, 4'b0001, A_ID, 32'd0); chk(rdat, 32'h0000_0001, "ID sel=0001");
        wb(1'b0, 4'b0010, A_ID, 32'd0); chk(rdat, 32'h0000_4900, "ID sel=0010");
        wb(1'b0, 4'b0100, A_ID, 32'd0); chk(rdat, 32'h0041_0000, "ID sel=0100");
        wb(1'b0, 4'b1000, A_ID, 32'd0); chk(rdat, 32'h5400_0000, "ID sel=1000");
        wb(1'b0, 4'b1100, A_ID, 32'd0); chk(rdat, 32'h5441_0000, "ID sel=1100");
        wb(1'b0, 4'b1010, A_ID, 32'd0); chk(rdat, 32'h5400_4900, "ID sel=1010");
        wb(1'b0, 4'b0000, A_ID, 32'd0); chk(rdat, 32'd0, "ID sel=0000");
        wb(1'b0, 4'b0011, A_CAPS, 32'd0); chk(rdat, 32'h0000_0907, "CAPS sel=0011");
        wb(1'b0, 4'b0100, A_CAPS, 32'd0); chk(rdat, 32'h0001_0000, "CAPS sel=0100");
        // CTRL read back
        for (i = 0; i < 4; i = i + 1) begin
            set_mode(i[1:0]);
            rdr(A_CTRL); chk(rdat, i, "CTRL readback of mode");
        end
        wr(4'b0001, A_CTRL, 32'hFFFF_FF02);              // upper bits of lane 0 data ignored, START/CLEAR not in lane 0
        rdr(A_CTRL); chk(rdat, 32'd2, "CTRL after write of 0xFFFFFF02 sel=0001");
        wb(1'b0, 4'b0001, A_CTRL, 32'd0); chk(rdat, 32'd2, "CTRL sel=0001");
        wb(1'b0, 4'b0010, A_CTRL, 32'd0); chk(rdat, 32'd0, "CTRL sel=0010 (self-clearing bits read 0)");
        wr(4'b0100, A_CTRL, 32'hFFFF_FFFF);               // lanes 2 and 3 do nothing
        wr(4'b1000, A_CTRL, 32'hFFFF_FFFF);
        wr(4'b0000, A_CTRL, 32'hFFFF_FFFF);
        rdr(A_CTRL); chk(rdat, 32'd2, "CTRL unchanged by lane 2/3/none writes");
        chk_stat(4'd0, 2'd0, 1'b0, 1'b0, 1'b0, "STATUS unchanged by lane 2/3/none writes");
        set_mode(2'd0);
        // writes to read-only offsets and unmapped offsets change nothing
        wr(4'hF, A_ID,     32'hFFFF_FFFF);
        wr(4'hF, A_STATUS, 32'hFFFF_FFFF);
        wr(4'hF, A_RESULT, 32'hFFFF_FFFF);
        wr(4'hF, A_CYCLES, 32'hFFFF_FFFF);
        wr(4'hF, A_CAPS,   32'hFFFF_FFFF);
        wr(4'hF, A_DEBUG,  32'hFFFF_FFFF);
        wr(4'hF, BASE | 32'h20, 32'hFFFF_FFFF);
        wr(4'hF, BASE | 32'h24, 32'hFFFF_FFFF);
        wr(4'hF, BASE | 32'hFC, 32'hFFFF_FFFF);
        rdr(A_ID);   chk(rdat, 32'h5441_4901, "ID after writes");
        rdr(A_CAPS); chk(rdat, 32'h0001_0907, "CAPS after writes");
        rdr(A_CTRL); chk(rdat, 32'd0, "CTRL after writes");
        rdr(A_RESULT); chk(rdat, 32'd0, "RESULT after writes");
        rdr(A_CYCLES); chk(rdat, 32'd0, "CYCLES after writes");
        rdr(A_DEBUG);  chk(rdat, 32'd0, "DEBUG after writes");
        chk_stat(4'd0, 2'd0, 1'b0, 1'b0, 1'b0, "STATUS after writes");
        // unmapped reads
        rdr(A_INPUT);        chk(rdat, 32'd0, "INPUT read");
        rdr(BASE | 32'h20);  chk(rdat, 32'd0, "read 0x20");
        rdr(BASE | 32'h24);  chk(rdat, 32'd0, "read 0x24");
        rdr(BASE | 32'h80);  chk(rdat, 32'd0, "read 0x80");
        rdr(BASE | 32'hFC);  chk(rdat, 32'd0, "read 0xFC");
        // addresses outside the window
        rdr(32'h3000_0100);  chk(rdat, 32'd0, "read 0x30000100");
        rdr(32'h3000_0000 + 32'h0000_0100); chk(rdat, 32'd0, "read window end");
        rdr(32'h3100_0000);  chk(rdat, 32'd0, "read 0x31000000");
        rdr(32'h3100_0004);  chk(rdat, 32'd0, "read 0x31000004");
        rdr(32'h2FFF_FFFC);  chk(rdat, 32'd0, "read 0x2FFFFFFC");
        rdr(32'h0000_0000);  chk(rdat, 32'd0, "read 0x0");
        rdr(32'hB000_0008);  chk(rdat, 32'd0, "read 0xB0000008");
        wr(4'hF, 32'h3000_0104, 32'hFFFF_FFFF);          // CTRL alias outside the window: START+CLEAR+mode, no effect
        wr(4'hF, 32'h3000_010C, 32'h0000_0001);          // INPUT alias
        wr(4'hF, 32'h3100_0004, 32'h0000_0103);
        wr(4'hF, 32'h3100_000C, 32'h0000_0001);
        wr(4'hF, 32'h0000_000C, 32'h0000_0001);
        rdr(A_ID);   chk(rdat, 32'h5441_4901, "ID after outside writes");
        rdr(A_CTRL); chk(rdat, 32'd0, "CTRL after outside writes");
        rdr(A_DEBUG); chk(rdat, 32'd0, "DEBUG after outside writes");
        chk_stat(4'd0, 2'd0, 1'b0, 1'b0, 1'b0, "STATUS/count after outside writes");
        // DEBUG reflects the buffer, 2 bits per input, input 0 in bits 1:0
        fresh(2'd2);
        push(32'd3); push(32'd2); push(32'd1); push(32'd0);
        rdr(A_DEBUG); chk(rdat, 32'h0000_001B, "DEBUG mode 2 inputs 3,2,1,0");
        wb(1'b0, 4'b0001, A_DEBUG, 32'd0); chk(rdat, 32'h0000_001B, "DEBUG sel=0001");
        wb(1'b0, 4'b0010, A_DEBUG, 32'd0); chk(rdat, 32'd0, "DEBUG sel=0010");
        chk_stat(4'd4, 2'd0, 1'b0, 1'b0, 1'b0, "STATUS count 4");
        rdr(A_INPUT);        chk(rdat, 32'd0, "INPUT read with data buffered");
        fresh(2'd1);
        pk = 18'd0;
        for (i = 0; i < 9; i = i + 1) begin
            v32 = (i * 5 + 1) & 1;
            pk[2*i +: 2] = v32[1:0];
            push({24'hFFFFFF, 7'd0, v32[0]} & 32'hFFFF_FF01);   // upper bits of the data word are ignored
        end
        rdr(A_DEBUG); chk(rdat, {14'd0, pk}, "DEBUG mode 1 nine inputs");
        chk_stat(4'd9, 2'd0, 1'b0, 1'b0, 1'b0, "STATUS count 9");
        do_clear;
        rdr(A_DEBUG); chk(rdat, 32'd0, "DEBUG after CLEAR");
        chk_stat(4'd0, 2'd0, 1'b0, 1'b0, 1'b0, "STATUS after CLEAR");
        chk_irq;

        // ---------------- 3. protocol negatives
        // too few inputs; ERROR is sticky and does not stop a later valid START
        cur = -3;
        fresh(2'd0);
        push(1); push(0); push(1);
        go;
        chk_stat(4'd3, 2'd0, 1'b1, 1'b0, 1'b0, "too few: ERROR, no run");
        idle(30); chk_stat(4'd3, 2'd0, 1'b1, 1'b0, 1'b0, "too few: still no run"); chk_irq;
        push(1);
        chk_stat(4'd4, 2'd0, 1'b1, 1'b0, 1'b0, "ERROR sticky after another INPUT");
        go; wait_done(1'b1);
        verify_run(need_case(0, 4, 18'b01_01_00_01), 4'd4, 2'd0, 1'b1, 18'b01_01_00_01);
        idle(30); chk_stat(4'd4, 2'd0, 1'b1, 1'b1, 1'b0, "DONE and ERROR persist");
        do_clear;
        chk_stat(4'd0, 2'd0, 1'b0, 1'b0, 1'b0, "CLEAR drops ERROR and DONE");

        // too many for mode 0, wrong count for the other modes
        fresh(2'd0);
        for (i = 0; i < 5; i = i + 1) push(1);
        chk_stat(4'd5, eact, 1'b0, 1'b0, 1'b0, "5 inputs accepted into the buffer");
        go;
        chk_stat(4'd5, eact, 1'b1, 1'b0, 1'b0, "too many (5 in mode 0): ERROR, no run");
        idle(30); chk_stat(4'd5, eact, 1'b1, 1'b0, 1'b0, "too many: still no run"); chk_irq;
        do_clear; chk_stat(4'd0, eact, 1'b0, 1'b0, 1'b0, "CLEAR after too many");
        fresh(2'd0);
        for (i = 0; i < 9; i = i + 1) push(0);
        go; chk_stat(4'd9, eact, 1'b1, 1'b0, 1'b0, "9 inputs in mode 0");
        do_clear;
        fresh(2'd1);
        for (i = 0; i < 4; i = i + 1) push(1);
        go; chk_stat(4'd4, eact, 1'b1, 1'b0, 1'b0, "4 inputs in mode 1");
        do_clear;
        fresh(2'd2);
        for (i = 0; i < 3; i = i + 1) push(3);
        go; chk_stat(4'd3, eact, 1'b1, 1'b0, 1'b0, "3 inputs in mode 2");
        push(0); push(0);
        go; chk_stat(4'd5, eact, 1'b1, 1'b0, 1'b0, "5 inputs in mode 2");
        idle(30); chk_irq;
        do_clear;
        chk_stat(4'd0, eact, 1'b0, 1'b0, 1'b0, "CLEAR after wrong counts");

        // START in mode 3
        fresh(2'd0);
        push(1); push(1); push(0); push(0);
        set_mode(2'd3);
        rdr(A_CTRL); chk(rdat, 32'd3, "CTRL mode 3");
        go;
        chk_stat(4'd4, eact, 1'b1, 1'b0, 1'b0, "START in mode 3: ERROR, no run");
        idle(30); chk_stat(4'd4, eact, 1'b1, 1'b0, 1'b0, "mode 3: still no run"); chk_irq;
        set_mode(2'd0); go; wait_done(1'b1);
        verify_run(need_case(0, 4, 18'b00_00_01_01), 4'd4, 2'd0, 1'b1, 18'b00_00_01_01);
        do_clear;
        // any INPUT in mode 3 is an error
        fresh(2'd3);
        for (i = 0; i < 4; i = i + 1) begin
            do_clear; set_mode(2'd3);
            case (i) 0: v32 = 0; 1: v32 = 1; 2: v32 = 3; default: v32 = 255; endcase
            push(v32);
            chk_stat(4'd0, eact, 1'b1, 1'b0, 1'b0, "INPUT in mode 3: ERROR, not pushed");
            rdr(A_DEBUG); chk(rdat, 32'd0, "DEBUG after rejected input");
        end
        do_clear;

        // out-of-range inputs
        for (i = 0; i < 8; i = i + 1) begin
            case (i)
                0: begin mm = 0; v32 = 2;    end
                1: begin mm = 0; v32 = 255;  end
                2: begin mm = 1; v32 = 2;    end
                3: begin mm = 1; v32 = 3;    end
                4: begin mm = 2; v32 = 4;    end
                5: begin mm = 2; v32 = 5;    end
                6: begin mm = 2; v32 = 128;  end
                default: begin mm = 0; v32 = 32'h0000_0102; end   // low byte 2
            endcase
            fresh(mm);
            push(v32);
            chk_stat(4'd0, eact, 1'b1, 1'b0, 1'b0, "out-of-range input: ERROR, not pushed");
            rdr(A_DEBUG); chk(rdat, 32'd0, "DEBUG after out-of-range input");
            do_clear;
            chk_stat(4'd0, eact, 1'b0, 1'b0, 1'b0, "CLEAR drops ERROR (range)");
        end
        // in-range edge values are accepted; data bits above the low byte are not looked at
        fresh(2'd2); push(3); push(32'hFFFF_FF02); push(1); push(32'h0000_0100);
        chk_stat(4'd4, eact, 1'b0, 1'b0, 1'b0, "mode 2 edge values accepted");
        rdr(A_DEBUG); chk(rdat, {14'd0, 8'b00_01_10_11}, "DEBUG mode 2 edge values");
        do_clear;

        // a 10th input when 9 are buffered (mode 1)
        fresh(2'd1);
        pk = 18'd0;
        for (i = 0; i < 9; i = i + 1) begin
            v32 = (i % 3 == 0) ? 1 : (i % 2);
            pk[2*i +: 2] = v32[1:0];
            push(v32);
        end
        chk_stat(4'd9, eact, 1'b0, 1'b0, 1'b0, "nine inputs buffered");
        push(1);
        chk_stat(4'd9, eact, 1'b1, 1'b0, 1'b0, "10th input: ERROR, count stays 9");
        push(0);
        rdr(A_DEBUG); chk(rdat, {14'd0, pk}, "DEBUG unchanged by the 10th input");
        go; wait_done(1'b1);
        verify_run(need_case(1, 9, pk), 4'd9, 2'd1, 1'b1, pk);
        do_clear;

        // START while busy, INPUT while busy, CLEAR while busy (mode 1: longest run)
        for (j = 0; j < 3; j = j + 1) begin
            fresh(2'd1);
            pk = 18'd0;
            for (i = 0; i < 9; i = i + 1) begin
                v32 = ((i + j) % 2);
                pk[2*i +: 2] = v32[1:0];
                push(v32);
            end
            go;
            case (j)
                0: go;                                             // START while busy
                1: push(1);                                        // INPUT while busy
                default: do_clear;                                 // CLEAR while busy
            endcase
            rdr(A_STATUS);
            chk(rdat, stat_word(4'd9, 2'd1, 1'b1, 1'b0, 1'b1), "busy-time command: ERROR, still BUSY");
            rdr(A_DEBUG); chk(rdat, {14'd0, pk}, "DEBUG unchanged by busy-time command");
            wait_done(1'b0);
            verify_run(need_case(1, 9, pk), 4'd9, 2'd1, 1'b1, pk);
            idle(20); chk_irq;
            do_clear;
            chk_stat(4'd0, eact, 1'b0, 1'b0, 1'b0, "CLEAR after busy-time command");
        end

        // byte-select: lane-0-only CTRL write with the START bit does not start; wrong-lane INPUT does not push
        fresh(2'd0);
        push(1); push(0); push(0); push(1);
        wr(4'b0001, A_CTRL, 32'h0000_0100);
        chk_stat(4'd4, eact, 1'b0, 1'b0, 1'b0, "CTRL sel=0001 with START bit: no run");
        idle(30); chk_stat(4'd4, eact, 1'b0, 1'b0, 1'b0, "CTRL sel=0001 with START bit: still idle"); chk_irq;
        wr(4'b0001, A_CTRL, 32'h0000_0200);
        chk_stat(4'd4, eact, 1'b0, 1'b0, 1'b0, "CTRL sel=0001 with CLEAR bit: no clear");
        wr(4'b0001, A_CTRL, 32'h0000_0102);
        rdr(A_CTRL); chk(rdat, 32'd2, "CTRL sel=0001 wrote the mode only");
        chk_stat(4'd4, eact, 1'b0, 1'b0, 1'b0, "mode write alone does not start");
        set_mode(2'd0);
        wr(4'b0100, A_CTRL, 32'h0000_0100); wr(4'b1000, A_CTRL, 32'h0000_0100); wr(4'b0000, A_CTRL, 32'h0000_0100);
        wr(4'b0101, A_CTRL, 32'h0000_0100); wr(4'b0001, A_CTRL, 32'h0001_0300);
        chk_stat(4'd4, eact, 1'b0, 1'b0, 1'b0, "other-lane CTRL writes: no run");
        wr(4'b0010, A_INPUT, 32'h0000_0101); wr(4'b0100, A_INPUT, 32'h0000_0101);
        wr(4'b1000, A_INPUT, 32'h0000_0101); wr(4'b0000, A_INPUT, 32'h0000_0101);
        wr(4'b1110, A_INPUT, 32'h0101_0101);
        chk_stat(4'd4, eact, 1'b0, 1'b0, 1'b0, "INPUT without lane 0: not pushed, no ERROR");
        rdr(A_DEBUG); chk(rdat, {14'd0, 8'b01_00_00_01}, "DEBUG after wrong-lane INPUT");
        go; wait_done(1'b1);
        verify_run(need_case(0, 4, 18'b01_00_00_01), 4'd4, 2'd0, 1'b0, 18'b01_00_00_01);
        do_clear;

        // START and CLEAR in one write: CLEAR wins
        for (i = 0; i < 3; i = i + 1) begin
            fresh(2'd0);
            push(1); push(1); push(1); push(1);
            if (i == 0)      wr(4'hF,       A_CTRL, 32'h0000_0300);
            else if (i == 1) wr(4'b0010,    A_CTRL, 32'h0000_0300);
            else             wr(4'hF,       A_CTRL, 32'hFFFF_FF00);
            chk_stat(4'd0, eact, 1'b0, 1'b0, 1'b0, "START+CLEAR: CLEAR wins");
            idle(30); chk_stat(4'd0, eact, 1'b0, 1'b0, 1'b0, "START+CLEAR: no run"); chk_irq;
            rdr(A_DEBUG); chk(rdat, 32'd0, "START+CLEAR clears the buffer");
        end
        // START+CLEAR after a finished run clears DONE
        fresh(2'd0); push(0); push(1); push(1); push(0);
        go; wait_done(1'b1);
        verify_run(need_case(0, 4, 18'b00_01_01_00), 4'd4, 2'd0, 1'b0, 18'b00_01_01_00);
        wr(4'hF, A_CTRL, 32'h0000_0300);
        chk_stat(4'd0, eact, 1'b0, 1'b0, 1'b0, "START+CLEAR after a run clears DONE");
        chk_irq;

        // DONE / ERROR persistence, back-to-back runs
        cur = -4;
        fresh(2'd2); push(3); push(0); push(2); push(1);
        go; wait_done(1'b1);
        pk = 18'b01_10_00_11;
        verify_run(need_case(2, 4, pk), 4'd4, 2'd2, 1'b0, pk);
        idle(40); chk_stat(4'd4, eact, 1'b0, 1'b1, 1'b0, "DONE persists");
        push(2);                                                    // idle INPUT with count 4: still in range -> count 5
        chk_stat(4'd5, eact, 1'b0, 1'b1, 1'b0, "INPUT after a run keeps DONE");
        push(7);
        chk_stat(4'd5, eact, 1'b1, 1'b1, 1'b0, "rejected INPUT sets ERROR, DONE stays");
        set_mode(2'd3); go;
        chk_stat(4'd5, eact, 1'b1, 1'b1, 1'b0, "invalid START leaves DONE");
        set_mode(2'd2); go;                                         // count 5 != 4
        chk_stat(4'd5, eact, 1'b1, 1'b1, 1'b0, "wrong-count START leaves DONE");
        chk_irq;
        do_clear;
        chk_stat(4'd0, eact, 1'b0, 1'b0, 1'b0, "CLEAR drops DONE and ERROR");
        rdr(A_RESULT); chk(rdat, 32'd0, "RESULT after CLEAR");
        rdr(A_CYCLES); chk(rdat, 32'd0, "CYCLES after CLEAR");
        rdr(A_DEBUG);  chk(rdat, 32'd0, "DEBUG after CLEAR (run)");
        chk(io_out, {16'd0, 8'd0, eact, 4'd0, 8'd0}, "io_out after CLEAR");
        chk(la_data_out, {96'd0, 8'd0, 8'd0, 2'd0, eact, 4'd0, 16'd0}, "la_data_out after CLEAR");
        // back-to-back without CLEAR: the next valid START clears DONE and runs again; the buffer is kept
        fresh(2'd1);
        pk = 18'd0;
        for (i = 0; i < 9; i = i + 1) begin v32 = (i == 2 || i == 5 || i == 8); pk[2*i +: 2] = v32[1:0]; push(v32); end
        for (i = 0; i < 4; i = i + 1) begin
            go; wait_done(1'b1);
            verify_run(need_case(1, 9, pk), 4'd9, 2'd1, 1'b0, pk);
        end
        // switch mode between runs without CLEAR: count 9 is wrong for mode 0 -> ERROR, DONE kept
        set_mode(2'd0); go;
        chk_stat(4'd9, eact, 1'b1, 1'b1, 1'b0, "mode switch without CLEAR: wrong count");
        do_clear;
        // a different mode after CLEAR; STATUS active mode follows the run
        fresh(2'd0); push(1); push(1); push(1); push(1);
        go; wait_done(1'b1);
        verify_run(need_case(0, 4, 18'b01_01_01_01), 4'd4, 2'd0, 1'b0, 18'b01_01_01_01);
        do_clear;

        // ---------------- 5. reset during a run (and while idle with state)
        cur = -5;
        for (m = 0; m < 3; m = m + 1) begin
            k0 = first_of_mode(m[1:0]);
            if (k0 < 0) $fatal(1, "FAIL TB: no vector for mode %0d", m);
            for (d = 0; d < 20; d = d + 1) begin
                cur = -500 - 100 * m - d;
                nrec = vec[16*k0+1];
                fresh(m[1:0]);
                for (i = 0; i < nrec; i = i + 1) push(vec[16*k0+2+i]);
                go;
                idle(d);
                rst_pulse;
                if (irq_rises != runs && irq_rises != runs + 1) $fatal(1, "FAIL case %0d: irq pulse count %0d runs %0d", cur, irq_rises, runs);
                chk(irq_hi, irq_rises, "irq pulse width around reset");
                runs = irq_rises;
                eact = 2'd0;
                chk_reset_state("STATUS after reset in a run");
                idle(30);
                chk_stat(4'd0, 2'd0, 1'b0, 1'b0, 1'b0, "reset state holds");
                chk_irq;
                if (d % 7 == 0) begin
                    run_case(k0, 1'b0);
                    eact = vec[16*k0];
                end
            end
        end
        // reset with a finished result and an error pending
        fresh(2'd0); push(1); push(1); push(0); push(1);
        go; wait_done(1'b1);
        push(2);
        rst_pulse; eact = 2'd0;
        chk_reset_state("STATUS after reset with DONE+ERROR");
        chk_irq;
        // after reset one case of every mode passes
        for (m = 0; m < 3; m = m + 1) begin
            k0 = first_of_mode(m[1:0]);
            run_case(k0, 1'b1);
            if (m == 1) begin
                // reset right after a result, then the same case again
                rst_pulse; eact = 2'd0;
                chk_reset_state("STATUS after reset following a result");
                run_case(k0, 1'b0);
            end
        end

        // ---------------- 1. every vector case
        for (i = 1; i <= nvec; i = i + 1) begin
            run_case(i, (i % 3) == 0);
            // no stray pulses between cases: the count stays equal to the number of completed runs
        end
        idle(20);
        chk_irq;
        chk(acks, reqs, "every request acknowledged exactly once");

        $display("PASS tiny_ai_core_tb: %0d cases, %0d checks (%0d wishbone transactions; results, CYCLES<=16, irq, GPIO/LA mirrors, registers, byte lanes, window decode, protocol errors, back-to-back, reset)",
                 nvec, n_checks, n_tx);
        $finish;
    end
endmodule
