// Generated by model/precision_hw/gen.py from model/precision_hw/golden.py; do not edit.
// source sha256 bd114534c7c5336b459aecd7842971a1fa2183e1751e6a3c639c7effa9cbd748
`timescale 1ns/1ps
// prec_bf16 parameter ROM (model/precision_hw/spec.md): bfloat16 bit patterns (subnormals flushed to +0 at quantisation); the bias is in the same format.
// Constants are continuous assignments (no always block): read by the one serial MAC, weight[addr] per input.
module prec_bf16_rom (
    input  wire        [3:0]  addr,     // pixel index 0..8, raster order (>= 9 reads 0)
    output wire        [15:0] weight,
    output wire        [15:0] bias
);
    localparam [15:0] W0 = 16'h3C72;   // +0.0147705078  (fp32 +0.014786)
    localparam [15:0] W1 = 16'h3E95;   // +0.291015625  (fp32 +0.291126)
    localparam [15:0] W2 = 16'h3CEC;   // +0.0288085938  (fp32 +0.028851)
    localparam [15:0] W3 = 16'hBEA2;   // -0.31640625  (fp32 -0.316742)
    localparam [15:0] W4 = 16'hBC9C;   // -0.0190429688  (fp32 -0.019083)
    localparam [15:0] W5 = 16'hBE89;   // -0.267578125  (fp32 -0.267208)
    localparam [15:0] W6 = 16'h3D37;   // +0.0446777344  (fp32 +0.044593)
    localparam [15:0] W7 = 16'h3E97;   // +0.294921875  (fp32 +0.294643)
    localparam [15:0] W8 = 16'h3A5A;   // +0.000831604004  (fp32 +0.000830)
    localparam [15:0] B  = 16'hBE3A;   // -0.181640625  (fp32 bias -0.181312)
    assign weight = (addr == 4'd0) ? W0 :
                    (addr == 4'd1) ? W1 :
                    (addr == 4'd2) ? W2 :
                    (addr == 4'd3) ? W3 :
                    (addr == 4'd4) ? W4 :
                    (addr == 4'd5) ? W5 :
                    (addr == 4'd6) ? W6 :
                    (addr == 4'd7) ? W7 :
                    (addr == 4'd8) ? W8 : 16'h0000;
    assign bias = B;
endmodule
