#!/usr/bin/env python3
"""gen_rom.py -- generate, from weights.json and golden.py:
  designs/audio_pitch/rtl/audio_pitch_rom.v   the threshold ROM (continuous assigns only)
  designs/audio_pitch/tb/vectors.hex          test vectors for designs/audio_pitch/tb/audio_pitch_tb.v
Files are rewritten only when their content changes (the flow's stale-run check compares timestamps).

Vector file ($readmemh, 32-bit words). Word 0 = {8'hA5, 24'd number of beats}, word 1 = number of recordings
(s_last count), word 2 = index of the first beat of the reset-test recording, word 3 = index after it. Words 4.. =
one word per INPUT beat: [7:0] s_data, [8] s_last, [9] a result beat is expected after this beat is accepted,
[10] its m_last, [18:11] its m_data = {error, class, count[5:0]}."""
import os, random, hashlib
import golden

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))


def sha256_of(*paths):
    h = hashlib.sha256()
    for p in paths:
        h.update(os.path.relpath(p, REPO).encode() + b"\0" + open(p, "rb").read())
    return h.hexdigest()


def header(h):
    return ("// Generated by model/audio_pitch/gen_rom.py from model/audio_pitch/weights.json; do not edit.\n"
            "// source sha256 %s\n`timescale 1ns/1ps\n" % h)


def rom_verilog(w, h):
    # continuous assignment only: an always @(*) block whose input never changes is never evaluated in simulation
    return header(h) + """// The learned decision threshold of audio_pitch: class = (count of sign changes in the window >= threshold).
module audio_pitch_rom (
    output wire [3:0] threshold
);
    assign threshold = 4'd%d;
endmodule
""" % w["threshold"]


def square(half, phase, n):
    return [1 if ((i + phase) // half) % 2 == 0 else 0 for i in range(n)]


def de_bruijn(k, n):
    a, seq = [0] * k * n, []
    def db(t, p):
        if t > n:
            if n % p == 0:
                seq.extend(a[1:p + 1])
        else:
            a[t] = a[t - p]
            db(t + 1, p)
            for j in range(a[t - p] + 1, k):
                a[t] = j
                db(t + 1, t)
    db(1, 1)
    return seq


def recordings(W):
    """list of recordings, each a list of (s_data, last)."""
    rng = random.Random(7)
    rec = []
    plain = lambda bits: [(b, i == len(bits) - 1) for i, b in enumerate(bits)]
    # 1. every possible window content: all 2^W sign patterns, each a recording of exactly W samples
    for v in range(1 << W):
        rec.append(plain([(v >> (W - 1 - i)) & 1 for i in range(W)]))
    # 2. one long recording containing every W-bit window in a continuing stream (de Bruijn B(2,W) + wrap)
    s = de_bruijn(2, W)
    rec.append(plain(s + s[:W - 1]))
    # 3. generated waveforms: tone of every half-period and several phases, then a tone change, with noise
    for half in (1, 2, 3, 4, 6, 8, 12, 16):
        for phase in (0, half // 2, 2 * half - 1):
            rec.append(plain(square(half, phase, 40)))
    for lo, hi in ((12, 2), (8, 3), (2, 8), (3, 12), (1, 6)):
        rec.append(plain(square(lo, 0, 24) + square(hi, 1, 24)))
    for half in (2, 3, 8, 12):
        bits = square(half, 0, 48)
        for _ in range(5):
            bits[rng.randrange(48)] ^= 1
        rec.append(plain(bits))
    # 4. short recordings (shorter than the warm-up: no result beat at all), lengths 1..W-1
    for n in range(1, W):
        rec.append(plain(square(1, 0, n)))
        rec.append(plain([1] * n))
    # 5. exactly warm-up long plus one, and recordings ending right after the first result
    rec.append(plain(square(1, 0, W + 1)))
    # 6. error beats: bad byte at every position of a 12-sample stream, several values (bit 0 still used)
    for bad in (0x02, 0x03, 0x80, 0xFF, 0x7E):
        for pos in range(12):
            bits = square(2, 0, 12)
            r = plain(bits)
            r[pos] = (bad, r[pos][1])
            rec.append(r)
    rec.append([(0x02, False), (0xFE, False), (0x01, True)])                 # errors dropped with a short recording
    rec.append([(0x04, False)] + plain(square(2, 0, 20)))                    # error in warm-up reaches the first result only
    # 7. history really cleared: the same samples after a recording, and a recording ending on a warm beat
    rec.append(plain([1] * 20))
    rec.append(plain([0, 1] * 10))
    # 8. last: the reset-test recording (run again after resets in the testbench)
    rec.append(plain(square(1, 0, W) + [0, 0, 1, 1]))
    return rec


def build(w):
    W, T = w["window"], w["threshold"]
    g = golden.Pitch(W, T)
    words, nrec = [], 0
    reset_start = None
    recs = recordings(W)
    for ri, r in enumerate(recs):
        if ri == len(recs) - 1:
            reset_start = len(words)
        samples = []
        for d, last in r:
            samples.append(d & 1)
            o = g.push(d, last)
            if o:
                assert (o[0] & 63) == golden.recount(samples, W) and len(samples) >= W   # independent recount agrees
                word = d | last << 8 | 1 << 9 | o[1] << 10 | o[0] << 11
            else:
                word = d | last << 8
            words.append(word)
        nrec += 1
    return words, nrec, reset_start


def write_if_changed(path, text):
    try:
        if open(path).read() == text:
            return
    except OSError:
        pass
    open(path, "w").write(text)


def main():
    w = golden.params()
    h = sha256_of(golden.WEIGHTS_PATH, os.path.join(HERE, "golden.py"), os.path.abspath(__file__), os.path.join(HERE, "spec.json"))
    rom = os.path.join(REPO, "designs", "audio_pitch", "rtl", "audio_pitch_rom.v")
    vec = os.path.join(REPO, "designs", "audio_pitch", "tb", "vectors.hex")
    os.makedirs(os.path.dirname(rom), exist_ok=True)
    os.makedirs(os.path.dirname(vec), exist_ok=True)
    write_if_changed(rom, rom_verilog(w, h))
    words, nrec, rs = build(w)
    n = len(words)
    nres = sum(1 for x in words if x >> 9 & 1)
    lines = ["// Generated by model/audio_pitch/gen_rom.py from model/audio_pitch/weights.json and golden.py; do not edit.",
             "// source sha256 %s" % h,
             "// audio_pitch: %d input beats, %d recordings, %d expected result beats (word layout in gen_rom.py)" % (n, nrec, nres),
             "%08x" % (0xA5 << 24 | n), "%08x" % nrec, "%08x" % (4 + rs), "%08x" % (4 + n)]
    lines += ["%08x" % x for x in words]
    write_if_changed(vec, "\n".join(lines) + "\n")
    print("gen_rom: %s, %s (%d beats, %d recordings, %d result beats)" % (os.path.relpath(rom, REPO), os.path.relpath(vec, REPO), n, nrec, nres))


if __name__ == "__main__":
    main()
