#!/usr/bin/env python3
"""gen_rom.py -- generate, from weights.json and golden.py:
  designs/audio_onset/rtl/audio_onset_rom.v   the weights and the threshold (continuous assigns only)
  designs/audio_onset/tb/vectors.hex          test vectors for designs/audio_onset/tb/audio_onset_tb.v
Both carry a source sha256 header and are written only when their content changes. Never edit them by hand.

Sum range: for weights w and energies 0..15 the sum lies in [15*sum(min(w,0)), 15*sum(max(w,0))]. The RTL computes it
in 6 bits (two's complement, -32..31); this script refuses to generate a ROM whose exact range does not fit (the 6-bit
modular arithmetic is then exact, even though single products are also computed in 6 bits and may wrap).

Vector file: $readmemh of 32-bit words ('//' comment lines allowed).
  word 0 = A5A5A5A5, word 1 = number of beats N, word 2 = number of expected output beats.
  words 3..N+2, one per input beat:
    [7:0]   s_data              [8]  s_last
    [9]     DRAIN-RESET: wait until every earlier result has been taken, then pulse rst (reset between beats of a stream)
    [10]    this beat produces an output beat      [18:11] expected m_data     [19] expected m_last
    [20]    STALL-RESET: hold m_ready low until a result is waiting at the output, then pulse rst (that result is lost)
Streams: (1) de Bruijn B(16,4): one stream of 65539 samples in which each of the 65,536 four-sample windows occurs
exactly once; (2) short streams, s_last everywhere, error samples, generated onset sequences, resets."""
import os, random
from common import REPO, WEIGHTS_PATH, SPEC_PATH, sha256_of, spec, weights, write_if_changed
import golden

HERE = os.path.dirname(os.path.abspath(__file__))
ROM_PATH = os.path.join(REPO, "designs", "audio_onset", "rtl", "audio_onset_rom.v")
VEC_PATH = os.path.join(REPO, "designs", "audio_onset", "tb", "vectors.hex")


def de_bruijn(k, n):
    a, seq = [0] * (k * n), []

    def db(t, p):
        if t > n:
            if n % p == 0:
                seq.extend(a[1:p + 1])
        else:
            a[t] = a[t - p]
            db(t + 1, p)
            for j in range(a[t - p] + 1, k):
                a[t] = j
                db(t + 1, t)
    db(1, 1)
    return seq


def lit(v, bits):
    return ("%d'sd%d" % (bits, v)) if v >= 0 else ("-%d'sd%d" % (bits, -v))


def rom_verilog(h):
    w, T = weights()["weights"], weights()["threshold"]
    lo, hi = 15 * sum(min(a, 0) for a in w), 15 * sum(max(a, 0) for a in w)
    assert all(-4 <= a <= 3 for a in w), "weights must fit 3-bit signed"
    assert -32 <= lo and hi <= 31, "sum range %d..%d does not fit the 6-bit datapath" % (lo, hi)
    assert -32 <= T <= 31, "threshold does not fit 6-bit signed"
    names = ("oldest", "second-oldest", "second-newest", "newest")
    body = "\n".join("    assign w%d = %s;   // applies to the %s energy" % (i, lit(a, 3), names[i]) for i, a in enumerate(w))
    return ("// Generated by model/audio_onset/gen_rom.py from model/audio_onset/weights.json; do not edit.\n"
            "// source sha256 %s\n`timescale 1ns/1ps\n"
            "// Learned weights (signed 3 bit) and threshold (signed 6 bit) of the one neuron. Exact sum range with these\n"
            "// weights and 4-bit energies: %d..%d (fits the 6-bit signed sum in audio_onset.v).\n"
            "module audio_onset_rom (\n    output wire signed [2:0] w0,\n    output wire signed [2:0] w1,\n"
            "    output wire signed [2:0] w2,\n    output wire signed [2:0] w3,\n    output wire signed [5:0] threshold\n);\n"
            "%s\n    assign threshold = %s;   // class = (sum >= threshold)\nendmodule\n") % (h, lo, hi, body, lit(T, 6))


def build_beats():
    """List of (s_data, s_last, drain_reset, stall_reset)."""
    rng = random.Random(spec()["data"]["seed"] + 1)
    B = []

    def add(d, l=0, r=0, sr=0):
        B.append((d, int(l), r, sr))

    def stream(samples, **kw):
        for i, d in enumerate(samples):
            add(d, i == len(samples) - 1, **(kw if i == 0 else {}))

    # 1. de Bruijn: every 4-sample window exactly once (the last three windows wrap around the cycle)
    db = de_bruijn(16, 4)
    assert len(db) == 65536
    full = db + db[:3]
    assert len({tuple(full[i:i + 4]) for i in range(65536)}) == 65536
    stream(full)
    # 2. extremes and short streams (lengths 1..8), single-beat streams (s_last on every beat)
    for n in range(1, 9):
        stream([15] * n)
        stream([0] * n)
    for _ in range(20):
        add(rng.randrange(16), 1)
    # history reset: a loud tail must not leak across s_last
    stream([15, 15, 15]); stream([0, 0, 0, 0]); stream([15, 15, 15, 15, 0, 0, 0, 0, 15, 15, 15, 15])
    # 3. generated onset sequences (constant, step, ramps up and down, small noise, random)
    for _ in range(150):
        n, kind = rng.randrange(4, 25), rng.randrange(6)
        a, b = rng.randrange(16), rng.randrange(16)
        if kind == 0:
            s = [a] * n
        elif kind == 1:
            s = [a if i < n // 2 else b for i in range(n)]
        elif kind == 2:
            s = [min(15, i * (1 + a % 3)) for i in range(n)]
        elif kind == 3:
            s = [max(0, 15 - i * (1 + a % 3)) for i in range(n)]
        elif kind == 4:
            s = [min(15, max(0, a + rng.randrange(-2, 3))) for _ in range(n)]
        else:
            s = [rng.randrange(16) for _ in range(n)]
        stream(s)
    # 4. error inputs: every bad high nibble at every position of an 8-sample stream, plus special cases
    for pos in range(8):
        for hi in (1, 2, 4, 8, 15, 10):
            s = [rng.randrange(16) for _ in range(8)]
            s[pos] |= hi << 4
            stream(s)
    stream([0x10, 1, 2]); stream([0x20, 3, 4, 5, 6, 7]); stream([1, 2, 3, 4, 5, 0xF0]); stream([1, 2, 3, 4, 5, 6])
    stream([0xFF] * 5); stream([0x80])
    # 5. resets: drain-reset in the middle of streams (warm-up restarts); stall-reset (a waiting result is discarded,
    #    it follows a beat that produced an output)
    for _ in range(60):
        n = rng.randrange(2, 12)
        s = [rng.randrange(16) for _ in range(n)]
        cut = rng.randrange(1, n)
        for i, d in enumerate(s):
            add(d, i == n - 1, r=int(i == cut))
    for _ in range(30):
        n = rng.randrange(5, 12)
        s = [rng.randrange(16) for _ in range(n)]
        cut = rng.randrange(4, n)       # beat cut-1 has emitted (count reached 3)
        for i, d in enumerate(s):
            add(d, i == n - 1, sr=int(i == cut))
    stream([15] * 5); stream([0] * 6, sr=1)    # full-loud history, reset with a result waiting, quiet stream
    return B


def cross_check(B, exp):
    """Drive golden.Engine cycle by cycle with random gaps and stalls (resets done the way the testbench does them)
    and compare its output beats with the function view: pacing may change only WHEN beats move."""
    rng = random.Random(99)
    eng, got = golden.Engine(), []

    def tick(rst, sv, d, l, mr):
        out, bi, bo = eng.clock(rst, sv, d, l, mr)
        if bo:
            got.append((out[1], out[2]))
        return bi

    for i, (d, l, r, sr) in enumerate(B):
        if r:
            while eng.mv:
                tick(0, 0, rng.randrange(256), rng.randrange(2), rng.random() < 0.5)
        elif sr:
            tick(0, 0, 0, 0, 0)
            assert eng.mv, "stall-reset without a waiting result at beat %d" % i
        if r or sr:
            tick(1, 0, 0, 0, 0); tick(1, 0, 0, 0, 0)
        offered = False
        while True:
            if not offered and rng.random() < 0.25:
                tick(0, 0, rng.randrange(256), rng.randrange(2), rng.random() < 0.5)
                continue
            offered = True
            if tick(0, 1, d, l, rng.random() < 0.5):
                break
    while eng.mv:
        tick(0, 0, 0, 0, rng.random() < 0.5)
    keep = [e for i, e in enumerate(exp) if e is not None and not (i + 1 < len(B) and B[i + 1][3])]
    assert got == keep, "cycle model and function model disagree (%d vs %d beats)" % (len(got), len(keep))


def vectors_text(h):
    B = build_beats()
    exp = golden.run_beats([(d, l, r or sr) for d, l, r, sr in B])
    for i, (d, l, r, sr) in enumerate(B):
        assert not sr or (i > 0 and exp[i - 1] is not None), "stall-reset needs a result waiting (beat %d)" % i
    cross_check(B, exp)
    nexp = sum(e is not None for e in exp)
    words = ["a5a5a5a5", "%08x" % len(B), "%08x" % nexp]
    for (d, l, r, sr), e in zip(B, exp):
        v = d | l << 8 | r << 9 | sr << 20
        if e is not None:
            v |= 1 << 10 | e[0] << 11 | e[1] << 19
        words.append("%08x" % v)
    head = ("// Generated by model/audio_onset/gen_rom.py from weights.json, spec.json, golden.py; do not edit.\n"
            "// source sha256 %s\n// audio_onset: %d beats, %d expected output beats (record layout in gen_rom.py)\n"
            % (h, len(B), nexp))
    return head + "\n".join(words) + "\n"


def main():
    hv = sha256_of(WEIGHTS_PATH, SPEC_PATH, os.path.join(HERE, "golden.py"), os.path.join(HERE, "gen_rom.py"))
    a = write_if_changed(ROM_PATH, rom_verilog(sha256_of(WEIGHTS_PATH)))
    b = write_if_changed(VEC_PATH, vectors_text(hv))
    print("audio_onset_rom.v %s; vectors.hex %s" % ("written" if a else "unchanged", "written" if b else "unchanged"))


if __name__ == "__main__":
    main()
