// Generated by model/audio_pitch/gen_rom.py from model/audio_pitch/weights.json; do not edit.
// source sha256 9f33f2cca5d05db4d71be545ec902b1646df9c0dc4dffc00e792f356f779f40c
`timescale 1ns/1ps
// The learned decision threshold of audio_pitch: class = (count of sign changes in the window >= threshold).
module audio_pitch_rom (
    output wire [3:0] threshold
);
    assign threshold = 4'd4;
endmodule
