// Generated by model/image_text_match/gen_rom.py from model/image_text_match/weights.json; do not edit.
// source sha256 a9c12d72043082ddd628a515d96ca3608c3c9a5004a0a23253ba8daca1a28352
`timescale 1ns/1ps
// Learned parameters of image_text_match (continuous assigns only).
//   kernel_a / kernel_b : 3-tap binary kernels of the two image neurons (bit i = weight of pixel i of a line)
//   thr_a / thr_b       : neuron thresholds (fire when matches >= thr)
//   emb                 : text embedding of `token`: 6 signed 3-bit weights, packed {B_diags, B_rows, B_cols, A_diags, A_rows, A_cols}
//   sim_thr             : class = (similarity >= sim_thr)
module image_text_match_rom (
    input  wire        [1:0]  token,
    output wire        [2:0]  kernel_a,
    output wire        [1:0]  thr_a,
    output wire        [2:0]  kernel_b,
    output wire        [1:0]  thr_b,
    output wire signed [6:0]  sim_thr,
    output wire        [17:0] emb
);
    assign kernel_a = 3'b000;
    assign thr_a    = 2'd3;
    assign kernel_b = 3'b111;
    assign thr_b    = 2'd3;
    assign sim_thr  = 7'sd3;
    // embedding rows: one per caption token
    assign emb = (token == 2'd0) ? {3'sd0, 3'sd0, 3'sd0, 3'sd0, 3'sd1, 3'sd0} :   // EMPTY
                 (token == 2'd1) ? {3'sd0, 3'sd0, 3'sd3, 3'sd0, 3'sd0, 3'sd0} :   // VERT
                 (token == 2'd2) ? {3'sd0, 3'sd3, 3'sd0, 3'sd0, 3'sd0, 3'sd0} :   // HORIZ
                                   {3'sd3, 3'sd0, 3'sd0, 3'sd0, 3'sd0, 3'sd0};    // DIAG
endmodule
