// Generated by model/precision_hw/gen.py from model/precision_hw/golden.py; do not edit.
// source sha256 bd114534c7c5336b459aecd7842971a1fa2183e1751e6a3c639c7effa9cbd748
`timescale 1ns/1ps
// prec_fp8 parameter ROM (model/precision_hw/spec.md): OCP fp8 E4M3 bit patterns (bias 7, no Inf; subnormals flushed to +0 at quantisation); the bias is in the same format.
// Constants are continuous assignments (no always block): read by the one serial MAC, weight[addr] per input.
module prec_fp8_rom (
    input  wire        [3:0]  addr,     // pixel index 0..8, raster order (>= 9 reads 0)
    output wire        [7:0]  weight,
    output wire        [7:0]  bias
);
    localparam [7:0]  W0 = 8'h00;   // +0  (fp32 +0.014786)
    localparam [7:0]  W1 = 8'h29;   // +0.28125  (fp32 +0.291126)
    localparam [7:0]  W2 = 8'h0F;   // +0.029296875  (fp32 +0.028851)
    localparam [7:0]  W3 = 8'hAA;   // -0.3125  (fp32 -0.316742)
    localparam [7:0]  W4 = 8'h8A;   // -0.01953125  (fp32 -0.019083)
    localparam [7:0]  W5 = 8'hA9;   // -0.28125  (fp32 -0.267208)
    localparam [7:0]  W6 = 8'h13;   // +0.04296875  (fp32 +0.044593)
    localparam [7:0]  W7 = 8'h29;   // +0.28125  (fp32 +0.294643)
    localparam [7:0]  W8 = 8'h00;   // +0  (fp32 +0.000830)
    localparam [7:0]  B  = 8'hA4;   // -0.1875  (fp32 bias -0.181312)
    assign weight = (addr == 4'd0) ? W0 :
                    (addr == 4'd1) ? W1 :
                    (addr == 4'd2) ? W2 :
                    (addr == 4'd3) ? W3 :
                    (addr == 4'd4) ? W4 :
                    (addr == 4'd5) ? W5 :
                    (addr == 4'd6) ? W6 :
                    (addr == 4'd7) ? W7 :
                    (addr == 4'd8) ? W8 : 8'h00;
    assign bias = B;
endmodule
