#!/usr/bin/env python3
"""gen_rom.py -- from weights.json and golden.py write designs/<eng>/rtl/<eng>_rom.v and designs/<eng>/tb/vectors.hex.
Outputs carry the sha256 of their inputs and are rewritten only when the content changes. Never edit the outputs;
change the inputs and re-run (make generate; make check-generated fails if re-running changes a file).
Vector record (16 bytes, shared/tb/stream_tb.vh): [0] beats (1..12), [1..12] s_data, [13] beat 0, [14] beat 1, [15] latency.
Header record: A5, count_hi, count_lo. At most 1023 cases (MAXREC = 1024). Pattern from model/tiny_ai/gen_rom.py."""
import hashlib, os
import golden

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = golden.REPO
MAX_BEATS, MAX_CASES = 12, 1023


def sha256_of(*paths):
    h = hashlib.sha256()
    for p in paths:
        h.update(os.path.relpath(p, REPO).encode() + b"\0" + open(p, "rb").read())
    return h.hexdigest()


def header(h):
    return ("// Generated by model/<eng>/gen_rom.py from model/<eng>/weights.json; do not edit.\n"
            "// source sha256 %s\n`timescale 1ns/1ps\n" % h)


def rom_verilog(w, h):
    bits = "".join(str(v) for v in reversed(w["weights"]))
    # continuous assignments ONLY: an always @(*) block whose input never changes is never evaluated in simulation
    return header(h) + """// One 1-bit weight per input (bit i of WEIGHTS) and the neuron threshold.
module <eng>_rom (
    input  wire [1:0] addr,
    output wire       weight,
    output wire [2:0] threshold
);
    localparam [3:0] WEIGHTS = 4'b%s;
    assign weight    = WEIGHTS[addr];
    assign threshold = 3'd%d;
endmodule
""" % (bits, w["threshold"])


def cases():
    n, vmax = golden.SPEC["inputs"], golden.SPEC["input_max"]
    out = [x for x, _ in golden.truth_table()]                  # every valid input
    full = [vmax] * n
    out += [full[:k] for k in range(1, n)]                      # short frames
    out += [full + [vmax], full + [0, vmax]]                    # long frames
    for i in range(n):                                          # out-of-range item at each position
        out += [full[:i] + [vmax + 1] + full[i + 1:], full[:i] + [0xFF] + full[i + 1:]]
    assert all(1 <= len(c) <= MAX_BEATS for c in out) and len(out) <= MAX_CASES, "too many cases for stream_tb.vh"
    return out


def vectors(w, h):
    cs = cases()
    lines = ["// Generated by model/<eng>/gen_rom.py from weights.json and golden.py; do not edit.",
             "// source sha256 %s" % h, "// <eng>: %d cases" % len(cs),
             " ".join("%02x" % v for v in [0xA5, len(cs) >> 8, len(cs) & 0xFF] + [0] * 13)]
    for c in cs:
        b0, b1, lat = golden.run(c, w)
        lines.append(" ".join("%02x" % v for v in [len(c)] + c + [0] * (MAX_BEATS - len(c)) + [b0, b1, lat]))
    return "\n".join(lines) + "\n"


def write_if_changed(path, text):               # keep timestamps: the flow's stale-run check compares them
    try:
        if open(path).read() == text:
            return
    except OSError:
        pass
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, "w").write(text)


def main():
    w = golden.params()
    h = sha256_of(golden.WEIGHTS_PATH, os.path.join(HERE, "golden.py"), os.path.abspath(__file__), os.path.join(HERE, "spec.json"))
    write_if_changed(os.path.join(REPO, "designs/<eng>/rtl/<eng>_rom.v"), rom_verilog(w, h))
    write_if_changed(os.path.join(REPO, "designs/<eng>/tb/vectors.hex"), vectors(w, h))


if __name__ == "__main__":
    main()
