#!/usr/bin/env python3
"""gen_expected.py <out.h> -- expected response beats of the KV-cache firmware session, generated by running
model/kv_attention/golden.py (Engine.command, variant kv_attn_n8). Nothing is hand-written.
Sessions P = 0..7: RESET_CACHE, PREFILL of P tokens (one frame), DECODE until the cache holds 8, one more DECODE
(CACHE_FULL, the baseline frame for the CYCLES comparison)."""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "model", "kv_attention"))
import golden

N = 8
rng = golden.LCG(2024)
out = ["/* GENERATED by firmware/kv/gen_expected.py from model/kv_attention/golden.py -- do not edit */",
       "#ifndef KV_EXPECTED_H", "#define KV_EXPECTED_H", "#include <stdint.h>", "#define NSESS %d" % (N), ""]
P_, prompt, nq, q, pre, dec, lat, full = [], [], [], [], [], [], [], []
for P in range(N):
    e = golden.Engine("kv_attn_n8")
    r, L, _ = e.command([golden.OPC_RESET]); assert r == [0, 0] and L == 2
    toks = [rng.below(16) for _ in range(P)]
    r, L, _ = e.command([golden.OPC_PREFILL] + toks); assert L == 2 and r == [0, P]
    pre.append(r)
    qs, ds, ls = [], [], []
    for i in range(N - P):
        t = rng.below(16)
        r, L, info = e.command([golden.OPC_DECODE, t])
        assert len(r) == 8 and L == P + i + 3
        qs.append(t); ds.append(r); ls.append(L)
    r, L, _ = e.command([golden.OPC_DECODE, 0]); assert r == [golden.E_FULL, N] and L == 2
    full.append(r)
    P_.append(P); prompt.append(toks + [0] * (8 - P)); nq.append(N - P)
    q.append(qs + [0] * (8 - len(qs))); dec.append(ds + [[0] * 8] * (8 - len(ds)))
def arr(name, rows, dims):
    out.append("static const uint8_t %s%s = {" % (name, dims))
    out.append(",\n".join("  {" + ",".join("0x%02x" % b for b in r) + "}" for r in rows))
    out.append("};")
arr("S_PROMPT", prompt, "[NSESS][8]")
arr("S_Q", q, "[NSESS][8]")
arr("S_PRE", pre, "[NSESS][2]")
arr("S_FULL", full, "[NSESS][2]")
out.append("static const uint8_t S_DEC[NSESS][8][8] = {")
out.append(",\n".join("  {" + ",".join("{" + ",".join("0x%02x" % b for b in r) + "}" for r in ds) + "}" for ds in dec))
out.append("};")
out.append("#endif")
open(sys.argv[1], "w").write("\n".join(out) + "\n")
