// Generated by model/precision_hw/gen.py from model/precision_hw/golden.py; do not edit.
// source sha256 bd114534c7c5336b459aecd7842971a1fa2183e1751e6a3c639c7effa9cbd748
`timescale 1ns/1ps
// prec_fp16 parameter ROM (model/precision_hw/spec.md): IEEE binary16 bit patterns (subnormals flushed to +0 at quantisation); the bias is in the same format.
// Constants are continuous assignments (no always block): read by the one serial MAC, weight[addr] per input.
module prec_fp16_rom (
    input  wire        [3:0]  addr,     // pixel index 0..8, raster order (>= 9 reads 0)
    output wire        [15:0] weight,
    output wire        [15:0] bias
);
    localparam [15:0] W0 = 16'h2392;   // +0.0147857666  (fp32 +0.014786)
    localparam [15:0] W1 = 16'h34A8;   // +0.291015625  (fp32 +0.291126)
    localparam [15:0] W2 = 16'h2763;   // +0.0288543701  (fp32 +0.028851)
    localparam [15:0] W3 = 16'hB511;   // -0.316650391  (fp32 -0.316742)
    localparam [15:0] W4 = 16'hA4E3;   // -0.0190887451  (fp32 -0.019083)
    localparam [15:0] W5 = 16'hB446;   // -0.267089844  (fp32 -0.267208)
    localparam [15:0] W6 = 16'h29B5;   // +0.0445861816  (fp32 +0.044593)
    localparam [15:0] W7 = 16'h34B7;   // +0.294677734  (fp32 +0.294643)
    localparam [15:0] W8 = 16'h12CD;   // +0.000830173492  (fp32 +0.000830)
    localparam [15:0] B  = 16'hB1CD;   // -0.181274414  (fp32 bias -0.181312)
    assign weight = (addr == 4'd0) ? W0 :
                    (addr == 4'd1) ? W1 :
                    (addr == 4'd2) ? W2 :
                    (addr == 4'd3) ? W3 :
                    (addr == 4'd4) ? W4 :
                    (addr == 4'd5) ? W5 :
                    (addr == 4'd6) ? W6 :
                    (addr == 4'd7) ? W7 :
                    (addr == 4'd8) ? W8 : 16'h0000;
    assign bias = B;
endmodule
