#!/usr/bin/env python3
# Purpose: Generate build/expected.h (expected results of the tiny_ai_core firmware self-test) from the Python golden model.
# Run: python3 gen_expected.py build/expected.h (a prerequisite rule in firmware/Makefile; make soc-sim).
# In: model/tiny_ai/{golden.py,common.py,weights.json}. Out: build/expected.h (generated, not committed).
# Docs: firmware/README.md
"""gen_expected.py <out.h> -- write the expected-value tables of the firmware self-test, generated from
model/tiny_ai/golden.py (core_run) and the labelled truth tables of model/tiny_ai/common.py, plus the learned
parameters from model/tiny_ai/weights.json for the pure-C software networks. Nothing here is hand-written.

Case packing: input item k sits at bits [2k+1:2k] of `in` (the same item order as the INPUT pushes).
Expected word: bit 0 class, bits 15:8 score byte (RESULT[15:8]), bits 23:16 CYCLES (tiny_ai_core), bit 24 label
(the labelled ground truth, which equals class: golden.py --check)."""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
# import the golden model in place (model/ is not a package); fixed deterministic data, so the header is reproducible
sys.path.insert(0, os.path.join(HERE, "..", "model", "tiny_ai"))
import golden
from common import DESIGNS, truth_table, spec

w = golden.params()
out = ["/* GENERATED by firmware/gen_expected.py from model/tiny_ai/golden.py and weights.json -- do not edit */",
       "#ifndef EXPECTED_H", "#define EXPECTED_H", "#include <stdint.h>",
       "typedef struct { uint32_t in; uint32_t exp; } tcase_t;"]
for d in DESIGNS:
    s = spec()["designs"][d]
    rows = truth_table(d)
    out.append("#define N_%s %d" % (d.upper(), len(rows)))
    out.append("#define MODE_%s %d" % (d.upper(), s["mode"]))
    out.append("#define LEN_%s %d" % (d.upper(), s["inputs"]))
    out.append("static const tcase_t cases_%s[N_%s] = {" % (d, d.upper()))
    for items, label in rows:
        mode, cls, score, cyc = golden.core_run(d, items, w)
        assert cls == label   # the reference must agree with the labelled truth table, else the firmware test is meaningless
        pk = sum(v << (2 * k) for k, v in enumerate(items))
        ex = cls | (score & 0xFF) << 8 | cyc << 16 | label << 24
        out.append("  {0x%05x,0x%08x}," % (pk, ex))
    out.append("};")
a = w["vision_all_lit"]; b = w["vision_block"]; t = w["text_sentiment"]
out.append("static const uint8_t W_ALL_LIT[4] = {%s};" % ",".join(map(str, a["weights"])))
out.append("#define TH_ALL_LIT %d" % a["threshold"])
out.append("static const uint8_t K_BLOCK[4] = {%s};" % ",".join(map(str, b["kernel"])))
out.append("#define TH_BLOCK %d" % b["threshold"])
out.append("static const int8_t EMB_TEXT[4] = {%s};" % ",".join(map(str, t["embedding"])))
out.append("#define TH_TEXT %d" % t["threshold"])
out.append("#endif")
open(sys.argv[1], "w").write("\n".join(out) + "\n")
